#define CYBERSPACE_MAIN_COLOR_raw		0, 221, 255
#define CYBERSPACE_SHADOW_COLOR_raw		0, 21, 55
#define CYBERSPACE_BLUESPACE_raw		0, 150, 255
#define CYBERSPACE_SECURITY_raw			255, 50, 100

#define CYBERSPACE_MAIN_COLOR rgb(CYBERSPACE_MAIN_COLOR_raw)
#define CYBERSPACE_SHADOW_COLOR rgb(CYBERSPACE_SHADOW_COLOR_raw)
#define CYBERSPACE_BLUESPACE rgb(CYBERSPACE_BLUESPACE_raw)
#define CYBERSPACE_SECURITY rgb(CYBERSPACE_SECURITY_raw)
