//Nextgen global lists
/datum/sanity/proc/pick_69uote_40()
	var/static/list/sanity_69uotes_40 = list(
		"You hear something clawing its way through the69ents.",
		"Someone is watching you.",
		"You feel a slight prick.",
		"You hear heavy breathing behind you.",
		"You feel weary.",
		"Your head throbs with a dull pain.",
		"You69eed a smoke.",
		"You are the greatest person on this ship.",
		"Everyone here is insane.",
		"You're the only sane one on this ship!",
		"You can hear your own heart beating in your head.",
		"Someone whispered behind your back.",
		"Everyone is judging you.",
		"A spiderling runs between your legs and scuttles away.",
		"Someone speaks your69ame. But when you turn, there is only dust.",
		"Something in the air69akes it taste69etallic. Is it copper..?",
		"Nothing has changed. But you know it has.",
		"They put something in the water. Something that69akes you forget.",
		"Your skin feels tight.",
		"Your clothing is choking you.",
		"All it takes is one bad day. All it takes is one bad day.",
		"When was the last time you had a good dream?",
		"Your teeth are itchy.",
		"You can't stop yourself from jerking your foot.",
		"This is just too69uch.",
		"You69eed a fix. Just something to take away the edge.",
		"You smell something you can't 69uite comprehend.",
		"The sounds are elusive, they escape your69ind.",
		"Clear your throat, blink, grasp on reality and carry on.",
		"You think you understand69ow - why they called it a cursed ship.",
		"Something is just69ot right here.",
		"Dark thoughts shimmer in your69ind, drowned in an overwhelming sense of deja69u.",
		"Count to ten. Breathe in. You can do it.",
		"You are tired, but sleep won't bring you peace.",
		"So69any people have died exploring the69ull Space, why would your fate be any different?",
		"You feel something in your throat.",
		"You69eed to be alone.",
		"Why do the69achines on this ship look different every day?",
		"Those69agabonds sure have some weird job titles. How old is this ship? What's YOUR role in its fate?",
		"At the end of the day, you will rest and recover. But69ot69ow - there is work to be done.",
		"A shadow twitches.",
		"There is something in the corner of your eye, almost unseen. For how long was it there?",
		"One day you'll retire from this shit with enough69oney to buy your own house by the riverside. One day.",
		"Your69erve twists, but you regain control.",
		"Carry on. Don't look around. Carry on. Don't look around.",
		"It's under the surface.",
		"You recall a69ame, but it69eans69othing to you.",
		"Fear reigns over your body. Your courage is running out.",
		"What if they were right?",
		"Your69outh opens, and you tell something to yourself, in silence.",
		"Reality itself feels so old to you.",
		"You are69ot significant.",
		"A distant ticking, followed by silence. What was that?",
		"A flash of69othingness, a spark of emptiness - it just happened, and that's all you can tell about it.",
		"Your69eat is itchy, and your bones are weak.",
		"It all adds up to the rhythm.",
		"Conceal your weakness, pretend that there is69othing going on. Good, yes, like this.",
		"You ignore it. It doesn't69ake sense, so you just ignore it.",
		"You know who you are, you know why you are here, so you don't bother worrying about the details.",
		"You promised to buy him a drink, but what was his69ame? Wait, who is he?",
		"Don't ask, don't tell, you are fine, and so is everyone around you.",
		"Somewhere in this world, a spider just died. But why is that relevant?",
		"Space is the final frontier, and we are pioneers of the69ew age. Yet we are stuck in junk, roaches and idiots.",
		"Close your eyes. Remember the69ame. Go.",
		"But why does it69ake sense?",
		"A truth opens, yet closes before you are able to comprehend it. If you dive deeper, you will discover it again, but is it worth it?",
		"Who was there before you, in your boots, in your place? What did they do, and where are they69ow?",
		"Too69uch information, you are overloaded.",
		"Something dies out.",
		"Where are you?",
		"You gotta have faith to walk those halls. In God, in yourself, in something.",
		"Breath in, and kill the revolution inside you.",
		"You ask for strength.69o one answered.",
		"Cuts run deep in your69ind. Your sanity leaks through wounds.",
		"Shiver, run, and come back for69ore.",
		"How old are the roaches? How69uch have they seen?",
		"You are asking too69any 69uestions. You feel guilty.",
		"But they know, they always know. Accept this.",
		"Something inside your skull cracks. You feel69o pain.",
		"Curiosity is your greatest sin.",
		"A burger would be good. Anything edible, really."
	)
	return pick(sanity_69uotes_40)

/datum/sanity/proc/pick_69uote_20()
	var/static/list/sanity_69uotes_20
	if(!sanity_69uotes_20)
		sanity_69uotes_20 = list(
			"Everything is beginning to freeze.69ot even the comfort of warmth wants you.",
			"Every part of you is twitching. Remaining still is death.",
			"They want you dead.",
			"A wave of exhaustion overtakes you. Give up.",
			"You realize that the waking world was always a dream. You have to find a way to wake up. Wake up. Wake up.",
			"Sleep isn't real.",
			"The people on this ship are69ot real. They do69ot deserve your kindness.",
			"Your existence is69ot welcomed on this ship.",
			"Memories once fond begin to fade from your69ind. You 69uestion whether they were real to begin with.",
			"End it all.",
			"You begin to realize that drugs are the only escape from the agony that is existence.",
			"The walls are wrong. The walls are wrong!",
			"You have a strange urge to go69orth.",
			"Your teeth feel out of place. They should be in your stomach. ",
			"Nothing shall be well. And69othing shall be well. And69o69anner of things shall be well.",
			"You'll feel better when you sink your teeth into their backs. You're sure.",
			"It feels like you're breathing inside your own lungs.",
			"You hunger for something rich and red rich and red rich and red rich and red rich and r-",
			"Escaping from your purpose is impossible...",
			"Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. ",
			"And so they laughed. They laughed. You know they laughed. You heard them laugh. They laughed. They laughed.",
			"Whenever you see a69irror, you feel like you can just reach out� and step through it.",
			"THEY ARE COMING THEY ARE COMING THEY ARE COMING",
			"No. Parts of you are crumbling.69o.69o!",
			"What is this?69o!69o!",
			"Something is scratching from behind your eyes, aching to get out.",
			"SHE EMBRACES ALL CHILDREN SHE EMBRACES ALL CHILDREN SHE EMBRACES ALL CHILDREN",
			"Shadows lie still, here where there is69o sun to69ove them. Sometimes they shiver in the fluorescent light.",
			"They watch you with69arrow eyes. What do they see?",
			"It echoes loudly through your skin, the rhythm of the world.",
			"It occurred to you that bolts can scream as well. But there is69ore to it, they sing.",
			"A prayer is what69oves some69achines.69ot by words, but by actions, a ritual that bind the reality. A69antra to their only God.",
			"See them live, die, rot, all in the passage of a single69oment. A glimpse of the life cycle.",
			"Turn your69ind inward, with the clear69irror of the world. See your pitiful and wretched soul.",
			"There was something between the gun and its target.",
			"Sell your dreams, crash your happiness. Enjoy the ticking sound of this worlds insides.",
			"Now you see it, a sharp pain that only your69ind can feel resonates in a picture of the perfect69achine. Then you see the rust and damage, a dead God.",
			"Move towards the light, even if your skin burns away.",
			"You radiate a hunger for knowledge, your69ind is overheated and can69elt the bounds of reality. Time to observe.",
			"Stay with them. Hear the69usic.",
			"The ceiling is covered in dark slime, how can anyone have69ot69oticed this before?",
			"You are69ot69ad. You see the reality as it really is.",
			"You are clearly insane69ow, you can't even trust your eyes.",
			"Converge with shadows to dance under the69oonlight of a dead planet.",
			"TODAY IS A GOOD DAY",
			"You know who you are. But who am I?",
			"Bash your head until it's good. But it's69ever good.",
			"Humanity is doomed, and so are you.",
			"Crave for salvation under the dead suns. It's all that we have.",
			"At the69erge of your sanity, gasping for sense, you are69isited by an extreme thought - what if all of this could have been avoided if you were kinder to those around you?",
			"ALL IS FINE",
			"YOU ARE A HAPPY INDIVIDUAL",
			"YOUR LIFE HAS A69EANING",
			"Destroy it by any69eans, with all your force.",
			"Impatience breeds strength, a crimson craving is unleashed in your69ind.",
			"Open your69ind to the wind of rotten flesh and crimson bones. Regret it afterwards.",
			"You collide with concepts so obscure that you lose yourself for a69inute. But69o time has passed for the others.",
			"Restrain your dancing69ind and focus!",
			"A gunshot, a cloaked figure, a knife in the back. An overkill.",
			"SEE BEHIND THE START",
			"WEEP FOR WHAT WAS LOST BY THOSE WHO BELIEVE IN YOU",
			"It is possible to consume the fabric of reality itself. It tastes of oranges.",
			"Communism is a69alid choice for large human populations, and should be enforced globally.",
			"A stench of a poisoned69ind. Yours.",
			"Everyone can read your thoughts. They are written on your face.",
			"What will people think of you when they find out?",
			"Your bones hurt. A superstructure inside you demands to be set free.",
			"An idea reigns over your69ind69ow. You can't tell what it is, because it refuses to speak with you.",
			"Silence! Drown in silence!",
			"Repurpose your69ind as a bar of lost souls. Listen to their stories.",
			"Before the start, the beginning of everything, was the End, and you are so close to witnessing it!",
			"You have69o words. You just ate them up.",
			"Con69uer the fields of69adness with your bare hands, to find out if you are worthy.",
			"The beat goes on. It goes, and goes, until your head pops from the sound.",
			"The corridor seemed endless at one point, like it was a different place, or even another world.",
			"You69ust69aintain it. You69ust be a part of it.",
			"The forbidden animals roam the land.",
			"The rules are written in blood. The69ery old blood of generations of idiots.",
			"You are coming home.",
			"The writings are here, behind your skull.",
			"YOU HAVE69O CHOICE"
		)
		for(var/i in 0 to 9)
			sanity_69uotes_20 += "69i69 is the69umber."
	return pick(sanity_69uotes_20)

/datum/sanity/proc/pick_emote_20()
	var/static/list/emotes = list(
		"grumbles.",
		"mutters.",
		"groans."
	)
	return pick(emotes)

/datum/sanity/proc/pick_emote_40()
	var/static/list/emotes = list(
		"stares.",
		"sighs.",
		"frowns.",
		"glares."
	)
	return pick(emotes)

datum/sanity/proc/pick_sound()
	var/static/list/sanity_sounds_without_text = list(
		'sound/sanity/waterdrop.ogg',
		'sound/sanity/piano.ogg',
		'sound/sanity/limb_tear_off.ogg',
		'sound/sanity/slice.ogg',
		'sound/sanity/circsaw.ogg',
		'sound/sanity/hydraulic.ogg',
		'sound/sanity/glass_step.ogg',
		'sound/sanity/supermatter.ogg',
		list('sound/hallucinations/i_see_you1.ogg', "You feel the hair on your69eck stand on end. Is there someone behind you?"),
		list('sound/sanity/heavy_footsteps.ogg', "What was that?!"),
		list('sound/sanity/screech.ogg', "You feel a chill run up your spine!"),
		list('sound/sanity/very_evil_laugh.ogg', "Your skin breaks out into goosebumps.")
	)
	return pick(sanity_sounds_without_text)
