//Nextgen global lists
/datum/sanity/proc/pick_quote_40()
	var/static/list/sanity_quotes_40 = list(
		"You hear something clawing its way through the vents.",
		"Someone is watching you.",
		"You feel a slight prick.",
		"You hear heavy breathing behind you.",
		"You feel weary.",
		"Your head throbs with a dull pain.",
		"You need a smoke.",
		"You are the greatest person on this ship.",
		"Everyone here is insane.",
		"You're the only sane one on this ship!",
		"You can hear your own heart beating in your head.",
		"Someone whispered behind your back.",
		"Everyone is judging you.",
		"A spiderling runs between your legs and scuttles away.",
		"Someone speaks your name. But when you turn, there is only dust.",
		"Something in the air makes it taste metallic. Is this copper..?",
		"Nothing has changed. But you know it did.",
		"They put something in the water. Something that makes you forget.",
		"Your skin feels tight.",
		"Your clothing is choking you.",
		"All it takes is one bad day. All it takes is one bad day.",
		"When was the last time you had a good dream?",
		"Your teeth are itchy.",
		"You can't stop yourself from jerking your foot.",
		"This is just too much.",
		"You need a fix. Just a bit to take away the edge.",
		"You smell something you can't quite comprehend.",
		"The sounds are elusive, they escape your mind.",
		"Clear your throat, blink, grasp on reality and carry on.",
		"You think you understand now, why they called it a cursed ship.",
		"Something just not right here.",
		"Dark thoughts glimpse in your mind, drowned in an overwhelming sense of deja vu.",
		"Count to ten. Breathe in. You can do it.",
		"You are tired, but sleep won't bring you peace.",
		"So many people have died exploring a Null Space, why would your fate will be different?",
		"You got something in your throat.",
		"You need be alone.",
		"Why machines on this ship look a bit different each day?",
		"Those Vagabonds sure got some weird job titles, how old is this ship? What's YOUR role in it's fate?",
		"At the end of the day, you will rest and recover. But not now, there is work to be done.",
		"A shadow thwiches.",
		"There is something in the corner of your eye, almost unseen. For how long it was there?",
		"One day you will retire of this shit with a money large enough to buy your own house at the riverside. One day.",
		"Your nerve twists, but you regain control.",
		"Carry on. Don't look around. Carry on. Don't look around.",
		"It's under the surface.",
		"You recall a name, but it's mean nothing to you.",
		"Fear reigns over you body. Courage is running out.",
		"What if they were right?",
		"Your month open, you tell something to yourself, in silence.",
		"The reality itself feels so old for you.",
		"You are not significant.",
		"A distant ticking, followed by a death of spring. What was that?",
		"A flash of nothingness, a spark of emptiness, it just happened, and it's all you can tell about it.",
		"Your meat is itchy, and bones are weak.",
		"It all adds up to the rhythm.",
		"Conceal your weakness, pretend that there is nothing going on. Good, yes, like this.",
		"You ignore it. It's all not makes sense, so you just ignore it.",
		"You know who you are, you know why you are here, so you don't bother with a details of the mind.",
		"You promised to buy him a drink, but what was his name? Wait, who is he?",
		"Don't ask, don't tell, you are fine, and so do people around you.",
		"Somewhere in this world, a spider just died. But why this is relevant?",
		"Space is the final frontier, and we are pioneers of the new age. Yet we stuck in junk, roaches and idiots.",
		"Close your eyes. Remember the name. Go.",
		"But why does it make sense?",
		"A truth opens, yet closes before you was able to comprehend it. If you dive deeper, you will discover it again, but is it worth it?",
		"Who was there before you, in your boots, in your place? What do they do, and where are they now?",
		"Too much information, you are overloaded.",
		"Something dies out.",
		"Where are you?",
		"You gotta have faith to walk those halls. In God, yourself, in something.",
		"Breath in, and kill the revolution inside you.",
		"You ask for strength. No one answered.",
		"Cuts run deep in your mind. Your sanity leaks through wounds.",
		"Shiver, run, and come back for more.",
		"How old are roaches? How much did they saw?",
		"You are asking too many questions. You feel guilty.",
		"But they know, they always know. Accept this.",
		"Something inside your skull cracks. You feel no pain.",
		"Curiosity is your greatest sin.",
		"A burger could be good. Any tasty food, really."
	)
	return pick(sanity_quotes_40)

/datum/sanity/proc/pick_quote_20()
	var/static/list/sanity_quotes_20
	if(!sanity_quotes_20)
		sanity_quotes_20 = list(
			"Everything is beginning to freeze. Not even the comfort of warmth wants you.",
			"Every part of you is twitching. Remaining still is death.",
			"They want you dead.",
			"A wave of exhaustion overtakes you. Give up.",
			"You realize that the waking world was always a dream. You have to find a way to wake up. Wake up. Wake up.",
			"Sleep isn't real.",
			"The people on this ship are not real. They do not deserve your kindness.",
			"Your existence is not welcomed on this ship.",
			"Memories once fond begin to fade from your mind. You question whether they were real to begin with.",
			"End it all.",
			"You begin to realize that drugs are the only escape from the agony that is existence.",
			"The walls are wrong. The walls are wrong!",
			"You have a strange urge to go North.",
			"Your teeth feel out of place. They should be in your stomach. ",
			"Nothing shall be well. And nothing shall be well. And no manner of things shall be well.",
			"You'll feel better when you sink your teeth into their backs. You're sure.",
			"It feels like you're breathing inside your own lungs.",
			"You hunger for something rich and red rich and red rich and red rich and red rich and r-",
			"Escaping from your purpose is impossible...",
			"Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. ",
			"And so they laughed. They laughed. You know they laughed. You heard them laugh. They laughed. They laughed.",
			"Whenever you see a mirror, you feel like you can just reach out… and step through it.",
			"THEY ARE COMING THEY ARE COMING THEY ARE COMING",
			"No. Parts of you are crumbling. No. No!",
			"What is this? No… No!",
			"Something is scratching from behind your eyes, aching to get out.",
			"SHE EMBRACES ALL CHILDREN SHE EMBRACES ALL CHILDREN SHE EMBRACES ALL CHILDREN",
			"Shadows lie still, here where there is no sun to move them. Sometimes they shiver in fluorescent-light.",
			"They watch you with narrow eyes. What do they see?",
			"It echoes loudly through your skin, the rhythm of the world.",
			"It occurred to you that bolts can scream as well. But there is more to it, they sing.",
			"A prayer is what moves some machines. Not by words, but by actions, a rituals that bind the reality. A mantra to their only God.",
			"See them live, die, rot, in a single moment passed. A glimpse of a life cycle.",
			"Turn your mind towards you, as a world clearest mirror. See the pity and wretched soul that's you.",
			"There was something between a gun and that target.",
			"Sell your dreams, crash your happiness. Enjoy the ticking sound of this worlds insides.",
			"Now you see it, a sharp pain that only your mind can feel resonates in a picture of the perfect machine. Then you see the rust and damage, a dead God.",
			"Move towards the light, even if your skin burns away.",
			"You radiate a hunger for knowledge, your mind is overheated and can melt the bounds of reality. Time to observe.",
			"Stay with them. Hear the music.",
			"The ceiling is covered in dark slime, how can anyone never noticed this before?",
			"You are not mad. You see the reality as it really are.",
			"You are clearly insane now, you can't trust your eyes.",
			"Converge with shadows to dance under the moonlight of dead planet.",
			"TODAY IS A GOOD DAY",
			"You know who you are. But who am I?",
			"Bash your head until it's good. It's never good.",
			"Humanity is doomed, and so do you.",
			"Crave for salvation under a dead suns. It's all that we have.",
			"At a verge of your sanity, gasping for sense, you are visited by an extreme though, what if all of this could have been avoided if you were more kind to people around you?",
			"ALL IS FINE",
			"YOU ARE A HAPPY INDIVIDUAL",
			"YOUR LIFE HAVE A MEANING",
			"Destroy it by any means, with all your force.",
			"Impatience breeds stronger, a crimson craving is unleashed in your mind.",
			"Open your mind to the wind of rotten flesh and crimson bones. Regret it afterwards.",
			"You collide with concepts so obscure that you lost yourself for a minute. But no time passed for the rest.",
			"Restrain your dancing mind and focus!",
			"A gunshot, a cloaked figure, a knife in the back. An overkill.",
			"SEE BEHIND THE START",
			"WEEP FOR WHAT WAS LOST BY THOSE WHO BELIEVE IN YOU",
			"It is possible to consume the fabric of reality itself. It tastes of oranges.",
			"A communism is a valid choice for large human populations, and should be enforced globally.",
			"A stench of a poisoned mind. Yours.",
			"Everyone can read your thoughts. They are written on your face.",
			"What people will think of you when they found out?",
			"Your bones hurt. A superstructure inside demands to be set free.",
			"An idea reign over your mind now. You can't tell what it is about, because it refuses to speak with you.",
			"Silence! Drown in silence!",
			"Repurpose your mind as bar of lost souls. Listen to their stories.",
			"Before the start, the beginning of everything, was the End, and you are so close to see it!",
			"You have no words. You just ate them up.",
			"Conquer the fields of madness with your bare hands, to find out if you are worthy.",
			"The beat goes on. It goes, and goes, until your head will pop from sound.",
			"A corridor seemed endless at some point, like it was a different place, or even another world.",
			"You must maintain it. You must be a part of it.",
			"The forbidden animals roam the land.",
			"The rules are written in blood. Very old blood of generations of idiots.",
			"You are coming home.",
			"The writings are here, behind your skull.",
			"YOU HAVE NO CHOICE"
		)
		for(var/i in 0 to 9)
			sanity_quotes_20 += "[i] is the number."
	return pick(sanity_quotes_20)

/datum/sanity/proc/pick_emote_20()
	var/static/list/emotes = list(
		"shivers",
		"stares at something blindly for a moment.",
		"looks disoriented for a moment."
	)
	return pick(emotes)

/datum/sanity/proc/pick_emote_40()
	var/static/list/emotes = list(
		"have a zombie stare",
		"is about to snap.",
		"rapidly and loudly tilts their head in unusual angle.",
		"laughs a bit.",
		"sobs for a moment."
	)
	return pick(emotes)

datum/sanity/proc/pick_sound()
	var/static/list/sanity_sounds_without_text = list(
		'sound/sanity/waterdrop.ogg',
		'sound/sanity/piano.ogg',
		'sound/sanity/limb_tear_off.ogg',
		'sound/sanity/slice.ogg',
		'sound/sanity/circsaw.ogg',
		'sound/sanity/hydraulic.ogg',
		'sound/sanity/glass_step.ogg',
		'sound/sanity/supermatter.ogg',
		list('sound/hallucinations/i_see_you1.ogg', "You hear someone behind you."),
		list('sound/sanity/heavy_footsteps.ogg', "You hear that something heavy behind you."),
		list('sound/sanity/screech.ogg', "You've got goosebumps."),
		list('sound/sanity/very_evil_laugh.ogg', "You hear an evil laugh.")
	)
	return pick(sanity_sounds_without_text)
