/obj/random/lowkeyrandom //Absolutly random things
	name = "random stuff"
	icon_state = "radnomstuff-green"

/obj/random/lowkeyrandom/item_to_spawn()
	return pick(prob(1);/obj/item/weapon/storage/box/shotgunammo/beanbags,\
				prob(1);/obj/item/ammo_magazine/mc9mmt/rubber,\
				prob(3);/obj/item/weapon/storage/box/matches,\
				prob(2);/obj/item/stack/material/cardboard,\
				prob(3);/obj/item/weapon/cell/large,\
				prob(6);/obj/item/weapon/cell/medium,\
				prob(7);/obj/item/weapon/cell/small,\
				prob(3);/obj/item/stack/medical/bruise_pack,\
				prob(2);/obj/item/bodybag/cryobag,\
				prob(2);/obj/item/weapon/reagent_containers/syringe/inaprovaline,\
				prob(4);/obj/item/weapon/cigbutt,\
				prob(2);/obj/item/device/t_scanner,\
				prob(2);/obj/item/device/scanner/analyzer,\
				prob(2);/obj/item/device/scanner/healthanalyzer,\
				prob(5);/obj/item/weapon/tool/screwdriver,\
				prob(5);/obj/item/weapon/tool/wirecutters,\
				prob(5);/obj/item/weapon/tool/weldingtool,\
				prob(5);/obj/item/weapon/tool/crowbar,\
				prob(5);/obj/item/weapon/tool/wrench,\
				prob(5);/obj/item/weapon/storage/belt/utility/full,\
				prob(4);/obj/item/weapon/storage/belt/medical,\
				prob(4);/obj/item/weapon/storage/belt/security,\
				prob(3);/obj/item/weapon/tool/pickaxe,\
				prob(3);/obj/item/weapon/pen,\
				prob(3);/obj/item/weapon/storage/box/donkpockets,\
				prob(2);/obj/item/weapon/locator,\
				prob(3);/obj/item/weapon/dice,\
				prob(2);/obj/item/weapon/clipboard,\
				prob(3);/obj/item/weapon/airlock_electronics,\
				prob(3);/obj/item/weapon/weldpack,\
				prob(2);/obj/item/weapon/soap,\
				prob(4);/obj/item/weedkiller/triclopyr,\
				prob(4);/obj/item/weedkiller,\
				prob(4);/obj/item/weedkiller/lindane,\
				prob(4);/obj/item/weedkiller/D24,\
				prob(3);/obj/item/weapon/phone,\
				prob(2);/obj/item/weapon/cane,\
				prob(1);/obj/item/weapon/cane/concealed,\
				prob(2);/obj/item/weapon/staff/broom,\
				prob(1);/obj/item/weapon/circuitboard/apc,\
				prob(1);/obj/item/weapon/tool/shovel,\
				prob(2);/obj/item/weapon/folder,\
				prob(2);/obj/item/weapon/folder/blue,\
				prob(2);/obj/item/weapon/folder/red,\
				prob(2);/obj/item/weapon/folder/yellow,\
				prob(2);/obj/item/weapon/folder/white,\
				prob(2);/obj/item/weapon/paper_bin,\
				prob(2);/obj/item/device/flash,\
				prob(4);/obj/item/device/camera_film,\
				prob(3);/obj/item/device/radio,\
				prob(1);/obj/item/device/debugger,\
				prob(1);/obj/item/device/aicard,\
				prob(2);/obj/item/weapon/storage/box/botanydisk,\
				prob(2);/obj/item/weapon/storage/box/ids,\
				prob(2);/obj/item/weapon/storage/briefcase/crimekit,\
				prob(2);/obj/item/weapon/storage/box/drinkingglasses,\
				prob(2);/obj/item/weapon/hatton_magazine,\
				prob(2);/obj/item/weapon/hand_labeler,\
				prob(2);/obj/item/weapon/tool/bonesetter,\
				prob(2);/obj/item/weapon/tool/scalpel,\
				prob(2);/obj/item/weapon/tool/surgicaldrill,\
				prob(2);/obj/item/weapon/tool/cautery,\
				prob(2);/obj/item/weapon/tool/retractor,\
				prob(2);/obj/item/weapon/tool/saw/circular,\
				prob(3);/obj/item/weapon/mop,\
				prob(3);/obj/item/weapon/lipstick/random,\
				prob(2);/obj/item/weapon/inflatable_dispenser,\
				prob(2);/obj/item/weapon/grenade/chem_grenade/cleaner,\
				prob(2);/obj/item/weapon/smes_coil,\
				prob(2);/obj/item/weapon/tank/anesthetic,\
				prob(2);/obj/item/weapon/tank/nitrogen,\
				prob(3);/obj/item/clothing/mask/balaclava,\
				prob(3);/obj/item/clothing/mask/gas,\
				prob(2);/obj/item/clothing/head/ushanka,\
				prob(1);/obj/item/clothing/head/welding,\
				prob(3);/obj/item/clothing/gloves/insulated/cheap,\
				prob(2);/obj/item/clothing/gloves/insulated,\
				prob(2);/obj/item/clothing/head/soft/blue,\
				prob(2);/obj/item/clothing/head/soft/green,\
				prob(2);/obj/item/clothing/head/soft/grey,\
				prob(2);/obj/item/device/taperecorder,\
				prob(2);/obj/item/weapon/storage/briefcase,\
				prob(2);/obj/item/weapon/storage/secure/briefcase,\
				prob(2);/obj/item/device/binoculars,\
				prob(1);/obj/item/taperoll,\
				prob(1);/obj/item/toy/crossbow,\
				prob(1);/obj/item/toy/cultsword,\
				prob(1);/obj/item/weapon/reagent_containers/food/drinks/bottle/small/beer,\
				prob(1);/obj/item/weapon/reagent_containers/food/drinks/bottle/vodka,\
				prob(1);/obj/item/weapon/circuitboard/communications,\
				prob(2);/obj/item/weapon/circuitboard/broken,\
				prob(1);/obj/item/weapon/airlock_electronics,\
				prob(1);/obj/item/rig_module/maneuvering_jets,\
				prob(1);/obj/item/rig_module/device/drill,\
				prob(1);/obj/item/clothing/glasses/meson,\
				prob(1);/obj/item/clothing/glasses/night,\
				prob(2);/obj/item/weapon/computer_hardware/battery_module,\
				prob(2);/obj/item/weapon/computer_hardware/card_slot,\
				prob(2);/obj/item/weapon/computer_hardware/hard_drive,\
				prob(2);/obj/item/weapon/computer_hardware/network_card,\
				prob(2);/obj/item/weapon/computer_hardware/processor_unit,\
				prob(2);/obj/item/weapon/computer_hardware/tesla_link,\
				prob(2);/obj/item/weapon/stock_parts/console_screen,\
				prob(2);/obj/item/weapon/stock_parts/capacitor,\
				prob(2);/obj/item/weapon/stock_parts/manipulator,\
				prob(2);/obj/item/weapon/stock_parts/matter_bin,\
				prob(2);/obj/item/weapon/stock_parts/micro_laser,\
				prob(2);/obj/item/weapon/stock_parts/scanning_module,\
				prob(1);/obj/item/weapon/stock_parts/subspace/amplifier,\
				prob(1);/obj/item/weapon/stock_parts/subspace/analyzer,\
				prob(1);/obj/item/weapon/stock_parts/subspace/ansible,\
				prob(1);/obj/item/weapon/stock_parts/subspace/crystal,\
				prob(1);/obj/item/weapon/stock_parts/subspace/filter,\
				prob(1);/obj/item/weapon/stock_parts/subspace/transmitter,\
				prob(1);/obj/item/weapon/stock_parts/subspace/treatment,\
				prob(1);/obj/item/weapon/aiModule/reset,\
				prob(1);/obj/item/weapon/circuitboard/autolathe,\
				prob(1);/obj/item/ammo_magazine/cl32/rubber,\
				prob(1);/obj/item/ammo_magazine/cl32,\
				prob(1);/obj/item/ammo_magazine/sl357,\
				prob(1);/obj/item/ammo_magazine/sl38,\
				prob(1);/obj/item/ammo_magazine/sl38/rubber,\
				prob(1);/obj/item/weapon/flamethrower,\
				prob(1);/obj/item/weapon/gun/projectile/mk58,\
				prob(1);/obj/item/weapon/gun/projectile/giskard,\
				prob(1);/obj/item/weapon/gun/projectile/revolver/deckard,\
				prob(1);/obj/item/weapon/gun/projectile/revolver/detective)

/obj/random/lowkeyrandom/low_chance
	name = "low chance random stuff"
	icon_state = "radnomstuff-green-low"
	spawn_nothing_percentage = 60
