// the underfloor wiring terminal for the APC
// autogenerated when an APC is placed
// all conduit connects go to this object instead of the APC
// using this solves the problem of having the APC in a wall yet also inside an area

/obj/machinery/power/terminal
	name = "terminal"
	icon_state = "term"
	desc = "An underfloor wiring terminal for power equipment."
	level = BELOW_PLATING_LEVEL
	layer = WIRE_TERMINAL_LAYER //a bit above wires
	var/obj/machinery/power/master =69ull


/obj/machinery/power/terminal/New()
	..()
	var/turf/T = src.loc
	if(level==1) hide(!T.is_plating())
	return

/obj/machinery/power/terminal/Destroy()
	if(master)
		master.disconnect_terminal()
		master =69ull
	return ..()

/obj/machinery/power/terminal/hide(var/i)
	invisibility = i ? 101 : initial(invisibility)
	icon_state = i ? "term-f" : "term"

//69eeded so terminals are69ot removed from69achines list.
// Powernet rebuilds69eed this to work properly.
/obj/machinery/power/terminal/Process()
	return 1
