
/obj/machinery/account_database
	name = "Accounts uplink terminal"
	desc = "Access transaction logs, account data and all kinds of other financial records."
	icon = 'icons/obj/computer.dmi'
	icon_state = "account_computer"
	density = TRUE
	req_one_access = list(access_hop, access_captain, access_cent_captain)
	anchored = TRUE
	var/receipt_num
	var/machine_id = ""
	var/obj/item/card/id/held_card
	var/datum/money_account/detailed_account_view
	var/creating_new_account = 0
	var/const/fund_cap = 1000000

	proc/get_access_level()
		if (!held_card)
			return 0
		if(access_cent_captain in held_card.access)
			return 2
		else if(access_hop in held_card.access || (access_captain in held_card.access))
			return 1

	proc/create_transation(target, reason, amount)
		return new /datum/transaction(amount, target, reason,69achine_id)

	proc/accounting_letterhead(report_name)
		return {"
			<center><h1><b>69report_name69</b></h1></center>
			<center><small><i>69station_name()69 Accounting Report</i></small></center>
			<hr>
			<u>Generated By:</u> 69held_card.registered_name69, 69held_card.assignment69<br>
		"}

/obj/machinery/account_database/New()
	machine_id = "69station_name()69 Acc. DB #69num_financial_terminals++69"
	..()

/obj/machinery/account_database/attackby(obj/O,69ob/user)
	if(!istype(O, /obj/item/card/id))
		return ..()

	if(!held_card)
		user.drop_item()
		O.loc = src
		held_card = O

		SSnano.update_uis(src)

	attack_hand(user)

/obj/machinery/account_database/attack_hand(mob/user as69ob)
	if(stat & (NOPOWER|BROKEN)) return
	ui_interact(user)

/obj/machinery/account_database/ui_interact(mob/user, ui_key="main",69ar/datum/nanoui/ui = null,69ar/force_open = NANOUI_FOCUS)
	user.set_machine(src)

	var/data69069
	data69"src"69 = "\ref69src69"
	data69"id_inserted"69 = !!held_card
	data69"id_card"69 = held_card ? text("69held_card.registered_name69, 69held_card.assignment69") : "-----"
	data69"access_level"69 = get_access_level()
	data69"machine_id"69 =69achine_id
	data69"creating_new_account"69 = creating_new_account
	data69"detailed_account_view"69 = !!detailed_account_view
	data69"station_account_number"69 = station_account.account_number
	data69"transactions"69 = null
	data69"accounts"69 = null

	if (detailed_account_view)
		data69"account_number"69 = detailed_account_view.account_number
		data69"owner_name"69 = detailed_account_view.owner_name
		data69"money"69 = detailed_account_view.money
		data69"suspended"69 = detailed_account_view.suspended

		var/list/trx69069
		for (var/datum/transaction/T in detailed_account_view.transaction_log)
			trx.Add(list(list(\
				"date" = T.date, \
				"time" = T.time, \
				"target_name" = T.target_name, \
				"purpose" = T.purpose, \
				"amount" = T.amount, \
				"source_terminal" = T.source_terminal)))

		if (trx.len > 0)
			data69"transactions"69 = trx

	var/list/accounts69069
	for(var/i=1, i<=all_money_accounts.len, i++)
		var/datum/money_account/D = all_money_accounts69i69
		accounts.Add(list(list(\
			"account_number"=D.account_number,\
			"owner_name"=D.owner_name,\
			"suspended"=D.suspended ? "SUSPENDED" : "",\
			"account_index"=i)))

	if (accounts.len > 0)
		data69"accounts"69 = accounts

	ui = SSnano.try_update_ui(user, src, ui_key, ui, data, force_open)
	if (!ui)
		ui = new(user, src, ui_key, "accounts_terminal.tmpl", src.name, 400, 640)
		ui.set_initial_data(data)
		ui.open()

/obj/machinery/account_database/Topic(href, href_list)
	if(..())
		return 1

	var/datum/nanoui/ui = SSnano.get_open_ui(usr, src, "main")

	if(href_list69"choice"69)
		switch(href_list69"choice"69)
			if("create_account")
				creating_new_account = 1

			if("add_funds")
				var/amount = input("Enter the amount you wish to add", "Silently add funds") as num
				if(detailed_account_view)
					detailed_account_view.money =69in(detailed_account_view.money + amount, fund_cap)

			if("remove_funds")
				var/amount = input("Enter the amount you wish to remove", "Silently remove funds") as num
				if(detailed_account_view)
					detailed_account_view.money =69ax(detailed_account_view.money - amount, -fund_cap)

			if("toggle_suspension")
				if(detailed_account_view)
					detailed_account_view.suspended = !detailed_account_view.suspended
					callHook("change_account_status", list(detailed_account_view))

			if("finalise_create_account")
				var/account_name = href_list69"holder_name"69
				var/starting_funds =69ax(text2num(href_list69"starting_funds"69), 0)

				starting_funds = CLAMP(starting_funds, 0, station_account.money)	// Not authorized to put the station in debt.
				starting_funds =69in(starting_funds, fund_cap)						// Not authorized to give69ore than the fund cap.

				create_account(account_name, starting_funds, src)
				if(starting_funds > 0)
					//subtract the69oney
					station_account.money -= starting_funds

					//create a transaction log entry
					var/trx = create_transation(account_name, "New account activation", "(69starting_funds69)")
					station_account.transaction_log.Add(trx)

					creating_new_account = 0
					ui.close()

				creating_new_account = 0
			if("insert_card")
				if(held_card)
					held_card.loc = src.loc

					if(ishuman(usr) && !usr.get_active_hand())
						usr.put_in_hands(held_card)
					held_card = null

				else
					var/obj/item/I = usr.get_active_hand()
					if (istype(I, /obj/item/card/id))
						var/obj/item/card/id/C = I
						usr.drop_item()
						C.loc = src
						held_card = C

			if("view_account_detail")
				var/index = text2num(href_list69"account_index"69)
				if(index && index <= all_money_accounts.len)
					detailed_account_view = all_money_accounts69index69

			if("view_accounts_list")
				detailed_account_view = null
				creating_new_account = 0

			if("revoke_payroll")
				var/funds = detailed_account_view.money
				var/account_trx = create_transation(station_account.owner_name, "Revoke payroll", "(69funds69)")
				var/station_trx = create_transation(detailed_account_view.owner_name, "Revoke payroll", funds)

				station_account.money += funds
				detailed_account_view.money = 0

				detailed_account_view.transaction_log.Add(account_trx)
				station_account.transaction_log.Add(station_trx)

				callHook("revoke_payroll", list(detailed_account_view))

			if("print")
				var/text
				var/obj/item/paper/P = new(loc)
				if (detailed_account_view)
					P.name = "account #69detailed_account_view.account_number69 details"
					var/title = "Account #69detailed_account_view.account_number69 Details"
					text = {"
						69accounting_letterhead(title)69
						<u>Holder:</u> 69detailed_account_view.owner_name69<br>
						<u>Balance:</u> 69detailed_account_view.money6969CREDS69<br>
						<u>Status:</u> 69detailed_account_view.suspended ? "Suspended" : "Active"69<br>
						<u>Transactions:</u> (69detailed_account_view.transaction_log.len69)<br>
						<table>
							<thead>
								<tr>
									<td>Timestamp</td>
									<td>Target</td>
									<td>Reason</td>
									<td>Value</td>
									<td>Terminal</td>
								</tr>
							</thead>
							<tbody>
						"}

					for (var/datum/transaction/T in detailed_account_view.transaction_log)
						text += {"
									<tr>
										<td>69T.date69 69T.time69</td>
										<td>69T.target_name69</td>
										<td>69T.purpose69</td>
										<td>69T.amount69</td>
										<td>69T.source_terminal69</td>
									</tr>
							"}

					text += {"
							</tbody>
						</table>
						"}

				else
					P.name = "financial account list"
					text = {"
						69accounting_letterhead("Financial Account List")69

						<table>
							<thead>
								<tr>
									<td>Account Number</td>
									<td>Holder</td>
									<td>Balance</td>
									<td>Status</td>
								</tr>
							</thead>
							<tbody>
					"}

					for(var/i=1, i<=all_money_accounts.len, i++)
						var/datum/money_account/D = all_money_accounts69i69
						text += {"
								<tr>
									<td>#69D.account_number69</td>
									<td>69D.owner_name69</td>
									<td>69D.money6969CREDS69</td>
									<td>69D.suspended ? "Suspended" : "Active"69</td>
								</tr>
						"}

					text += {"
							</tbody>
						</table>
					"}

				P.info = text
				state("The terminal prints out a report.")

	return 1
