#include "_mech_defines.dm"

	#include "mech.dm"
	#include "mech_construction.dm"
	#include "mech_damage.dm"
	#include "mech_damage_immunity.dm"
	#include "mech_icon.dm"
	#include "mech_interaction.dm"
	#include "mech_life.dm"
	#include "mech_movement.dm"
	#include "mech_misc.dm"
	#include "mech_recharger.dm"
	#include "mech_wreckage.dm"

	#include "components/_components.dm"
		#include "components/armour.dm"
		#include "components/arms.dm"
		#include "components/body.dm"
		#include "components/frame.dm"
		#include "components/head.dm"
		#include "components/legs.dm"
		#include "components/software.dm"

	#include "equipment/_equipment.dm"
		#include "equipment/combat.dm"
		//#include "ai_holding.dm"
		#include "equipment/engineering.dm"
		#include "equipment/medical.dm"
		#include "equipment/utility.dm"

	#include "interface/_mech_HUD.dm"
		#include "interface/screen_objects.dm"
		#include "interface/datum_HUD.dm"

	#include "premade/_premade.dm"
		#include "premade/combat.dm"
		#include "premade/heavy.dm"
		#include "premade/light.dm"
		#include "premade/powerloader.dm"

#include "_mech_undefines.dm"
