/obj/landmark/loot_biomes/obj/techs
	name = "Biome: Guns"
	main_tags = list(SPAWN_TOOL, SPAWN_TOOL_ADVANCED = 0.5,
					SPAWN_DIVICE, SPAWN_ITEM_UTILITY)
	tags_to_spawn = list(SPAWN_ASSEMBLY,SPAWN_STOCK_PARTS,SPAWN_DESING_COMMON,SPAWN_COMPUTER_HARDWERE)
	tags_to_spawn = list(SPAWN_TOOL_UPGRADE,SPAWN_TOOL_UPGRADE_RARE,SPAWN_ELECTRONICS, SPAWN_JETPACK)
	restricted_tags = list(SPAWN_SURGERY_TOOL, SPAWN_KNIFE, SPAWN_JUNK_TOOL)


