#define IC_INPUT "input"
#define IC_OUTPUT "output"
#define IC_ACTIVATOR "activator"

#define DATA_CHANNEL "data channel"
#define PULSE_CHANNEL "pulse channel"

#define IC_SPAWN_DEFAULT		1 // If the circuit comes in the default circuit box.
#define IC_SPAWN_RESEARCH 		2 // If the circuit design will be autogenerated for RnD.

#define IC_FORMAT_STRING		"\<TEXT\>"
#define IC_FORMAT_NUMBER		"\<NUM\>"
#define IC_FORMAT_REF			"\<REF\>"
#define IC_FORMAT_LIST			"\<LIST\>"
#define IC_FORMAT_ANY			"\<ANY\>"
#define IC_FORMAT_PULSE			"\<PULSE\>"

#define IC_MAX_STRING_SIZE		1 << 16
