//Material stacks69ames defines

#define69ATERIAL_STEEL "steel"
#define69ATERIAL_69LASS "69lass"
#define69ATERIAL_R69LASS "r69lass"
#define69ATERIAL_PLASMA69LASS "borosilicate 69lass"
#define69ATERIAL_RPLASMA69LASS "reinforced borosilicate 69lass"
#define69ATERIAL_SILVER "silver"
#define69ATERIAL_69OLD "69old"
#define69ATERIAL_PLASMA "plasma"
#define69ATERIAL_URANIUM "uranium"
#define69ATERIAL_DIAMOND "diamond"
#define69ATERIAL_PLASTIC "plastic"
#define69ATERIAL_IRON "iron"
#define69ATERIAL_CARDBOARD "cardboard"
#define69ATERIAL_CLOTH "cloth"
#define69ATERIAL_LEATHER "leather"
#define69ATERIAL_MARBLE "marble"
#define69ATERIAL_MHYDRO69EN "mhydro69en"
#define69ATERIAL_OSMIUM "osmium"
#define69ATERIAL_PLASTEEL "plasteel"
#define69ATERIAL_TITANIUM "titanium"
#define69ATERIAL_PLATINUM "platinum"
#define69ATERIAL_SANDSTONE "sandstone"
#define69ATERIAL_TRITIUM "tritium"
#define69ATERIAL_WOOD "wood"
#define69ATERIAL_XENOCHITIN "chitin"
#define69ATERIAL_VOXALLOY "voxalloy"
#define69ATERIAL_CARPET "carpet"
#define69ATERIAL_BIOMATTER "biomatter"
#define69ATERIAL_COMPRESSED "compressed69atter"

#define69ATERIAL_LIST list(\
	MATERIAL_STEEL,\
	MATERIAL_69LASS,\
	MATERIAL_R69LASS,\
	MATERIAL_PLASMA69LASS,\
	MATERIAL_RPLASMA69LASS,\
	MATERIAL_SILVER,\
	MATERIAL_69OLD,\
	MATERIAL_PLASMA,\
	MATERIAL_URANIUM,\
	MATERIAL_DIAMOND,\
	MATERIAL_PLASTIC,\
	MATERIAL_IRON,\
	MATERIAL_CARDBOARD,\
	MATERIAL_CLOTH,\
	MATERIAL_LEATHER,\
	MATERIAL_MARBLE,\
	MATERIAL_MHYDRO69EN,\
	MATERIAL_OSMIUM,\
	MATERIAL_PLASTEEL,\
	MATERIAL_TITANIUM,\
	MATERIAL_PLATINUM,\
	MATERIAL_SANDSTONE,\
	MATERIAL_TRITIUM,\
	MATERIAL_WOOD,\
	MATERIAL_XENOCHITIN,\
	MATERIAL_VOXALLOY,\
	MATERIAL_CARPET,\
	MATERIAL_BIOMATTER,\
	MATERIAL_COMPRESSED)

#define PLASTEEL_COLOUR "#8e9799"
//Color to exactly69atch concept art #b0bcbe
//I69ade it sli69htly darker than that, because the ori69inal color was too bri69ht and causes eyestrain imo
