// INTERNAL ORGANS
#define IORGAN_STANDARD_HEALTH 12
#define IORGAN_SMALL_HEALTH 8
#define IORGAN_SKELETAL_HEALTH 14
#define IORGAN_MAX_HEALTH 14

// INTERNAL WOUNDS
#define IWOUND_INSIGNIFICANT_DAMAGE 0.05
#define IWOUND_LIGHT_DAMAGE 0.1
#define IWOUND_MEDIUM_DAMAGE 0.25
#define IWOUND_HEAVY_DAMAGE 0.5

#define IWOUND_1_MINUTE	30
#define IWOUND_2_MINUTES 60
#define IWOUND_3_MINUTES 90
#define IWOUND_4_MINUTES 120
#define IWOUND_5_MINUTES 150
