#define PERK_FAST_WALKER /datum/perk/oddity/fast_walker
#define PERK_GUNSLINGER /datum/perk/oddity/gunslinger
#define PERK_TERRIBLE_FATE /datum/perk/oddity/terrible_fate
#define PERK_UNFINISHED_DELIVERY /datum/perk/oddity/unfinished_delivery
#define PERK_LUNGS_OF_IRON /datum/perk/oddity/lungs_of_iron
#define PERK_BLOOD_OF_LEAD /datum/perk/oddity/blood_of_lead
#define PERK_SPACE_ASSHOLE /datum/perk/oddity/space_asshole
#define PERK_PARKOUR /datum/perk/oddity/parkour
#define PERK_CHARMING_PERSONALITY /datum/perk/oddity/charming_personality
#define PERK_HORRIBLE_DEEDS /datum/perk/oddity/horrible_deeds
#define PERK_CHAINGUN_SMOKER /datum/perk/oddity/chaingun_smoker
#define PERK_NIGHTCRAWLER /datum/perk/oddity/nightcrawler
#define PERK_FAST_FINGERS /datum/perk/oddity/fast_fingers
#define PERK_QUIET_AS_MOUSE /datum/perk/oddity/quiet_as_mouse
#define PERK_EAR_OF_QUICKSILVER /datum/perk/oddity/ear_of_quicksilver
#define PERK_BALLS_OF_PLASTEEL /datum/perk/oddity/balls_of_plasteel
#define PERK_JUNKBORN /datum/perk/oddity/junkborn
#define PERK_ASS_OF_CONCRETE /datum/perk/oddity/ass_of_concrete
#define PERK_TOXIC_REVENGER /datum/perk/oddity/toxic_revenger
#define PERK_ABSOLUTE_GRAB /datum/perk/oddity/absolute_grab
