#define PERK_FAST_WALKER /datum/perk/fast_walker
#define PERK_GUNSLINGER /datum/perk/gunslinger
#define PERK_TERRIBLE_FATE /datum/perk/terrible_fate
#define PERK_UNFINISHED_DELIVERY /datum/perk/unfinished_delivery
#define PERK_LUNGS_OF_IRON /datum/perk/lungs_of_iron
#define PERK_BLOOD_OF_LEAD /datum/perk/blood_of_lead
#define PERK_SPACE_ASSHOLE /datum/perk/space_asshole
#define PERK_PARKOUR /datum/perk/parkour
#define PERK_CHARMING_PERSONALITY /datum/perk/charming_personality
#define PERK_HORRIBLE_DEEDS /datum/perk/horrible_deeds
#define PERK_CHAINGUN_SMOKER /datum/perk/chaingun_smoker
#define PERK_NIGHTCRAWLER /datum/perk/nightcrawler
#define PERK_FAST_FINGERS /datum/perk/fast_fingers
#define PERK_QUIET_AS_MOUSE /datum/perk/quiet_as_mouse
#define PERK_EAR_OF_QUICKSILVER /datum/perk/ear_of_quicksilver
#define PERK_BALLS_OF_PLASTEEL /datum/perk/balls_of_plasteel
#define PERK_JUNKBORN /datum/perk/junkborn
#define PERK_ASS_OF_CONCRETE /datum/perk/ass_of_concrete
#define PERK_TOXIC_REVENGER /datum/perk/toxic_revenger
#define PERK_ABSOLUTE_GRAB /datum/perk/absolute_grab
