#define QUALITY_WRENCHING				"wrenching"
#define QUALITY_PRYING					"prying"
#define QUALITY_WELDING					"welding"
#define QUALITY_SCREWING				"screwing"
#define QUALITY_WIRECUTTING				"wirecutting"
#define QUALITY_SURGERY_CUTTING			"surgery cutting"
#define QUALITY_SURGERY_COMPRESS		"surgery compressing"
#define QUALITY_SURGERY_CAUTERIZING		"surgery cauterizing"
#define QUALITY_SURGERY_RETRACTING		"surgery retracting"
#define QUALITY_SURGERY_DRILING			"surgery driling"
#define QUALITY_SURGERY_SAWING			"surgery sawing"
#define QUALITY_SURGERY_BONE_SETTING	"surgery bone setting"
#define QUALITY_SURGERY_VEIN_FIXING		"surgery vein fixing"
#define QUALITY_SURGERY_BONE_FIXING		"surgery bone fixing"
#define QUALITY_SHOVELING				"shoveling"
#define QUALITY_DIGGING					"digging"
#define QUALITY_HOENG					"hoeng"
#define QUALITY_WOOD_CUTTING			"wood cutting"
#define QUALITY_SIMPLE_CUTTING			"simple cutting"
#define QUALITY_FLATTENING				"flattening"
