#define VAULT_BALANCE "balance"
#define VAULT_ITEMS "items"
#define VAULT_ITEMS_DUBS "items_dubs"
#define VAULT_PATRON "patron"
#define VAULT_PATRON_0 "None"
#define VAULT_PATRON_1 "Vagabond"
#define VAULT_PATRON_2 "Guild Member"
#define VAULT_PATRON_3 "Neotheology Patron"

#define VAULT_TRANSACTION_TYPE_PURCHASE "vault_buy"
#define VAULT_TRANSACTION_TYPE_SELL "vault_sell"
#define VAULT_TRANSACTION_TYPE_ROUND_END "vault_round_end"

#define VAULT_REWARD_COST "cost"
#define VAULT_REWARD_IMAGE "icon"
#define VAULT_REWARD_NAME "name"
#define VAULT_REWARD_DESC "desc"
#define VAULT_REWARD_TYPE "item_type"
