#define69ER69E_SPAWN_TA69S(first, second) first + ";" + second

#define CHEAP_ITEM_PRICE 400

//69uns defines
#define 69UN_CHEAP_PRICE 1700
#define 69UN_PRICE_DIVISOR 100
//end 69uns

//cells
#define CELL_LAR69E_BASE_CHAR69E 1000
#define CELL_MEDIUM_BASE_CHAR69E 600
#define CELL_SMALL_BASE_CHAR69E 100

#define  BASE_AUTORECHAR69E_RATE 0.03
#define  BASE_RECHAR69E_TIME 4

//clothin69
#define CLOTH_PRICE_DIVISOR 40

//biomes defines
#define LOOT_LEVEL_VERY_LOW 4000

#define LOOT_LEVEL_LOW 8000

#define LOOT_LEVEL_ADVERA69E 12000

#define LOOT_LEVEL_HI69 16000

#define LOOT_LEVEL_VERY_HI69 20000

//	Items
#define SPAWN_OBJ "obj"
#define SPAWN_ITEM "item"
#define SPAWN_WEAPON "weapon"
#define SPAWN_DICE "dice"

#define SPAWN_TA69_ITEM		MER69E_SPAWN_TA69S(SPAWN_OBJ, SPAWN_ITEM)
#define SPAWN_TA69_WEAPON	MER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_WEAPON)

#define SPAWN_TA69_DICE				MER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_DICE)
#define SPAWN_TA69_ITEM_BOTANICAL	MER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, "botanical")
#define SPAWN_TA69_ITEM_CLOWN		MER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_CLOWN)


#define SPAWN_RARE_ITEM "rare_item"

#define SPAWN_TA69_RARE_ITEM			MER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_RARE_ITEM)

//Items - tools
#define SPAWN_TOOL "tool"
#define SPAWN_JUNKTOOL "junk_tool"
#define SPAWN_TOOL_ADVANCED "tool_advanced"
#define SPAWN_OS_TOOL "os_tool"

#define SPAWN_TA69_TOOL				MER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_TOOL)
#define SPAWN_TA69_TOOL_ADVANCED		MER69E_SPAWN_TA69S(SPAWN_TA69_TOOL, SPAWN_TOOL_ADVANCED)
#define SPAWN_TA69_OS_TOOL			MER69E_SPAWN_TA69S(MER69E_SPAWN_TA69S(SPAWN_TA69_TOOL_ADVANCED, SPAWN_OS_TOOL), SPAWN_ONESTAR)
#define SPAWN_TA69_JUNKTOOL			MER69E_SPAWN_TA69S(MER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_JUNKTOOL), SPAWN_JUNK)

//	Items - tools - knife
#define SPAWN_KNIFE "knife"
#define SPAWN_SWORD "sword"

#define SPAWN_TA69_KNIFE69ER69E_SPAWN_TA69S(MER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_WEAPON), SPAWN_KNIFE)
#define SPAWN_TA69_SWORD69ER69E_SPAWN_TA69S(SPAWN_TA69_KNIFE, SPAWN_SWORD)
#define SPAWN_TA69_KNIFE_CONTRABAND69ER69E_SPAWN_TA69S(SPAWN_TA69_KNIFE, SPAWN_CONTRABAND)

// ITEMS - tools - SUR69ERY
#define SPAWN_SUR69ERY_TOOL "sur69ery_tool"

#define SPAWN_TA69_SUR69ERY_TOOL69ER69E_SPAWN_TA69S(MER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_SUR69ERY_TOOL), SPAWN_MEDICAL)

//	Items - up69rades
#define SPAWN_TOOL_UP69RADE "tool_up69rade"
#define SPAWN_TOOL_UP69RADE_RARE "tool_up69rade_rare"
#define SPAWN_69UN_UP69RADE "69un_up69rade"
#define SPAWN_TOOL_69UN_UP69RADE "tool_69un_up69rade"

#define SPAWN_TA69_TOOL_69UN_UP69RADE SPAWN_TA69_ITEM+";"+SPAWN_TOOL_69UN_UP69RADE
#define SPAWN_TA69_TOOL_UP69RADE69ER69E_SPAWN_TA69S(SPAWN_TA69_TOOL_69UN_UP69RADE, SPAWN_TOOL_UP69RADE)
#define SPAWN_TA69_TOOL_UP69RADE_RARE69ER69E_SPAWN_TA69S(SPAWN_TA69_TOOL_UP69RADE, SPAWN_TOOL_UP69RADE_RARE)
#define SPAWN_TA69_TOOL_UP69RADE_RARE_OS69ER69E_SPAWN_TA69S(SPAWN_TA69_TOOL_UP69RADE_RARE, SPAWN_TA69_TECH_OS)
#define SPAWN_TA69_69UN_UP69RADE69ER69E_SPAWN_TA69S(MER69E_SPAWN_TA69S(SPAWN_TA69_TOOL_69UN_UP69RADE, SPAWN_69UN_UP69RADE), SPAWN_69UNS)

//items - one star
#define SPAWN_ITEM_TECH_OS "item_tech_os"

#define SPAWN_TA69_TECH_OS69ER69E_SPAWN_TA69S(SPAWN_ITEM_TECH_OS, SPAWN_ONESTAR)
#define SPAWN_TA69_ITEM_TECH_OS69ER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_TA69_TECH_OS)

// or69an- PROSTHESIS
#define SPAWN_OR69AN "or69an"
#define SPAWN_OR69AN_OR69ANIC "or69an_or69anic"
#define SPAWN_PROSTHETIC "or69an_prosthetic"
#define SPAWN_PROSTHETIC_OS "or69an_prosthetic_os"

#define SPAWN_TA69_OR69ANS69ER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_OR69AN)
#define SPAWN_TA69_OR69AN69ER69E_SPAWN_TA69S(SPAWN_TA69_OR69ANS, SPAWN_OR69AN_OR69ANIC)
#define SPAWN_TA69_OR69AN_INTERNAL69ER69E_SPAWN_TA69S(SPAWN_TA69_OR69AN, "or69an_internal")
#define SPAWN_TA69_OR69AN_EXTERNAL69ER69E_SPAWN_TA69S(SPAWN_TA69_OR69AN, "or69an_external")
#define SPAWN_TA69_PROSTHETIC69ER69E_SPAWN_TA69S(MER69E_SPAWN_TA69S(SPAWN_TA69_OR69ANS, SPAWN_PROSTHETIC), "or69an_external")
#define SPAWN_TA69_PROSTHETIC_OS69ER69E_SPAWN_TA69S(MER69E_SPAWN_TA69S(SPAWN_TA69_PROSTHETIC, SPAWN_PROSTHETIC_OS), SPAWN_TA69_TECH_OS)

//	Items - Oddities
#define SPAWN_ODDITY "oddity"

#define SPAWN_TA69_ODDITY69ER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_ODDITY)

//	Items - Tanks
#define SPAWN_TANK_69AS "tank_69as"

#define SPAWN_TA69_TANK_69AS69ER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_TANK_69AS)

//items - jetpack
#define SPAWN_JETPACK "jetpack"

#define SPAWN_TA69_JETPACK69ER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_JETPACK)

//  Items - electronics
#define SPAWN_ELECTRONICS "electronics"

#define SPAWN_TA69_ELECTRONICS69ER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_ELECTRONICS)
#define SPAWN_TA69_ELECTRONICS_TA69_JUNK69ER69E_SPAWN_TA69S(SPAWN_TA69_ELECTRONICS, SPAWN_JUNK)

//  Items - assembly
#define SPAWN_ASSEMBLY "assembly"

#define SPAWN_TA69_ASSEMBLY69ER69E_SPAWN_TA69S(SPAWN_TA69_ITEM, SPAWN_ASSEMBLY)

// items - ore
#define SPAWN_MATERIAL "material"
#define SPAWN_ORE "ore"
#define SPAWN_MATERIAL_RESOURCES "material_resources"
#define SPAWN_MATERIAL_RESOURCES_RARE "material_resources_rare"
#define SPAWN_MATERIAL_BUILDIN69 "buldin69_material"
#define SPAWN_MATERIAL_BUILDIN69_ROD "rod"
#define SPAWN_MATERIAL_JUNK "material_junk"

#define SPAWN_TA69_MATERIAL SPAWN_TA69_ITEM+";"+SPAWN_MATERIAL
#define SPAWN_TA69_ORE SPAWN_TA69_MATERIAL+";"+SPAWN_ORE
#define SPAWN_TA69_ORE_TA69_JUNK SPAWN_TA69_ORE+";"+SPAWN_MATERIAL_JUNK+";"+SPAWN_JUNK
#define SPAWN_TA69_MATERIAL_RESOURCES SPAWN_TA69_MATERIAL+";"+SPAWN_MATERIAL_RESOURCES
#define SPAWN_TA69_MATERIAL_RESOURCES_RARE SPAWN_TA69_MATERIAL_RESOURCES+";"+SPAWN_MATERIAL_RESOURCES_RARE
#define SPAWN_TA69_MATERIAL_BUILDIN69 SPAWN_TA69_MATERIAL+";"+SPAWN_MATERIAL_BUILDIN69
#define SPAWN_TA69_MATERIAL_RESOURCES_BULDIN69 SPAWN_TA69_MATERIAL_RESOURCES+";"+SPAWN_MATERIAL_BUILDIN69
#define SPAWN_TA69_MATERIAL_BUILDIN69_JUNK SPAWN_TA69_MATERIAL_BUILDIN69+";"+SPAWN_MATERIAL_JUNK+";"+SPAWN_JUNK

// FOSSIL
#define SPAWN_XENOARCH "xenoarcheolo69y"
#define SPAWN_FOSSIL "fossil"

#define SPAWN_TA69_XENOARCH_ITEM SPAWN_TA69_ITEM+";"+SPAWN_XENOARCH
#define SPAWN_TA69_XENOARCH_ITEM_FOSSIL SPAWN_TA69_ITEM+";"+SPAWN_FOSSIL+";"+SPAWN_XENOARCH
#define SPAWN_TA69_69UN_ENER69Y_XENOARCH SPAWN_TA69_69UN_ENER69Y+";"+SPAWN_XENOARCH

// 69INES
#define SPAWN_MINE "mine"
#define SPAWN_MINE_ITEM "mine_item"
#define SPAWN_STUCTURE_MINE "mine_structure"

#define SPAWN_TA69_MINE_ITEM SPAWN_TA69_ITEM+";"+SPAWN_MINE+";"+SPAWN_MINE_ITEM
#define SPAWN_TA69_MINE_STUCTURE SPAWN_TA69_STRUCTURE+";"+SPAWN_MINE+";"+SPAWN_STUCTURE_MINE

//traps
#define SPAWN_TRAP_ARMED "trap_armed"
#define SPAWN_TRAP_WIRE "trap_wire"

#define SPAWN_TA69_TRAP_ARMED SPAWN_OBJ+";"+SPAWN_TRAP_ARMED
#define SPAWN_TA69_TRAP_ARMED_WIRE SPAWN_TA69_TRAP_ARMED+";"+SPAWN_TRAP_WIRE

//	Items - powercells
#define SPAWN_POWERCELL "powercell"
#define SPAWN_POWERCELL_SMALL "powercell_small"
#define SPAWN_POWERCELL_MEDIUM "powercell_medium"
#define SPAWN_POWERCELL_LAR69E "powercell_lar69e"

#define SPAWN_TA69_POWERCELL SPAWN_TA69_ITEM+";"+SPAWN_POWERCELL
#define SPAWN_TA69_POWERCELL_SMALL SPAWN_TA69_POWERCELL+";"+SPAWN_POWERCELL_SMALL
#define SPAWN_TA69_POWERCELL_MEDIUM SPAWN_TA69_POWERCELL+";"+SPAWN_POWERCELL_MEDIUM
#define SPAWN_TA69_POWERCELL_MEDIUM_IH_AMMO SPAWN_TA69_POWERCELL_MEDIUM+";ammo_ih;ammo_common"
#define SPAWN_TA69_POWERCELL_LAR69E SPAWN_TA69_POWERCELL+";"+SPAWN_POWERCELL_LAR69E

//PARTS
#define SPAWN_PART "part"
#define SPAWN_PART_69UN "part_69un"
#define SPAWN_PART_ARMOR "69un_armor"

#define SPAWN_TA69_PART SPAWN_TA69_ITEM+";"+SPAWN_PART
#define SPAWN_TA69_69UN_PART SPAWN_TA69_PART+";"+SPAWN_69UNS+";"+SPAWN_PART_69UN
#define SPAWN_TA69_PART_ARMOR SPAWN_TA69_PART+";"+SPAWN_PART_ARMOR+";"+SPAWN_CLOTHIN69

//	Items - 69UNS
#define SPAWN_69UNS "69uns"
#define SPAWN_69UN "69un"
#define SPAWN_69UN_ENER69Y "69un_ener69y"
#define SPAWN_69UN_PROJECTILE "69un_projectile"
#define SPAWN_69UN_SHOT69UN "shot69un"
#define SPAWN_69UN_OS "69un_os"
#define SPAWN_69UN_HANDMADE "69un_handmade"

#define SPAWN_TA69_69UNS SPAWN_TA69_ITEM+";"+SPAWN_69UNS
#define SPAWN_TA69_69UN SPAWN_TA69_69UNS+";"+SPAWN_69UN
#define SPAWN_TA69_69UN_ENER69Y SPAWN_TA69_69UN+";"+SPAWN_69UN_ENER69Y
#define SPAWN_TA69_69UN_ENER69Y_CHAMALEON SPAWN_TA69_69UN_ENER69Y+";"+SPAWN_TA69_CHAMALEON
#define SPAWN_TA69_69UN_PROJECTILE SPAWN_TA69_69UN+";"+SPAWN_69UN_PROJECTILE
#define SPAWN_TA69_69UN_SHOT69UN69ER69E_SPAWN_TA69S(SPAWN_TA69_69UN_PROJECTILE, SPAWN_69UN_SHOT69UN)
#define SPAWN_TA69_69UN_SHOT69UN_ENER69Y69ER69E_SPAWN_TA69S(SPAWN_TA69_69UN_ENER69Y, SPAWN_69UN_SHOT69UN)
#define SPAWN_TA69_69UN_ENER69Y_BOTANICAL SPAWN_TA69_69UN_ENER69Y+";botanical"
#define SPAWN_TA69_69UN_OS SPAWN_TA69_69UN+";"+SPAWN_69UN_OS
#define SPAWN_TA69_69UN_HANDMADE SPAWN_69UN_HANDMADE

//	Items - 69UNS - ammo
#define SPAWN_AMMO "ammo"
#define SPAWN_AMMO_S "ammmo_stora69e"
#define SPAWN_AMMO_IH "ammo_ih"
#define SPAWN_AMMO_SHOT69UN "ammmo_stora69e_shot69un"
#define SPAWN_AMMO_COMMON "ammo_common"

#define SPAWN_TA69_AMMO SPAWN_TA69_ITEM+";"+SPAWN_69UNS+";"+SPAWN_AMMO+";"+SPAWN_AMMO_S
#define SPAWN_TA69_AMMO_COMMON SPAWN_TA69_AMMO+";"+SPAWN_AMMO_COMMON
#define SPAWN_TA69_AMMO_SHOT69UN SPAWN_TA69_AMMO+";"+SPAWN_AMMO_SHOT69UN
#define SPAWN_TA69_AMMO_SHOT69UN_COMMON SPAWN_TA69_AMMO_SHOT69UN+";"+SPAWN_AMMO_COMMON
#define SPAWN_TA69_AMMO_IH SPAWN_TA69_AMMO+";"+SPAWN_AMMO_IH

//	Items - contraband
#define SPAWN_CONTRABAND "contraband"
#define SPAWN_CHAMALEON "chamaleon"
//#define SPAWN_DRU69 "dru69"//crused
//#define SPAWN_PILL "pill"//crused

#define SPAWN_TA69_CHAMALEON SPAWN_CONTRABAND+";"+SPAWN_CHAMALEON
#define SPAWN_ITEM_CONTRABAND SPAWN_TA69_ITEM+";"+SPAWN_CONTRABAND
//#define SPAWN_TA69_DRU69_CONTRABAND SPAWN_ITEM_CONTRABAND//+";"+SPAWN_DRU69
//#define SPAWN_TA69_DRU69_PILL_CONTRABAND SPAWN_ITEM_CONTRABAND//+";"+SPAWN_DRU69+";"+SPAWN_PILL

//	Items - TOYS
#define SPAWN_TOY "toy"
#define SPAWN_PLUSHIE "toy_plushie"
#define SPAWN_FI69URE "toy_fi69ure"
#define SPAWN_TOY_WEAPON "toy_weapon"

#define SPAWN_TA69_ITEM_TOY SPAWN_TA69_ITEM+";"+SPAWN_TOY
#define SPAWN_TA69_TOY_WEAPON SPAWN_TA69_ITEM_TOY+";"+SPAWN_TOY_WEAPON
#define SPAWN_TA69_PLUSHIE SPAWN_TA69_ITEM_TOY+";"+SPAWN_PLUSHIE
#define SPAWN_TA69_STRUCTURE_PLUSHIE SPAWN_TA69_STRUCTURE+";"+SPAWN_PLUSHIE
#define SPAWN_TA69_FI69URE SPAWN_TA69_ITEM_TOY+";"+SPAWN_FI69URE

//items - utility
#define SPAWN_ITEM_UTILITY "item_utility"

#define SPAWN_TA69_ITEM_UTILITY SPAWN_TA69_ITEM+";"+SPAWN_ITEM_UTILITY

//	Items - CLOTHIN69
#define SPAWN_CLOTHIN69 "clothin69"
#define SPAWN_MASK "mask"
#define SPAWN_VOID_SUIT "void_suit"
#define SPAWN_HAZMATSUIT "hazmatsuit"
#define SPAWN_HOLSTER "holster"
#define SPAWN_SHOES "shoes"
#define SPAWN_69LOVES "69loves"
#define SPAWN_CLOTHIN69_UNDER "under"
#define SPAWN_CLOTHIN69_HEAD "head"
#define SPAWN_CLOTHIN69_HEAD_HELMET "helmet"
#define SPAWN_CLOTHIN69_ARMOR "armor"
#define SPAWN_69LASSES "69lasses"
#define SPAWN_CLOTHIN69_SUIT_STORA69E "suit_stora69e"
#define SPAWN_CLOTHIN69_SUIT_PONCHO "suit_poncho"

#define SPAWN_TA69_CLOTHIN69 SPAWN_TA69_ITEM+";"+SPAWN_CLOTHIN69
#define SPAWN_TA69_VOID_SUIT SPAWN_TA69_CLOTHIN69+";suit;space_suit;"+SPAWN_VOID_SUIT
#define SPAWN_TA69_MASK SPAWN_TA69_CLOTHIN69+";"+SPAWN_MASK
#define SPAWN_TA69_MASK_CONTRABAND SPAWN_TA69_MASK+";"+SPAWN_TA69_CHAMALEON
#define SPAWN_TA69_HAZMATSUIT SPAWN_TA69_CLOTHIN69+";"+SPAWN_HAZMATSUIT//suit but69O SUIT
#define SPAWN_TA69_HOLSTER SPAWN_TA69_CLOTHIN69+";"+SPAWN_HOLSTER
#define SPAWN_TA69_SHOES SPAWN_TA69_CLOTHIN69+";"+SPAWN_SHOES
#define SPAWN_TA69_SHOES_CHAMALEON SPAWN_TA69_SHOES+";"+SPAWN_TA69_CHAMALEON
#define SPAWN_TA69_69LOVES SPAWN_TA69_CLOTHIN69+";"+SPAWN_69LOVES
#define SPAWN_TA69_69LOVES_INSULATED SPAWN_TA69_69LOVES+";"+SPAWN_ITEM_UTILITY
#define SPAWN_TA69_69LOVES_CHAMALEON SPAWN_TA69_69LOVES+";"+SPAWN_TA69_CHAMALEON
#define SPAWN_TA69_CLOTHIN69_UNDER SPAWN_TA69_CLOTHIN69+";"+SPAWN_CLOTHIN69_UNDER
#define SPAWN_TA69_CLOTHIN69_UNDER_CHAMALEON SPAWN_TA69_CLOTHIN69_UNDER+";"+SPAWN_TA69_CHAMALEON
#define SPAWN_TA69_CLOTHIN69_HEAD SPAWN_TA69_CLOTHIN69+";"+SPAWN_CLOTHIN69_HEAD
#define SPAWN_TA69_CLOTHIN69_HEAD_CHAMALEON SPAWN_TA69_CLOTHIN69_HEAD+";"+SPAWN_TA69_CHAMALEON
#define SPAWN_TA69_CLOTHIN69_HEAD_HELMET SPAWN_TA69_CLOTHIN69_HEAD+";"+SPAWN_CLOTHIN69_HEAD_HELMET
#define SPAWN_TA69_CLOTHIN69_ARMOR SPAWN_TA69_CLOTHIN69+";"+SPAWN_CLOTHIN69_ARMOR
#define SPAWN_TA69_69LASSES SPAWN_TA69_CLOTHIN69+";"+SPAWN_69LASSES
#define SPAWN_TA69_69LASSES_CHAMALEON SPAWN_TA69_69LASSES+";"+SPAWN_TA69_CHAMALEON
#define SPAWN_TA69_CLOTHIN69_SUIT_STORA69E SPAWN_TA69_CLOTHIN69+";suit"+";"+SPAWN_CLOTHIN69_SUIT_STORA69E
#define SPAWN_TA69_CLOTHIN69_SUIT_PONCHO SPAWN_TA69_CLOTHIN69+";suit"+";"+SPAWN_CLOTHIN69_SUIT_PONCHO

//	Items - stora69e
#define SPAWN_STORA69E "stora69e"
#define SPAWN_TOOLBOX "toolbox"
#define SPAWN_POUCH "pouch"
#define SPAWN_BELT "belt"
#define SPAWN_BOX "box"
#define SPAWN_FIRSTAID "firstaid"
#define SPAWN_BACKPACK "backpack"

#define SPAWN_TA69_STORA69E SPAWN_TA69_ITEM+";"+SPAWN_STORA69E
#define SPAWN_TA69_STORA69E_CLOTHIN69 SPAWN_TA69_STORA69E+";"+SPAWN_CLOTHIN69
#define SPAWN_TA69_TOOLBOX SPAWN_TA69_STORA69E+";"+SPAWN_TOOLBOX
#define SPAWN_TA69_POUCH SPAWN_TA69_STORA69E_CLOTHIN69+";"+SPAWN_POUCH
#define SPAWN_TA69_BELT SPAWN_TA69_STORA69E_CLOTHIN69+";"+SPAWN_BELT
#define SPAWN_TA69_BELT_UTILITY SPAWN_TA69_BELT+";"+SPAWN_ITEM_UTILITY
#define SPAWN_TA69_BOX SPAWN_TA69_STORA69E+";"+SPAWN_BOX
#define SPAWN_TA69_FIRSTAID SPAWN_TA69_STORA69E+";"+SPAWN_FIRSTAID
#define SPAWN_TA69_BACKPACK SPAWN_TA69_STORA69E_CLOTHIN69+";"+SPAWN_BACKPACK
#define SPAWN_TA69_BACKPACK_CHAMALEON SPAWN_TA69_BACKPACK+";"+SPAWN_TA69_CHAMALEON
#define SPAWN_TA69_BOX_TA69_JUNK SPAWN_TA69_BOX+";"+SPAWN_JUNK

// ITEM - STOCK PARTS   and os_tech
#define SPAWN_STOCK_PARTS "stock_parts"

#define SPAWN_TA69_STOCK_PARTS SPAWN_TA69_ITEM+";"+SPAWN_STOCK_PARTS
#define SPAWN_TA69_STOCK_PARTS_TIER_2 SPAWN_TA69_STOCK_PARTS+";"+SPAWN_SCIENCE
#define SPAWN_TA69_STOCK_PARTS_OS SPAWN_TA69_STOCK_PARTS+";"+SPAWN_TA69_TECH_OS+";stock_parts_os"

// ITEM - divice
#define SPAWN_DIVICE "divice"

#define SPAWN_TA69_DIVICE SPAWN_TA69_ITEM+";"+SPAWN_DIVICE
#define SPAWN_TA69_DIVICE_SCIENCE SPAWN_TA69_DIVICE+";"+SPAWN_SCIENCE

//factions
#define SPAWN_SCIENCE "science"
#define SPAWN_MEDICAL "medical"

#define SPAWN_TA69_MEDICAL SPAWN_TA69_ITEM+";"+SPAWN_MEDICAL

// ITEMS -69EDICINE
#define SPAWN_MEDICINE "medicine"
#define SPAWN_MEDICINE_COMMON "medicine_common"
#define SPAWN_MEDICINE_ADVANCED "medicine_advanced"

#define SPAWN_TA69_MEDICINE SPAWN_TA69_MEDICAL+";"+SPAWN_MEDICINE
#define SPAWN_TA69_MEDICINE_COMMON SPAWN_TA69_MEDICINE+";"+SPAWN_MEDICINE_COMMON
#define SPAWN_TA69_MEDICINE_CONTRABAND SPAWN_TA69_MEDICINE+";"+SPAWN_CONTRABAND
#define SPAWN_TA69_MEDICINE_ADVANCED SPAWN_TA69_MEDICINE+";"+SPAWN_MEDICINE_ADVANCED

//ITEMS - BEAKER
#define SPAWN_TA69_VIAL SPAWN_TA69_ITEM+";"+SPAWN_SCIENCE+";"+SPAWN_MEDICAL+";beaker;vial"


// ITEMS - COMPUTER
#define SPAWN_DESI69N "desi69n"
#define SPAWN_DESI69N_COMMON "desi69n_common"
#define SPAWN_DESI69N_ADVANCED "desi69n_advanced"
#define SPAWN_DESI69N_OS "desi69n_os"
#define SPAWN_COMPUTER_HARDWERE "computer_hardware"

#define SPAWN_TA69_DESI69N SPAWN_TA69_ITEM+";"+SPAWN_DESI69N
#define SPAWN_TA69_DESI69N_COMMON SPAWN_TA69_DESI69N+";"+SPAWN_DESI69N_COMMON
#define SPAWN_TA69_DESI69N_ADVANCED SPAWN_TA69_DESI69N+";"+SPAWN_DESI69N_ADVANCED
#define SPAWN_TA69_DESI69N_ADVANCED_COMMON SPAWN_TA69_DESI69N_ADVANCED+";"+SPAWN_DESI69N_COMMON
#define SPAWN_TA69_DESI69N_OS SPAWN_TA69_DESI69N+";"+SPAWN_TA69_TECH_OS+";"+SPAWN_DESI69N_OS
#define SPAWN_TA69_RESEARCH_POINTS SPAWN_TA69_ITEM+";"+SPAWN_SCIENCE
#define SPAWN_TA69_COMPUTER_HARDWERE SPAWN_TA69_ITEM+";"+SPAWN_COMPUTER_HARDWERE

// ITEMS - RI69
#define SPAWN_RI69 "ri69_suit"
#define SPAWN_RI69_MODULE "ri69_module"
#define SPAWN_RI69_MODULE_COMMON "ri69_module_common"

#define SPAWN_TA69_RI69 SPAWN_TA69_ITEM+";space_suit;"+SPAWN_RI69
#define SPAWN_TA69_RI69_HAZMAT SPAWN_TA69_RI69+";"+SPAWN_SCIENCE
#define SPAWN_TA69_RI69_MODULE SPAWN_TA69_ITEM+";"+SPAWN_RI69_MODULE
#define SPAWN_TA69_RI69_MODULE_COMMON SPAWN_TA69_RI69_MODULE+";"+SPAWN_RI69_MODULE_COMMON

// ITEM - DRIKS
#define SPAWN_BOOZE "bottle_alcohol"
#define SPAWN_DRINK_SODA "cans"

#define SPAWN_TA69_BOTTLE_DRIN69 SPAWN_TA69_ITEM+";drink;bottle_drink"
#define SPAWN_TA69_BOOZE SPAWN_TA69_BOTTLE_DRIN69+";"+SPAWN_BOOZE
#define SPAWN_TA69_DRINK_SODA SPAWN_TA69_BOTTLE_DRIN69+";"+SPAWN_DRINK_SODA

// item -snacks
#define SPAWN_SNACK "snacks"
#define SPAWN_JUNKFOOD "junkfood"
#define SPAWN_PIZZA "pizza"
#define SPAWN_RATIONS "rations"
#define SPAWN_COOKED_FOOD "cooked_food"

#define SPAWN_TA69_ITEM_SNACKS SPAWN_TA69_ITEM+";"+SPAWN_SNACK
#define SPAWN_TA69_RATIONS SPAWN_TA69_ITEM_SNACKS+";"+SPAWN_RATIONS
#define SPAWN_TA69_JUNKFOOD SPAWN_TA69_ITEM_SNACKS+";"+SPAWN_JUNKFOOD
#define SPAWN_TA69_JUNKFOOD_RATIONS SPAWN_TA69_JUNKFOOD+";"+SPAWN_RATIONS
#define SPAWN_TA69_PIZZA SPAWN_TA69_ITEM_SNACKS+";"+SPAWN_PIZZA
#define SPAWN_TA69_COOKED_FOOD SPAWN_TA69_ITEM_SNACKS+";"+SPAWN_COOKED_FOOD

// ITEM - 69RENADES
#define SPAWN_69ENADE "69renade"

#define SPAWN_TA69_69RENADE SPAWN_TA69_ITEM+";"+SPAWN_69ENADE

#define SPAWN_TA69_69RENADE_CLEANER SPAWN_TA69_69RENADE+";"+SPAWN_ITEM_UTILITY+";69renade_cleaner"

//	MECH
#define SPAWN_MECH "mech"

#define SPAWN_MECH_PREMADE "mech_premade"
#define SPAWN_MECH_69UIPMENT "mech_e69uipment"

#define SPAWN_TA69_MECH SPAWN_MECH+";"+SPAWN_MECH_PREMADE
#define SPAWN_TA69_MECH_69UIPMENT SPAWN_TA69_ITEM+";"+SPAWN_MECH+";"+SPAWN_MECH_69UIPMENT


//	MACHINERY
#define SPAWN_MACHINERY "machinery"

#define SPAWN_TA69_MACHINERY SPAWN_OBJ+";"+SPAWN_MACHINERY

//	Structures
#define SPAWN_STRUCTURE "structure"
#define SPAWN_STRUCTURE_COMMON "structure_common"

#define SPAWN_TA69_STRUCTURE SPAWN_OBJ+";"+SPAWN_STRUCTURE
#define SPAWN_TA69_STRUCTURE_COMMON SPAWN_TA69_STRUCTURE+";"+SPAWN_STRUCTURE_COMMON

// Structures - ClOSET
#define SPAWN_CLOSET "closet"
#define SPAWN_WARDROBE "wardrobe"
#define SPAWN_CLOSET_TECHNICAL "closet_technical"
#define SPAWN_CLOSET_RANDOM "closet_random"
#define SPAWN_CLOSET_LASERTA69 "closet_laserta69"
#define SPAWN_CLOSET_BOMB "closet_bomb"
#define SPAWN_CLOSET_COFFIN "closet_coffin"
#define SPAWN_CLOSET_SECURE "closet_secure"

#define SPAWN_TA69_CLOSET SPAWN_TA69_STRUCTURE+";"+SPAWN_CLOSET
#define SPAWN_TA69_CLOSET_OS SPAWN_TA69_CLOSET+";"+SPAWN_ONESTAR
#define SPAWN_TA69_CLOSET_SECURE SPAWN_TA69_CLOSET+";"+SPAWN_CLOSET_SECURE
#define SPAWN_TA69_CLOSET_TECHNICAL SPAWN_TA69_CLOSET+";"+SPAWN_CLOSET_TECHNICAL
#define SPAWN_TA69_WARDROBE SPAWN_TA69_CLOSET+";"+SPAWN_WARDROBE
#define SPAWN_TA69_CLOSET_RANDOM SPAWN_TA69_CLOSET+";"+SPAWN_CLOSET_RANDOM
#define SPAWN_TA69_CLOSET_SECURE_RANDOM SPAWN_TA69_CLOSET_SECURE+";"+SPAWN_CLOSET_RANDOM
#define SPAWN_TA69_CLOSET_LASERTA69 SPAWN_TA69_CLOSET+";"+SPAWN_CLOSET_LASERTA69
#define SPAWN_TA69_CLOSET_BOMB SPAWN_TA69_CLOSET+";"+SPAWN_CLOSET_BOMB
#define SPAWN_TA69_CLOSET_COFFIN SPAWN_TA69_CLOSET+";"+SPAWN_CLOSET_COFFIN

// Structures - SALVA69EABLE
#define SPAWN_SALVA69EABLE "structure_salva69eable"
#define SPAWN_SALVA69EABLE_OS "structure_salva69eable_os"
#define SPAWN_SALVA69EABLE_AUTOLATHE "structure_salva69eable_autolathe"

#define SPAWN_TA69_SALVA69EABLE SPAWN_TA69_STRUCTURE+";"+SPAWN_SALVA69EABLE
#define SPAWN_TA69_SALVA69EABLE_OS SPAWN_TA69_SALVA69EABLE+";"+SPAWN_SALVA69EABLE_OS+";"+SPAWN_ONESTAR
#define SPAWN_TA69_SALVA69EABLE_AUTOLATHE SPAWN_TA69_SALVA69EABLE+";"+SPAWN_SALVA69EABLE_AUTOLATHE

// Structures -69ACHINE_FRAME
#define SPAWN_MACHINE_FRAME "structure_machine_frame"

#define SPAWN_TA69_MACHINE_FRAME SPAWN_TA69_STRUCTURE+";"+SPAWN_MACHINE_FRAME

// Structures - rea69ent dispensers
#define SPAWN_REA69ENT_DISPENSER "structure_rea69ent_dispensers"

#define SPAWN_TA69_REA69ENT_DISPENSER SPAWN_TA69_STRUCTURE+";"+SPAWN_REA69ENT_DISPENSER

// Structures - scrap
#define SPAWN_SCRAP "structure_scrap"
#define SPAWN_SCRAP_LAR69E "structure_scrap_lar69e"
#define SPAWN_SCRAP_BEACON "structure_scrap_beacon"

#define SPAWN_TA69_SCRAP SPAWN_TA69_STRUCTURE+";"+SPAWN_SCRAP
#define SPAWN_TA69_LAR69E_SCRAP SPAWN_TA69_SCRAP+";"+SPAWN_SCRAP_LAR69E
#define SPAWN_TA69_BEACON_SCRAP SPAWN_TA69_SCRAP+";"+SPAWN_SCRAP_BEACON


//-encounters
#define SPAWN_ENCOUNER "encounter"
#define SPAWN_ENCOUNTER_CRYOPOD "encounter_cryopod"
#define SPAWN_SATELITE  "structure_satelite"
#define SPAWN_OMINOUS "structure_ominous"
#define SPAWN_STRAN69EBEACON "stran69ebeacon"
#define SPAWN_BOT_OS "bot_os"

#define SPAWN_TA69_ENCOUNTER_STRUCTURE SPAWN_TA69_STRUCTURE+";"+SPAWN_ENCOUNER
#define SPAWN_TA69_ENCOUNTER_CRYOPOD SPAWN_TA69_ENCOUNTER_STRUCTURE+";"+SPAWN_ENCOUNTER_CRYOPOD
#define SPAWN_TA69_SATELITE SPAWN_TA69_ENCOUNTER_STRUCTURE+";"+SPAWN_SATELITE
#define SPAWN_TA69_OMINOUS SPAWN_TA69_ENCOUNTER_STRUCTURE+";"+SPAWN_OMINOUS
#define SPAWN_TA69_STRAN69EBEACON SPAWN_TA69_ENCOUNTER_STRUCTURE+";"+SPAWN_STRAN69EBEACON
#define SPAWN_TA69_BOT_OS SPAWN_MOB+";"+SPAWN_ENCOUNER+";"+SPAWN_ONESTAR+";"+SPAWN_BOT_OS+";bot"

//	Mobs
#define SPAWN_MOB "mob"
#define SPAWN_MOB_HOSTILE "mob_hostile"
#define SPAWN_MOB_FRIENDLY "mob_friendly"
#define SPAWN_SLIME "slime"
#define SPAWN_MOB_OS_CUSTODIAN "os_custodian"
#define SPAWN_MOB_ROOMBA "roomba"
#define SPAWN_MOB_HIVEMIND "hivemind"
#define SPAWN_MOB_69OLEM "69olem"

#define SPAWN_TA69_MOB_HOSTILE SPAWN_MOB+";"+SPAWN_MOB_HOSTILE
#define SPAWN_TA69_MOB_FRIENDLY SPAWN_MOB+";"+SPAWN_MOB_FRIENDLY
#define SPAWN_TA69_SLIME SPAWN_MOB+";"+SPAWN_SLIME
#define SPAWN_TA69_MOB_HIVEMIND SPAWN_TA69_MOB_HOSTILE+";"+SPAWN_MOB_HIVEMIND
#define SPAWN_TA69_MOB_OS_CUSTODIAN SPAWN_TA69_MOB_HOSTILE+";"+SPAWN_MOB_OS_CUSTODIAN+";"+SPAWN_ONESTAR
#define SPAWN_TA69_MOB_ROOMBA SPAWN_TA69_MOB_HOSTILE+";"+SPAWN_MOB_ROOMBA+";"+SPAWN_ONESTAR
#define SPAWN_TA69_MOB_69OLEM SPAWN_TA69_MOB_HOSTILE+";"+SPAWN_MOB_69OLEM

//69OBS - ROACH
#define SPAWN_ROACH "roach"
#define SPAWN_ROACH_NANITE "roach_nanite"

#define SPAWN_TA69_ROACH SPAWN_TA69_MOB_HOSTILE+";"+SPAWN_ROACH
#define SPAWN_TA69_ROACH_NANITE SPAWN_TA69_ROACH+";"+SPAWN_ROACH_NANITE

//MOBS - SLIMES
#define SPAWN_SPIDER "spider"

#define SPAWN_TA69_SPIDER SPAWN_TA69_MOB_HOSTILE+";"+SPAWN_SPIDER

//EFFECTS
#define SPAWN_FLORA "flora"

#define SPAWN_TA69_FLORA "effect;"+SPAWN_FLORA


//JUNK
#define SPAWN_JUNK "junk"
#define SPAWN_CLEANABLE "cleanable"
#define SPAWN_REMAINS "remains"

#define SPAWN_TA69_REMAINS SPAWN_TA69_ITEM+";"+SPAWN_REMAINS
#define SPAWN_TA69_JUNK SPAWN_TA69_ITEM+";"+SPAWN_JUNK
#define SPAWN_TA69_JUNK_CLOWN SPAWN_TA69_JUNK+";"+SPAWN_CLOWN
#define SPAWN_TA69_CLEANABLE "effect;"+SPAWN_CLEANABLE

//  SPAWNERS
#define SPAWN_SPAWNER "spawner"
#define SPAWN_SPAWNER_ENCOUNER "spawner_encounter"
#define SPAWN_SPAWNER_MOB "spawner_mob"
#define SPAWN_SPAWNER_SCRAP "spawner_scrap"
#define SPAWN_SPAWNER_SCRAP_LAR69E "spawner_scrap_lar69e"

#define SPAWN_TA69_SPAWNER_ENCOUNER SPAWN_SPAWNER+";"+SPAWN_SPAWNER_ENCOUNER
#define SPAWN_TA69_SPAWNER_MOB SPAWN_SPAWNER+";"+SPAWN_SPAWNER_MOB
#define SPAWN_TA69_SPAWNER_SCRAP SPAWN_SPAWNER+";"+SPAWN_SPAWNER_SCRAP
#define SPAWN_TA69_SPAWNER_SCRAP_LAR69E SPAWN_SPAWNER_SCRAP+";"+SPAWN_SPAWNER_SCRAP_LAR69E

// FACTION KEYWORDS
#define SPAWN_ASTERS "asters"
#define SPAWN_EXCELSIOR "excelsior"
#define SPAWN_FROZEN_STAR "frozen_star"
#define SPAWN_IRONHAMMER "ironhammer"
#define SPAWN_NANOTRASEN "nanotrasen"
#define SPAWN_NEOTHEOLO69Y "neotheolo69y"
#define SPAWN_MOEBIUS "moebius"
#define SPAWN_SERBIAN "serbian"
#define SPAWN_ONESTAR "onestar"
#define SPAWN_TECHNOMANCER "technomancer"

#define SPAWN_CLOWN "clown"
