#define SPAWN_FS_PROJECTILE SPAWN_FROZEN_STAR + "_projectile"
#define SPAWN_FS_ENERGY SPAWN_FROZEN_STAR + "_energy"
#define SPAWN_FS_SHOTGUN SPAWN_FROZEN_STAR + "_shotgun"

#define SPAWN_TAG_FS_PROJECTILE	MERGE_SPAWN_TAGS(MERGE_SPAWN_TAGS(SPAWN_TAG_GUN_PROJECTILE, SPAWN_FROZEN_STAR), SPAWN_FS_PROJECTILE)
#define SPAWN_TAG_FS_ENERGY		MERGE_SPAWN_TAGS(MERGE_SPAWN_TAGS(SPAWN_TAG_GUN_ENERGY, SPAWN_FROZEN_STAR), SPAWN_FS_ENERGY)
#define SPANW_TAG_FS_SHOTGUN	MERGE_SPAWN_TAGS(MERGE_SPAWN_TAGS(SPAWN_TAG_GUN_SHOTGUN, SPAWN_FROZEN_STAR), SPAWN_FS_SHOTGUN)
