
//Chemical Reactions - Initialises all /datum/chemical_reaction into a list
// It is filtered into multiple lists within a list.
// For example:
// chemical_reaction_list["plasma"] is a list of all reactions relating to plasma
// Note that entries in the list are NOT duplicated. So if a reaction pertains to
// more than one chemical it will still only appear in only one of the sublists.
/proc/initialize_chemical_reactions()
	var/paths = typesof(/datum/chemical_reaction) - /datum/chemical_reaction
	GLOB.chemical_reactions_list = list()

	for(var/path in paths)
		var/datum/chemical_reaction/D = new path()
		for(var/id in D.required_reagents)
			if(!is_reagent_with_id_exist(id))
				error("recipe [D.type] created incorectly,\[required_reagents\] reagent with id \"[id]\" does not exist.")
		for(var/id in D.catalysts)
			if(!is_reagent_with_id_exist(id))
				error("recipe [D.type] created incorectly,\[catalysts\] reagent with id [id] does not exist.")
		for(var/id in D.inhibitors)
			if(!is_reagent_with_id_exist(id))
				error("recipe [D.type] created incorectly,\[inhibitors\] reagent with id [id] does not exist.")
		for(var/id in D.byproducts)
			if(!is_reagent_with_id_exist(id))
				error("recipe [D.type] created incorectly,\[byproducts\] reagent with id [id] does not exist.")
		if(D.required_reagents && D.required_reagents.len)
			if(D.result)
				if(!GLOB.chemical_reactions_list_by_result[D.result])
					GLOB.chemical_reactions_list_by_result[D.result] = list()
				GLOB.chemical_reactions_list_by_result[D.result] += D
			var/reagent_id = D.required_reagents[1]
			if(!GLOB.chemical_reactions_list[reagent_id])
				GLOB.chemical_reactions_list[reagent_id] = list()
			GLOB.chemical_reactions_list[reagent_id] += D

//helper that ensures the reaction rate holds after iterating
//Ex. REACTION_RATE(0.3) means that 30% of the reagents will react each chemistry tick (~2 seconds by default).
#define REACTION_RATE(rate) (1 - (1-rate)**(1/PROCESS_REACTION_ITER))

//helper to define reaction rate in terms of half-life
//Ex.
//HALF_LIFE(0) -> Reaction completes immediately (default chems)
//HALF_LIFE(1) -> Half of the reagents react immediately, the rest over the following ticks.
//HALF_LIFE(2) -> Half of the reagents are consumed after 2 chemistry ticks.
//HALF_LIFE(3) -> Half of the reagents are consumed after 3 chemistry ticks.
#define HALF_LIFE(ticks) (ticks? 1 - (0.5)**(1/(ticks*PROCESS_REACTION_ITER)) : 1)

/datum/chemical_reaction
	var/result = null
	var/list/required_reagents = list()
	var/list/catalysts = list()
	var/list/inhibitors = list()
	var/result_amount = 0
	var/list/byproducts= list()

	//how far the reaction proceeds each time it is processed. Used with either REACTION_RATE or HALF_LIFE macros.
	var/reaction_rate = HALF_LIFE(0)

	//if less than 1, the reaction will be inhibited if the ratio of products/reagents is too high.
	//0.5 = 50% yield -> reaction will only proceed halfway until products are removed.
	var/yield = 1

	// Reaction thermal requirements
	var/maximum_temperature = INFINITY
	var/minimum_temperature = 0
	var/thermal_product // Heat generated by the reaction

	var/maximum_pressure = INFINITY

	var/rotation_required = FALSE

	// if true then chemical can be decomposed to initial reagents
	var/supports_decomposition_by_electrolysis = TRUE

	//If limits on reaction rate would leave less than this amount of any reagent (adjusted by the reaction ratios),
	//the reaction goes to completion. This is to prevent reactions from going on forever with tiny reagent amounts.
	var/min_reaction = 2

	var/mix_message = "The solution begins to bubble."
	var/reaction_sound = 'sound/effects/bubbles.ogg'

	var/list/require_containers = list() // This reaction will only occure in these containers(Or their subtypes).
	var/list/blacklist_containers = list() // This reaction will not occure in these containers(Or their subtypes).

	var/log_is_important = 0 // If this reaction should be considered important for logging. Important recipes message admins when mixed, non-important ones just log to file.

/datum/chemical_reaction/proc/can_happen(datum/reagents/holder)
	//check that all the required reagents are present
	if(!holder.has_all_reagents(required_reagents))
		return FALSE

	//check that all the required catalysts are present in the required amount
	if(!holder.has_all_reagents(catalysts))
		return FALSE

	//check that none of the inhibitors are present in the required amount
	if(holder.has_any_reagent(inhibitors))
		return FALSE

	if(require_containers.len && !is_type_in_list(holder.my_atom, require_containers))
		return FALSE

	if(blacklist_containers.len && is_type_in_list(holder.my_atom, blacklist_containers))
		return FALSE

	var/temperature = holder.chem_temp
	if(temperature < minimum_temperature || temperature > maximum_temperature)
		return FALSE

	if(maximum_pressure)
		var/turf/location = get_turf(holder.my_atom)
		if(location)
			var/datum/gas_mixture/GM = location.return_air()
			if(GM.return_pressure() > maximum_pressure)
				return FALSE
		else
			return FALSE


	return TRUE

/datum/chemical_reaction/proc/calc_reaction_progress(var/datum/reagents/holder, var/reaction_limit)
	var/progress = reaction_limit * reaction_rate //simple exponential progression

	//calculate yield
	if(1-yield > 0.001) //if yield ratio is big enough just assume it goes to completion
		/*
			Determine the max amount of product by applying the yield condition:
			(max_product/result_amount) / reaction_limit == yield/(1-yield)

			We make use of the fact that:
			reaction_limit = (holder.get_reagent_amount(reactant) / required_reagents[reactant]) of the limiting reagent.
		*/
		var/yield_ratio = yield/(1-yield)
		var/max_product = yield_ratio * reaction_limit * result_amount //rearrange to obtain max_product
		var/yield_limit = max(0, max_product - holder.get_reagent_amount(result))/result_amount

		progress = min(progress, yield_limit) //apply yield limit

	//apply min reaction progress - wasn't sure if this should go before or after applying yield
	//I guess people can just have their miniscule reactions go to completion regardless of yield.
	for(var/reactant in required_reagents)
		var/remainder = holder.get_reagent_amount(reactant) - progress*required_reagents[reactant]
		if(remainder <= min_reaction*required_reagents[reactant])
			progress = reaction_limit
			break

	return progress

// This proc returns a list of all reagents it wants to use; if the holder has several reactions that use the same reagent, it will split the reagent evenly between them
/datum/chemical_reaction/proc/get_used_reagents()
	. = list()
	for(var/reagent in required_reagents)
		. += reagent

/datum/chemical_reaction/proc/process(datum/reagents/holder)
	//determine how far the reaction can proceed
	var/list/reaction_limits = list()
	for(var/reactant in required_reagents)
		reaction_limits += holder.get_reagent_amount(reactant) / required_reagents[reactant]

	//determine how far the reaction proceeds
	var/reaction_limit = min(reaction_limits)
	var/progress_limit = calc_reaction_progress(holder, reaction_limit)

	var/reaction_progress = min(reaction_limit, progress_limit) //no matter what, the reaction progress cannot exceed the stoichiometric limit.

	//need to obtain the new reagent's data before anything is altered
	var/data = send_data(holder, reaction_progress)

	//remove the reactants
	for(var/reactant in required_reagents)
		var/amt_used = required_reagents[reactant] * reaction_progress
		holder.remove_reagent(reactant, amt_used, safety = 1)

	//add the product
	var/amt_produced = result_amount * reaction_progress
	if(result)
		holder.add_reagent(result, amt_produced, data, safety = 1)

	on_reaction(holder, amt_produced)

	return reaction_progress

//called when a reaction processes
/datum/chemical_reaction/proc/on_reaction(var/datum/reagents/holder, var/created_volume)
	if(thermal_product)
		holder.chem_temp += thermal_product
	var/datum/reagents/to_splash = new()
	to_splash.maximum_volume = INFINITY
	//well i'll never test this cause there is no recipes with byproducts, so if YOU, yes you, the one who decided to add some, its up to you to fix this
	if(byproducts.len)
		for(var/i = 1 to created_volume/result_amount) // this to evenly fill holder
			for(var/id in byproducts)
				if(holder.get_free_space() > byproducts[id])
					holder.add_reagent(id, byproducts[id], safety = 1)
				else
					to_splash.add_reagent(id, byproducts[id], safety = 1)
	if(to_splash.total_volume)
		to_splash.handle_reactions()
		to_splash.splash(get_turf(holder.my_atom), to_splash.total_volume, 1, FALSE, to_splash.total_volume, to_splash.total_volume)
		qdel(to_splash)


//called after processing reactions, if they occurred
/datum/chemical_reaction/proc/post_reaction(var/datum/reagents/holder)
	var/atom/container = holder.my_atom
	if(mix_message && container && !ismob(container))
		var/turf/T = get_turf(container)
		var/list/seen = viewers(4, T)
		for(var/mob/M in seen)
			M.show_message(SPAN_NOTICE("\icon[container] [mix_message]"), 1)
		playsound(T, reaction_sound, 80, 1)

//obtains any special data that will be provided to the reaction products
//this is called just before reactants are removed.
/datum/chemical_reaction/proc/send_data(var/datum/reagents/holder, var/reaction_limit)
	return null

// UI data used by chemical catalog
/datum/chemical_reaction/nano_ui_data()
	var/list/dat = list()
	if(required_reagents)
		dat["reagents"] = list()
		for(var/id in required_reagents)
			dat["reagents"] += list(list("type" = get_reagent_type_by_id(id), "reagent" = get_reagent_name_by_id(id), "parts" = "[required_reagents[id]] part\s"))
	if(catalysts)
		dat["catalyst"] = list()
		for(var/id in catalysts)
			dat["catalyst"] += list(list("type" = get_reagent_type_by_id(id), "reagent" = get_reagent_name_by_id(id), "units" = catalysts[id]))

	dat["minimum_temperature"] = minimum_temperature
	if(maximum_temperature != INFINITY)
		dat["maximum_temperature"] = maximum_temperature

	dat["result_amount"] = "[result_amount] part\s"
	return dat
/* Common reactions */

/datum/chemical_reaction/inaprovaline
	result = "inaprovaline"
	required_reagents = list("acetone" = 1, "carbon" = 1, "sugar" = 1)
	result_amount = 3

/datum/chemical_reaction/dylovene
	result = "anti_toxin"
	required_reagents = list("silicon" = 1, "potassium" = 1, "ammonia" = 1)
	result_amount = 3

/datum/chemical_reaction/tramadol
	result = "tramadol"
	required_reagents = list("paracetamol" = 1, "sugar" = 1, "water" = 1)
	result_amount = 3

/datum/chemical_reaction/paracetamol
	result = "paracetamol"
	required_reagents = list("inaprovaline" = 1, "ethanol" = 1, "acetone" = 1)
	result_amount = 3

/datum/chemical_reaction/oxycodone
	result = "oxycodone"
	required_reagents = list("ethanol" = 1, "tramadol" = 1)
	catalysts = list("plasma" = 5)
	result_amount = 1

/datum/chemical_reaction/toxin
	result = "toxin"
	required_reagents = list("ammonia" = 1, "mercury" = 1, "ethanol" = 1)
	catalysts = list("plasma" = 5)
	result_amount = 3

/datum/chemical_reaction/sterilizine
	result = "sterilizine"
	required_reagents = list("ethanol" = 1, "anti_toxin" = 1, "hclacid" = 1)
	result_amount = 3

/datum/chemical_reaction/silicate
	result = "silicate"
	required_reagents = list("aluminum" = 1, "silicon" = 1, "acetone" = 1)
	result_amount = 3

/datum/chemical_reaction/mutagen
	result = "mutagen"
	required_reagents = list("radium" = 1, "phosphorus" = 1, "hclacid" = 1)
	result_amount = 3

/datum/chemical_reaction/thermite
	result = "thermite"
	required_reagents = list("aluminum" = 1, "iron" = 1, "acetone" = 1)
	result_amount = 3

/datum/chemical_reaction/space_drugs
	result = "space_drugs"
	required_reagents = list("mercury" = 1, "sugar" = 1, "lithium" = 1)
	result_amount = 3

/datum/chemical_reaction/nicotine
    result = "nicotine"
    required_reagents = list("toxin" = 1, "carbon" = 1, "capsaicin" = 1, "mercury" = 1)
    result_amount = 8

/datum/chemical_reaction/lube
	result = "lube"
	required_reagents = list("water" = 1, "silicon" = 1, "acetone" = 1)
	result_amount = 4

/datum/chemical_reaction/pacid
	result = "pacid"
	required_reagents = list("sacid" = 1, "hclacid" = 1, "potassium" = 1)
	result_amount = 3

/datum/chemical_reaction/synaptizine
	result = "synaptizine"
	required_reagents = list("sugar" = 1, "lithium" = 1, "water" = 1)
	result_amount = 3

/datum/chemical_reaction/hyronalin
	result = "hyronalin"
	required_reagents = list("radium" = 1, "anti_toxin" = 1)
	result_amount = 2

/datum/chemical_reaction/arithrazine
	result = "arithrazine"
	required_reagents = list("hyronalin" = 1, "hydrazine" = 1)
	result_amount = 2

/datum/chemical_reaction/impedrezene
	result = "impedrezene"
	required_reagents = list("mercury" = 1, "acetone" = 1, "sugar" = 1)
	result_amount = 2

/datum/chemical_reaction/kelotane
	result = "kelotane"
	required_reagents = list("silicon" = 1, "carbon" = 1)
	result_amount = 2
	log_is_important = 1

/datum/chemical_reaction/peridaxon
	result = "peridaxon"
	required_reagents = list("bicaridine" = 2, "clonexadone" = 2)
	catalysts = list("plasma" = 5)
	result_amount = 2

/datum/chemical_reaction/leporazine
	result = "leporazine"
	required_reagents = list("silicon" = 1, "copper" = 1)
	catalysts = list("plasma" = 5)
	result_amount = 2

/datum/chemical_reaction/cryptobiolin
	result = "cryptobiolin"
	required_reagents = list("potassium" = 1, "acetone" = 1, "sugar" = 1)
	result_amount = 3

/datum/chemical_reaction/tricordrazine
	result = "tricordrazine"
	required_reagents = list("inaprovaline" = 1, "anti_toxin" = 1)
	result_amount = 2

/datum/chemical_reaction/alkysine
	result = "alkysine"
	required_reagents = list("hclacid" = 1, "ammonia" = 1, "anti_toxin" = 1)
	result_amount = 2

/datum/chemical_reaction/dexalin
	result = "dexalin"
	required_reagents = list("acetone" = 2, "plasma" = 0.1)
	catalysts = list("plasma" = 1)
	inhibitors = list("water" = 1) // Messes with cryox
	result_amount = 1

/datum/chemical_reaction/dermaline
	result = "dermaline"
	required_reagents = list("acetone" = 1, "phosphorus" = 1, "kelotane" = 1)
	result_amount = 3

/datum/chemical_reaction/dexalinp
	result = "dexalinp"
	required_reagents = list("dexalin" = 1, "carbon" = 1, "iron" = 1)
	result_amount = 3

/datum/chemical_reaction/bicaridine
	result = "bicaridine"
	required_reagents = list("inaprovaline" = 2, "blattedin" = 1)
	inhibitors = list("sugar" = 1) // Messes up with inaprovaline
	result_amount = 3
/datum/chemical_reaction/meralyne
	result = "meralyne"
	required_reagents = list("hyperzine" = 1, "blattedin" = 2, "tramadol" = 1)
	result_amount = 2

/datum/chemical_reaction/hyperzine
	result = "hyperzine"
	required_reagents = list("sugar" = 1, "blattedin" = 1, "sulfur" = 1)
	result_amount = 3

/datum/chemical_reaction/ryetalyn
	result = "ryetalyn"
	required_reagents = list("arithrazine" = 1, "carbon" = 1)
	result_amount = 2

/datum/chemical_reaction/kognim
	result = "kognim"
	required_reagents = list("radium" = 1, "ryetalyn" = 2, "synaptizine" = 1)
	result_amount = 2

/datum/chemical_reaction/negative_ling
	result = "negativeling"
	required_reagents = list("ryetalyn" = 1, "carbon" = 1)
	result_amount = 1
	maximum_temperature = INFINITY
	minimum_temperature = 400

/datum/chemical_reaction/positive_ling
	result = "positiveling"
	required_reagents = list("negativeling" = 1, "blood" = 1)
	result_amount = 1
	maximum_temperature = INFINITY
	minimum_temperature = 700

/datum/chemical_reaction/positive_ling/can_happen(datum/reagents/holder)
	if(..())
		var/list/blood_data = holder.get_data("blood")
		if(blood_data["carrion"])
			return TRUE

	return FALSE

/datum/chemical_reaction/cryoxadone
	result = "cryoxadone"
	required_reagents = list("dexalin" = 1, "water" = 1, "acetone" = 1)
	result_amount = 3

/datum/chemical_reaction/clonexadone
	result = "clonexadone"
	required_reagents = list("cryoxadone" = 1, "sodium" = 1, "plasma" = 0.1)
	catalysts = list("plasma" = 5)
	result_amount = 2

/datum/chemical_reaction/spaceacillin
	result = "spaceacillin"
	required_reagents = list("cryptobiolin" = 1, "inaprovaline" = 1)
	result_amount = 2

/datum/chemical_reaction/spaceacillin_mold
	result = "spaceacillin"
	required_reagents = list("mold" = 1, "sugar" = 1, "acetone" = 1)
	result_amount = 6

/datum/chemical_reaction/imidazoline
	result = "imidazoline"
	required_reagents = list("carbon" = 1, "hydrazine" = 1, "anti_toxin" = 1)
	result_amount = 2

/datum/chemical_reaction/ethylredoxrazine
	result = "ethylredoxrazine"
	required_reagents = list("acetone" = 1, "anti_toxin" = 1, "carbon" = 1)
	result_amount = 3

/datum/chemical_reaction/soporific
	result = "stoxin"
	required_reagents = list("chloralhydrate" = 1, "sugar" = 4)
	inhibitors = list("phosphorus") // Messes with the smoke
	result_amount = 5

/datum/chemical_reaction/chloralhydrate
	result = "chloralhydrate"
	required_reagents = list("ethanol" = 1, "hclacid" = 3, "water" = 1)
	result_amount = 1

/datum/chemical_reaction/potassium_chloride
	result = "potassium_chloride"
	required_reagents = list("sodiumchloride" = 1, "potassium" = 1)
	result_amount = 2

/datum/chemical_reaction/potassium_chlorophoride
	result = "potassium_chlorophoride"
	required_reagents = list("potassium_chloride" = 1, "plasma" = 1, "chloralhydrate" = 1)
	result_amount = 4

/datum/chemical_reaction/zombiepowder
	result = "zombiepowder"
	required_reagents = list("carpotoxin" = 5, "stoxin" = 5, "copper" = 5)
	result_amount = 2

/datum/chemical_reaction/mindbreaker
	result = "mindbreaker"
	required_reagents = list("silicon" = 1, "hydrazine" = 1, "anti_toxin" = 1)
	result_amount = 3

/datum/chemical_reaction/mindwipe
	result = "mindwipe"
	required_reagents = list("mindbreaker" = 1, "anti_toxin" = 1, "ethanol" = 1)
	catalysts = list("whiskey" = 5)
	result_amount = 1

/datum/chemical_reaction/lipozine
	result = "lipozine"
	required_reagents = list("sodiumchloride" = 1, "ethanol" = 1, "radium" = 1)
	result_amount = 3

/datum/chemical_reaction/surfactant
	result = "surfactant"
	required_reagents = list("hydrazine" = 2, "carbon" = 2, "sacid" = 1)
	result_amount = 5

/datum/chemical_reaction/diethylamine
	result = "diethylamine"
	required_reagents = list ("ammonia" = 1, "ethanol" = 1)
	result_amount = 2

/datum/chemical_reaction/space_cleaner
	result = "cleaner"
	required_reagents = list("ammonia" = 1, "water" = 1)
	result_amount = 2

/datum/chemical_reaction/plantbgone
	result = "plantbgone"
	required_reagents = list("toxin" = 1, "water" = 4)
	result_amount = 5

/datum/chemical_reaction/foaming_agent
	result = "foaming_agent"
	required_reagents = list("lithium" = 1, "hydrazine" = 1)
	result_amount = 1

/datum/chemical_reaction/glycerol
	result = "glycerol"
	required_reagents = list("cornoil" = 3, "sacid" = 1)
	result_amount = 1

/datum/chemical_reaction/sodiumchloride
	result = "sodiumchloride"
	required_reagents = list("sodium" = 1, "hclacid" = 1)
	result_amount = 2

/datum/chemical_reaction/condensedcapsaicin
	result = "condensedcapsaicin"
	required_reagents = list("capsaicin" = 3)
	result_amount = 1
	maximum_temperature = INFINITY
	minimum_temperature = 373

/datum/chemical_reaction/coolant
	result = "coolant"
	required_reagents = list("tungsten" = 1, "acetone" = 1, "water" = 1)
	result_amount = 3

/datum/chemical_reaction/refrigerant
	result = "refrigerant"
	required_reagents = list("carbon" = 1, "acetone" = 1, "water" = 1)
	result_amount = 3

/datum/chemical_reaction/rezadone
	result = "rezadone"
	required_reagents = list("carpotoxin" = 1, "cryptobiolin" = 1, "copper" = 1)
	result_amount = 3

/datum/chemical_reaction/lexorin
	result = "lexorin"
	required_reagents = list("plasma" = 1, "hydrazine" = 1, "ammonia" = 1)
	result_amount = 3

/datum/chemical_reaction/methylphenidate
	result = "methylphenidate"
	required_reagents = list("mindbreaker" = 1, "hydrazine" = 1)
	result_amount = 3

/datum/chemical_reaction/citalopram
	result = "citalopram"
	required_reagents = list("mindbreaker" = 1, "carbon" = 1)
	result_amount = 3


/datum/chemical_reaction/paroxetine
	result = "paroxetine"
	required_reagents = list("mindbreaker" = 1, "acetone" = 1, "inaprovaline" = 1)
	result_amount = 3


/* Solidification */

/datum/chemical_reaction/plasmasolidification
	result = null
	required_reagents = list("iron" = 5, "frostoil" = 5, "plasma" = 20)
	result_amount = 1

/datum/chemical_reaction/plasmasolidification/on_reaction(var/datum/reagents/holder, var/created_volume)
	new /obj/item/stack/material/plasma(get_turf(holder.my_atom), created_volume)
	return

/datum/chemical_reaction/goldsolidification
	result = null
	required_reagents = list("iron" = 5, "frostoil" = 5, "gold" = 20)
	result_amount = 1

/datum/chemical_reaction/goldsolidification/on_reaction(var/datum/reagents/holder, var/created_volume)
	new /obj/item/stack/material/gold(get_turf(holder.my_atom), created_volume)
	return

/datum/chemical_reaction/uraniumsolidification
	result = null
	required_reagents = list("aluminum" = 5, "frostoil" = 10, "uranium" = 20)
	result_amount = 1

/datum/chemical_reaction/uraniumsolidification/on_reaction(var/datum/reagents/holder, var/created_volume)
	new /obj/item/stack/material/uranium(get_turf(holder.my_atom), created_volume)
	return

/datum/chemical_reaction/silversolidification
	result = null
	required_reagents = list("iron" = 5, "frostoil" = 5, "silver" = 20)
	result_amount = 1

/datum/chemical_reaction/silversolidification/on_reaction(var/datum/reagents/holder, var/created_volume)
	new /obj/item/stack/material/silver(get_turf(holder.my_atom), created_volume)
	return

/datum/chemical_reaction/plastication
	result = null
	required_reagents = list("pacid" = 1, "plasticide" = 2)
	result_amount = 1

/datum/chemical_reaction/plastication/on_reaction(var/datum/reagents/holder, var/created_volume)
	new /obj/item/stack/material/plastic(get_turf(holder.my_atom), created_volume)
	return

/* Grenade reactions */

/datum/chemical_reaction/explosion_potassium
	result = null
	required_reagents = list("water" = 1, "potassium" = 1)
	result_amount = 2
	mix_message = null

/datum/chemical_reaction/explosion_potassium/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/datum/effect/effect/system/reagents_explosion/e = new()
	e.set_up(round (created_volume/45, 1), holder.my_atom, 0, 0) // 600/45 = 13.3 , 13/3 = 4-3 light-range , slightly weaker than a cracker.
	if(isliving(holder.my_atom))
		e.amount *= 0.5
		var/mob/living/L = holder.my_atom
		if(L.stat != DEAD)
			if(e.amount >= 6)
				L.gib()
			e.amount *= 1.5
	e.start()
	holder.clear_reagents()
	return

/datum/chemical_reaction/flash_powder
	result = null
	required_reagents = list("aluminum" = 1, "potassium" = 1, "sulfur" = 1 )
	result_amount = null

/datum/chemical_reaction/flash_powder/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)
	var/datum/effect/effect/system/spark_spread/s = new /datum/effect/effect/system/spark_spread
	s.set_up(2, 1, location)
	s.start()
	for(var/mob/living/carbon/M in viewers(world.view, location))
		switch(get_dist(M, location))
			if(0 to 3)
				if(M.eyecheck() <= FLASH_PROTECTION_MAJOR)
					M.flash(15, FALSE , FALSE , FALSE)

			if(4 to 5)
				if(M.eyecheck() <= FLASH_PROTECTION_MAJOR)
					M.flash(0, FALSE , FALSE , FALSE)

/datum/chemical_reaction/emp_pulse
	result = null
	required_reagents = list(MATERIAL_URANIUM = 1, "iron" = 1) // Yes, laugh, it's the best recipe I could think of that makes a little bit of sense
	result_amount = 2

/datum/chemical_reaction/emp_pulse/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)
	// 100 created volume = 4 heavy range & 7 light range. A few tiles smaller than contractor EMP grandes.
	// 200 created volume = 8 heavy range & 14 light range. 4 tiles larger than contractor EMP grenades.
	empulse(location, round(created_volume / 24), round(created_volume / 14), 1)
	holder.clear_reagents()
	return

/datum/chemical_reaction/nitroglycerin
	result = "nitroglycerin"
	required_reagents = list("glycerol" = 1, "pacid" = 1, "sacid" = 1)
	result_amount = 2
	log_is_important = 1

/datum/chemical_reaction/nitroglycerin/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/datum/effect/effect/system/reagents_explosion/e = new()
	e.set_up(round (created_volume/2, 1), holder.my_atom, 0, 0)
	if(isliving(holder.my_atom))
		e.amount *= 0.5
		var/mob/living/L = holder.my_atom
		if(L.stat!=DEAD)
			e.amount *= 0.5
	e.start()

	holder.clear_reagents()
	return

/datum/chemical_reaction/napalm
	result = null
	required_reagents = list("aluminum" = 1, "plasma" = 1, "sacid" = 1 )
	result_amount = 1

/datum/chemical_reaction/napalm/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/turf/location = get_turf(holder.my_atom.loc)
	for(var/turf/simulated/floor/target_tile in range(0,location))
		target_tile.assume_gas("plasma", created_volume, 400+T0C)
		spawn (0) target_tile.hotspot_expose(700, 400)
	holder.del_reagent("napalm")
	return

/datum/chemical_reaction/chemsmoke
	result = null
	required_reagents = list("potassium" = 1, "sugar" = 1, "phosphorus" = 1)
	result_amount = 0.4

/datum/chemical_reaction/chemsmoke/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)
	var/datum/effect/effect/system/smoke_spread/chem/S = new /datum/effect/effect/system/smoke_spread/chem
	S.attach(location)
	S.set_up(holder, created_volume, 0, location)
	playsound(location, 'sound/effects/smoke.ogg', 50, 1, -3)
	spawn(0)
		S.start()
	holder.clear_reagents()
	return

/datum/chemical_reaction/foam
	result = null
	required_reagents = list("surfactant" = 1, "water" = 1)
	result_amount = 2
	mix_message = "The solution violently bubbles!"

/datum/chemical_reaction/foam/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)

	for(var/mob/M in viewers(5, location))
		to_chat(M, SPAN_WARNING("The solution spews out foam!"))

	var/datum/effect/effect/system/foam_spread/s = new()
	s.set_up(created_volume, location, holder, 0)
	s.start()
	holder.clear_reagents()
	return

/datum/chemical_reaction/metalfoam
	result = null
	required_reagents = list("aluminum" = 3, "foaming_agent" = 1, "pacid" = 1)
	result_amount = 5

/datum/chemical_reaction/metalfoam/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)

	for(var/mob/M in viewers(5, location))
		to_chat(M, SPAN_WARNING("The solution spews out a metalic foam!"))

	var/datum/effect/effect/system/foam_spread/s = new()
	s.set_up(created_volume, location, holder, 1)
	s.start()
	return

/datum/chemical_reaction/ironfoam
	result = null
	required_reagents = list("iron" = 3, "foaming_agent" = 1, "pacid" = 1)
	result_amount = 5

/datum/chemical_reaction/ironfoam/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)

	for(var/mob/M in viewers(5, location))
		to_chat(M, SPAN_WARNING("The solution spews out a metalic foam!"))

	var/datum/effect/effect/system/foam_spread/s = new()
	s.set_up(created_volume, location, holder, 2)
	s.start()
	return

/* Paint */

/datum/chemical_reaction/red_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_red" = 1)
	result_amount = 5

/datum/chemical_reaction/red_paint/send_data()
	return "#FE191A"

/datum/chemical_reaction/orange_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_orange" = 1)
	result_amount = 5

/datum/chemical_reaction/orange_paint/send_data()
	return "#FFBE4F"

/datum/chemical_reaction/yellow_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_yellow" = 1)
	result_amount = 5

/datum/chemical_reaction/yellow_paint/send_data()
	return "#FDFE7D"

/datum/chemical_reaction/green_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_green" = 1)
	result_amount = 5

/datum/chemical_reaction/green_paint/send_data()
	return "#18A31A"

/datum/chemical_reaction/blue_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_blue" = 1)
	result_amount = 5

/datum/chemical_reaction/blue_paint/send_data()
	return "#247CFF"

/datum/chemical_reaction/purple_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_purple" = 1)
	result_amount = 5

/datum/chemical_reaction/purple_paint/send_data()
	return "#CC0099"

/datum/chemical_reaction/grey_paint //mime
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_grey" = 1)
	result_amount = 5

/datum/chemical_reaction/grey_paint/send_data()
	return "#808080"

/datum/chemical_reaction/brown_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_brown" = 1)
	result_amount = 5

/datum/chemical_reaction/brown_paint/send_data()
	return "#846F35"

/datum/chemical_reaction/blood_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "blood" = 2)
	result_amount = 5

/datum/chemical_reaction/blood_paint/send_data(var/datum/reagents/T)
	var/t = T.get_data("blood")
	if(t && t["blood_colour"])
		return t["blood_colour"]
	return "#FE191A" // Probably red

/datum/chemical_reaction/milk_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "milk" = 5)
	result_amount = 5

/datum/chemical_reaction/milk_paint/send_data()
	return "#F0F8FF"

/datum/chemical_reaction/orange_juice_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "orangejuice" = 5)
	result_amount = 5

/datum/chemical_reaction/orange_juice_paint/send_data()
	return "#E78108"

/datum/chemical_reaction/tomato_juice_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "tomatojuice" = 5)
	result_amount = 5

/datum/chemical_reaction/tomato_juice_paint/send_data()
	return "#731008"

/datum/chemical_reaction/lime_juice_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "limejuice" = 5)
	result_amount = 5

/datum/chemical_reaction/lime_juice_paint/send_data()
	return "#365E30"

/datum/chemical_reaction/carrot_juice_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "carrotjuice" = 5)
	result_amount = 5

/datum/chemical_reaction/carrot_juice_paint/send_data()
	return "#973800"

/datum/chemical_reaction/berry_juice_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "berryjuice" = 5)
	result_amount = 5

/datum/chemical_reaction/berry_juice_paint/send_data()
	return "#990066"

/datum/chemical_reaction/grape_juice_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "grapejuice" = 5)
	result_amount = 5

/datum/chemical_reaction/grape_juice_paint/send_data()
	return "#863333"

/datum/chemical_reaction/poisonberry_juice_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "poisonberryjuice" = 5)
	result_amount = 5

/datum/chemical_reaction/poisonberry_juice_paint/send_data()
	return "#863353"

/datum/chemical_reaction/watermelon_juice_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "watermelonjuice" = 5)
	result_amount = 5

/datum/chemical_reaction/watermelon_juice_paint/send_data()
	return "#B83333"

/datum/chemical_reaction/lemon_juice_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "lemonjuice" = 5)
	result_amount = 5

/datum/chemical_reaction/lemon_juice_paint/send_data()
	return "#AFAF00"

/datum/chemical_reaction/banana_juice_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "banana" = 5)
	result_amount = 5

/datum/chemical_reaction/banana_juice_paint/send_data()
	return "#C3AF00"

/datum/chemical_reaction/potato_juice_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "potato" = 5)
	result_amount = 5

/datum/chemical_reaction/potato_juice_paint/send_data()
	return "#302000"

/datum/chemical_reaction/carbon_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "carbon" = 1)
	result_amount = 5

/datum/chemical_reaction/carbon_paint/send_data()
	return "#333333"

/datum/chemical_reaction/aluminum_paint
	result = "paint"
	required_reagents = list("plasticide" = 1, "water" = 3, "aluminum" = 1)
	result_amount = 5

/datum/chemical_reaction/aluminum_paint/send_data()
	return "#F0F8FF"

/* Slime cores */

/datum/chemical_reaction/slime
	var/required = null

/datum/chemical_reaction/slime/nano_ui_data()
	var/list/dat = ..()
	dat["required_object"] = required
	return dat

/datum/chemical_reaction/slime/can_happen(var/datum/reagents/holder)
	if(holder.my_atom && istype(holder.my_atom, required))
		var/obj/item/slime_extract/T = holder.my_atom
		if(T.Uses > 0)
			return ..()
	return 0

/datum/chemical_reaction/slime/on_reaction(var/datum/reagents/holder)
	var/obj/item/slime_extract/T = holder.my_atom
	T.Uses--
	if(T.Uses <= 0)
		T.visible_message("\icon[T]<span class='notice'>\The [T]'s power is consumed in the reaction.</span>")
		T.name = "used slime extract"
		T.desc = "This extract has been used up."

//Grey
/datum/chemical_reaction/slime/spawn
	result = null
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/grey

/datum/chemical_reaction/slime/spawn/on_reaction(var/datum/reagents/holder)
	holder.my_atom.visible_message(SPAN_WARNING("Infused with plasma, the core begins to quiver and grow, and soon a new baby slime emerges from it!"))
	var/mob/living/carbon/slime/S = new /mob/living/carbon/slime
	S.loc = get_turf(holder.my_atom)
	..()

/datum/chemical_reaction/slime/monkey
	result = null
	required_reagents = list("blood" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/grey

/datum/chemical_reaction/slime/monkey/on_reaction(var/datum/reagents/holder)
	for(var/i = 1, i <= 3, i++)
		var /obj/item/reagent_containers/food/snacks/monkeycube/M = new /obj/item/reagent_containers/food/snacks/monkeycube
		M.loc = get_turf(holder.my_atom)
	..()

//Green
/datum/chemical_reaction/slime/mutate
	result = "mutationtoxin"
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/green

//Metal
/datum/chemical_reaction/slime/metal
	result = null
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/metal

/datum/chemical_reaction/slime/metal/on_reaction(var/datum/reagents/holder)
	var/obj/item/stack/material/steel/M = new /obj/item/stack/material/steel
	M.amount = 15
	M.loc = get_turf(holder.my_atom)
	var/obj/item/stack/material/plasteel/P = new /obj/item/stack/material/plasteel
	P.amount = 5
	P.loc = get_turf(holder.my_atom)
	..()

//Gold - removed
/datum/chemical_reaction/slime/crit
	result = null
	required_reagents = list("blood" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/gold
	mix_message = "The slime extract begins to vibrate violently!"

/datum/chemical_reaction/slime/crit/on_reaction(var/datum/reagents/holder)
	for(var/i = 1 to 2)
		var/roachcube = pick(subtypesof(/obj/item/reagent_containers/food/snacks/roachcube))
		new roachcube(get_turf(holder.my_atom))
	..()

//Silver
/datum/chemical_reaction/slime/bork
	result = null
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/silver

/datum/chemical_reaction/slime/bork/on_reaction(var/datum/reagents/holder)
	var/list/borks = typesof(/obj/item/reagent_containers/food/snacks) - /obj/item/reagent_containers/food/snacks
	playsound(get_turf(holder.my_atom), 'sound/effects/phasein.ogg', 100, 1)
	for(var/mob/living/carbon/human/M in viewers(get_turf(holder.my_atom), null))
		if(M.eyecheck() < FLASH_PROTECTION_MODERATE)
			M.flash(0, FALSE , FALSE , FALSE, 0) // flashed by the gods or something idk

	for(var/i = 1, i <= 4 + rand(1,2), i++)
		var/chosen = pick(borks)
		var/obj/B = new chosen
		if(B)
			B.loc = get_turf(holder.my_atom)
			if(prob(50))
				for(var/j = 1, j <= rand(1, 3), j++)
					step(B, pick(NORTH, SOUTH, EAST, WEST))
	..()

//Blue
/datum/chemical_reaction/slime/frost
	result = "frostoil"
	required_reagents = list("plasma" = 1)
	result_amount = 10
	required = /obj/item/slime_extract/blue

//Dark Blue
/datum/chemical_reaction/slime/freeze
	result = null
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/darkblue
	mix_message = "The slime extract begins to vibrate violently!"

/datum/chemical_reaction/slime/freeze/on_reaction(var/datum/reagents/holder)
	..()
	addtimer(CALLBACK(src, PROC_REF(do_freeze), get_turf(holder.my_atom), 5 SECONDS))

/datum/chemical_reaction/slime/freeze/proc/do_freeze(turf/target)
	playsound(target, 'sound/effects/phasein.ogg', 100, 1)
	for(var/mob/living/M in range (target, 7))
		M.bodytemperature -= 140
		to_chat(M, SPAN_WARNING("You feel a chill!"))





//Orange
/datum/chemical_reaction/slime/casp
	result = "capsaicin"
	required_reagents = list("blood" = 1)
	result_amount = 10
	required = /obj/item/slime_extract/orange

/datum/chemical_reaction/slime/fire
	result = null
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/orange
	mix_message = "The slime extract begins to vibrate violently!"

/datum/chemical_reaction/slime/fire/on_reaction(var/datum/reagents/holder)
	..()
	addtimer(CALLBACK(src, PROC_REF(do_fire), get_turf(holder.my_atom), 5 SECONDS))

/datum/chemical_reaction/slime/fire/proc/do_fire(turf/target)
	for(var/turf/simulated/floor/target_tile in range(0, target))
		target_tile.assume_gas("plasma", 25, 1400)
		target_tile.hotspot_expose(700, 400)

//Yellow
/datum/chemical_reaction/slime/overload
	result = null
	required_reagents = list("blood" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/yellow

/datum/chemical_reaction/slime/overload/on_reaction(var/datum/reagents/holder, var/created_volume)
	..()
	empulse(get_turf(holder.my_atom), 3, 7)

/datum/chemical_reaction/slime/cell
	result = null
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/yellow

/datum/chemical_reaction/slime/cell/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/obj/item/cell/large/slime/P = new /obj/item/cell/large/slime
	P.loc = get_turf(holder.my_atom)

/datum/chemical_reaction/slime/glow
	result = null
	required_reagents = list("water" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/yellow
	mix_message = "The contents of the slime core harden and begin to emit a warm, bright light."

/datum/chemical_reaction/slime/glow/on_reaction(var/datum/reagents/holder, var/created_volume)
	..()
	var/obj/item/device/slimelight/F = new /obj/item/device/slimelight
	F.loc = get_turf(holder.my_atom)

//Purple
/datum/chemical_reaction/slime/psteroid
	result = null
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/purple

/datum/chemical_reaction/slime/psteroid/on_reaction(var/datum/reagents/holder, var/created_volume)
	..()
	var/obj/item/slimesteroid/P = new /obj/item/slimesteroid
	P.loc = get_turf(holder.my_atom)

/datum/chemical_reaction/slime/jam
	result = "slimejelly"
	required_reagents = list("sugar" = 1)
	result_amount = 10
	required = /obj/item/slime_extract/purple

//Dark Purple
/datum/chemical_reaction/slime/plasma
	result = null
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/darkpurple

/datum/chemical_reaction/slime/plasma/on_reaction(var/datum/reagents/holder)
	..()
	var/obj/item/stack/material/plasma/P = new /obj/item/stack/material/plasma
	P.amount = 10
	P.loc = get_turf(holder.my_atom)

//Red
/datum/chemical_reaction/slime/glycerol
	result = "glycerol"
	required_reagents = list("plasma" = 1)
	result_amount = 8
	required = /obj/item/slime_extract/red

/datum/chemical_reaction/slime/bloodlust
	result = null
	required_reagents = list("blood" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/red

/datum/chemical_reaction/slime/bloodlust/on_reaction(var/datum/reagents/holder)
	..()
	for(var/mob/living/carbon/slime/slime in viewers(get_turf(holder.my_atom), null))
		slime.rabid = 1
		slime.visible_message(SPAN_WARNING("The [slime] is driven into a frenzy!"))

//Pink
/datum/chemical_reaction/slime/ppotion
	result = null
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/pink

/datum/chemical_reaction/slime/ppotion/on_reaction(var/datum/reagents/holder)
	..()
	var/obj/item/slimepotion/P = new /obj/item/slimepotion
	P.loc = get_turf(holder.my_atom)

//Black
/datum/chemical_reaction/slime/mutate2
	result = "amutationtoxin"
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/black

//Oil
/datum/chemical_reaction/slime/explosion
	result = null
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/oil
	mix_message = "The slime extract begins to vibrate violently!"

/datum/chemical_reaction/slime/explosion/on_reaction(var/datum/reagents/holder)
	..()
	addtimer(CALLBACK(src, PROC_REF(do_explode), get_turf(holder.my_atom), 5 SECONDS))

/datum/chemical_reaction/slime/explosion/proc/do_explode(turf/target)
	explosion(target, 600, 50)

//Light Pink
/datum/chemical_reaction/slime/potion2
	result = null
	result_amount = 1
	required = /obj/item/slime_extract/lightpink
	required_reagents = list("plasma" = 1)

/datum/chemical_reaction/slime/potion2/on_reaction(var/datum/reagents/holder)
	..()
	var/obj/item/slimepotion2/P = new /obj/item/slimepotion2
	P.loc = get_turf(holder.my_atom)

//Adamantine
/datum/chemical_reaction/slime/golem
	result = null
	required_reagents = list("plasma" = 1)
	result_amount = 1
	required = /obj/item/slime_extract/adamantine

/datum/chemical_reaction/slime/golem/on_reaction(var/datum/reagents/holder)
	..()
	var/obj/effect/golemrune/Z = new /obj/effect/golemrune
	Z.loc = get_turf(holder.my_atom)
	Z.announce_to_ghosts()

/* Food */

/datum/chemical_reaction/tofu
	result = null
	required_reagents = list("soymilk" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 1
	blacklist_containers = list(/mob)

/datum/chemical_reaction/tofu/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/tofu(location)

/datum/chemical_reaction/chocolate_bar
	result = null
	required_reagents = list("soymilk" = 2, "coco" = 2, "sugar" = 2)
	result_amount = 1
	blacklist_containers = list(/mob)

/datum/chemical_reaction/chocolate_bar/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/chocolatebar(location)

/datum/chemical_reaction/chocolate_bar2
	result = null
	required_reagents = list("milk" = 2, "coco" = 2, "sugar" = 2)
	result_amount = 1
	blacklist_containers = list(/mob)

/datum/chemical_reaction/chocolate_bar2/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/chocolatebar(location)

/datum/chemical_reaction/hot_coco
	result = "hot_coco"
	required_reagents = list("water" = 5, "coco" = 1)
	result_amount = 5

/datum/chemical_reaction/soysauce
	result = "soysauce"
	required_reagents = list("soymilk" = 4, "sacid" = 1)
	result_amount = 5

/datum/chemical_reaction/ketchup
	result = "ketchup"
	required_reagents = list("tomatojuice" = 2, "water" = 1, "sugar" = 1)
	result_amount = 4

/datum/chemical_reaction/cheesewheel
	result = null
	required_reagents = list("milk" = 40)
	catalysts = list("enzyme" = 5)
	result_amount = 1
	blacklist_containers = list(/mob)

/datum/chemical_reaction/cheesewheel/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/sliceable/cheesewheel(location)

/datum/chemical_reaction/meatball
	result = null
	required_reagents = list("protein" = 3, "flour" = 5)
	result_amount = 3
	blacklist_containers = list(/mob)

/datum/chemical_reaction/meatball/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/meatball(location)

/datum/chemical_reaction/dough
	result = null
	required_reagents = list("egg" = 3, "flour" = 10)
	result_amount = 1
	blacklist_containers = list(/mob)

/datum/chemical_reaction/dough/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/dough(location)

/datum/chemical_reaction/syntiflesh
	result = null
	required_reagents = list("blood" = 5, "clonexadone" = 1)
	result_amount = 1
	blacklist_containers = list(/mob)

/datum/chemical_reaction/syntiflesh/on_reaction(var/datum/reagents/holder, var/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/meat/syntiflesh(location)

/datum/chemical_reaction/hot_ramen
	result = "hot_ramen"
	required_reagents = list("water" = 1, "dry_ramen" = 3)
	result_amount = 3

/datum/chemical_reaction/hell_ramen
	result = "hell_ramen"
	required_reagents = list("capsaicin" = 1, "hot_ramen" = 6)
	result_amount = 6

/* Alcohol */

/datum/chemical_reaction/goldschlager
	result = "goldschlager"
	required_reagents = list("vodka" = 10, MATERIAL_GOLD = 1)
	result_amount = 10

/datum/chemical_reaction/patron
	result = "patron"
	required_reagents = list("tequilla" = 10, MATERIAL_SILVER = 1)
	result_amount = 10

/datum/chemical_reaction/bilk
	result = "bilk"
	required_reagents = list("milk" = 1, "beer" = 1)
	result_amount = 2

/datum/chemical_reaction/icetea
	result = "icetea"
	required_reagents = list("ice" = 1, "tea" = 2)
	result_amount = 3

/datum/chemical_reaction/icegreentea
	result = "icegreentea"
	required_reagents = list("ice" = 1, "greentea" = 2)
	result_amount = 3

/datum/chemical_reaction/icecoffee
	result = "icecoffee"
	required_reagents = list("ice" = 1, "coffee" = 2)
	result_amount = 3

/datum/chemical_reaction/nuka_cola
	result = "nuka_cola"
	required_reagents = list(MATERIAL_URANIUM = 1, "cola" = 5)
	result_amount = 5

/datum/chemical_reaction/moonshine
	result = "moonshine"
	required_reagents = list("nutriment" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/grenadine
	result = "grenadine"
	required_reagents = list("berryjuice" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/wine
	result = "wine"
	required_reagents = list("grapejuice" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/pwine
	result = "pwine"
	required_reagents = list("poisonberryjuice" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/melonliquor
	result = "melonliquor"
	required_reagents = list("watermelonjuice" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/bluecuracao
	result = "bluecuracao"
	required_reagents = list("orangejuice" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/spacebeer
	result = "beer"
	required_reagents = list("cornoil" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/vodka
	result = "vodka"
	required_reagents = list("potato" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/sake
	result = "sake"
	required_reagents = list("rice" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/kahlua
	result = "kahlua"
	required_reagents = list("coffee" = 5, "sugar" = 5)
	catalysts = list("enzyme" = 5)
	result_amount = 5

/datum/chemical_reaction/gin_tonic
	result = "gintonic"
	required_reagents = list("gin" = 2, "tonic" = 1)
	result_amount = 3

/datum/chemical_reaction/cuba_libre
	result = "cubalibre"
	required_reagents = list("rum" = 2, "cola" = 1)
	result_amount = 3

/datum/chemical_reaction/martini
	result = "martini"
	required_reagents = list("gin" = 2, "vermouth" = 1)
	result_amount = 3

/datum/chemical_reaction/vodkamartini
	result = "vodkamartini"
	required_reagents = list("vodka" = 2, "vermouth" = 1)
	result_amount = 3

/datum/chemical_reaction/white_russian
	result = "whiterussian"
	required_reagents = list("blackrussian" = 2, "cream" = 1)
	result_amount = 3

/datum/chemical_reaction/whiskey_cola
	result = "whiskeycola"
	required_reagents = list("whiskey" = 2, "cola" = 1)
	result_amount = 3

/datum/chemical_reaction/screwdriver
	result = "screwdrivercocktail"
	required_reagents = list("vodka" = 2, "orangejuice" = 1)
	result_amount = 3

/datum/chemical_reaction/bloody_mary
	result = "bloodymary"
	required_reagents = list("vodka" = 2, "tomatojuice" = 3, "limejuice" = 1)
	result_amount = 6

/datum/chemical_reaction/gargle_blaster_lite
	result = "gargleblasterlite"
	required_reagents = list("vodka" = 2, "gin" = 1, "whiskey" = 1, "cognac" = 1, "limejuice" = 1)
	result_amount = 6

/datum/chemical_reaction/gargle_blaster
	result = "gargleblaster"
	required_reagents = list("sbiten" = 1, "carpotoxin" = 1, "singulo" = 1, "pwine" = 1, "fuhrerole" = 1, "limejuice" = 1)
	result_amount = 2
	maximum_pressure = 80

/datum/chemical_reaction/brave_bull
	result = "bravebull"
	required_reagents = list("tequilla" = 2, "kahlua" = 1)
	result_amount = 3

/datum/chemical_reaction/tequilla_sunrise
	result = "tequillasunrise"
	required_reagents = list("tequilla" = 2, "orangejuice" = 1)
	result_amount = 3

/datum/chemical_reaction/plasma_special
	result = "plasmaspecial"
	required_reagents = list("rum" = 2, "vermouth" = 2, "plasma" = 2)
	result_amount = 6

/datum/chemical_reaction/beepsky_smash
	result = "beepskysmash"
	required_reagents = list("limejuice" = 1, "whiskey" = 1, "iron" = 1)
	result_amount = 2

/datum/chemical_reaction/doctor_delight
	result = "doctorsdelight"
	required_reagents = list("limejuice" = 1, "tomatojuice" = 1, "orangejuice" = 1, "cream" = 2, "tricordrazine" = 1)
	result_amount = 6

/datum/chemical_reaction/irish_cream
	result = "irishcream"
	required_reagents = list("whiskey" = 2, "cream" = 1)
	result_amount = 3

/datum/chemical_reaction/manly_dorf
	result = "manlydorf"
	required_reagents = list ("beer" = 1, "ale" = 2)
	result_amount = 3

/datum/chemical_reaction/hooch
	result = "hooch"
	required_reagents = list ("sugar" = 1, "ethanol" = 2, "fuel" = 1)
	result_amount = 3

/datum/chemical_reaction/irish_coffee
	result = "irishcoffee"
	required_reagents = list("irishcream" = 1, "coffee" = 1)
	result_amount = 2

/datum/chemical_reaction/b52
	result = "b52"
	required_reagents = list("irishcream" = 1, "kahlua" = 1, "cognac" = 1)
	result_amount = 3

/datum/chemical_reaction/atomicbomb
	result = "atomicbomb"
	required_reagents = list("b52" = 10, MATERIAL_URANIUM = 1)
	result_amount = 10

/datum/chemical_reaction/margarita
	result = "margarita"
	required_reagents = list("tequilla" = 2, "limejuice" = 1)
	result_amount = 3

/datum/chemical_reaction/longislandicedtea
	result = "longislandicedtea"
	required_reagents = list("vodka" = 1, "gin" = 1, "tequilla" = 1, "cubalibre" = 3)
	result_amount = 6

/datum/chemical_reaction/threemileisland
	result = "threemileisland"
	required_reagents = list("longislandicedtea" = 10, MATERIAL_URANIUM = 1)
	result_amount = 10

/datum/chemical_reaction/whiskeysoda
	result = "whiskeysoda"
	required_reagents = list("whiskey" = 2, "sodawater" = 1)
	result_amount = 3

/datum/chemical_reaction/black_russian
	result = "blackrussian"
	required_reagents = list("vodka" = 2, "kahlua" = 1)
	result_amount = 3

/datum/chemical_reaction/manhattan
	result = "manhattan"
	required_reagents = list("whiskey" = 2, "vermouth" = 1)
	result_amount = 3

/datum/chemical_reaction/manhattan_proj
	result = "manhattan_proj"
	required_reagents = list("manhattan" = 10, MATERIAL_URANIUM = 1)
	result_amount = 10

/datum/chemical_reaction/vodka_tonic
	result = "vodkatonic"
	required_reagents = list("vodka" = 2, "tonic" = 1)
	result_amount = 3

/datum/chemical_reaction/gin_fizz
	result = "ginfizz"
	required_reagents = list("gin" = 1, "sodawater" = 1, "limejuice" = 1)
	result_amount = 3

/datum/chemical_reaction/bahama_mama
	result = "bahama_mama"
	required_reagents = list("rum" = 2, "orangejuice" = 2, "limejuice" = 1, "ice" = 1)
	result_amount = 6

/datum/chemical_reaction/singulo
	result = "singulo"
	required_reagents = list("vodka" = 5, "radium" = 1, "wine" = 5)
	result_amount = 10

/datum/chemical_reaction/alliescocktail
	result = "alliescocktail"
	required_reagents = list("martini" = 1, "vodka" = 1)
	result_amount = 2

/datum/chemical_reaction/demonsblood
	result = "demonsblood"
	required_reagents = list("rum" = 3, "spacemountainwind" = 1, "blood" = 1, "dr_gibb" = 1)
	result_amount = 6

/datum/chemical_reaction/booger
	result = "booger"
	required_reagents = list("cream" = 2, "banana" = 1, "rum" = 1, "watermelonjuice" = 1)
	result_amount = 5

/datum/chemical_reaction/antifreeze
	result = "antifreeze"
	required_reagents = list("vodka" = 1, "cream" = 1, "ice" = 1)
	result_amount = 3

/datum/chemical_reaction/barefoot
	result = "barefoot"
	required_reagents = list("berryjuice" = 1, "cream" = 1, "vermouth" = 1)
	result_amount = 3

/datum/chemical_reaction/grapesoda
	result = "grapesoda"
	required_reagents = list("grapejuice" = 2, "cola" = 1)
	result_amount = 3

/datum/chemical_reaction/sbiten
	result = "sbiten"
	required_reagents = list("vodka" = 10, "capsaicin" = 1)
	result_amount = 10

/datum/chemical_reaction/red_mead
	result = "red_mead"
	required_reagents = list("blood" = 1, "mead" = 1)
	result_amount = 2

/datum/chemical_reaction/mead
	result = "mead"
	required_reagents = list("honey" = 1, "water" = 1)
	catalysts = list("enzyme" = 5)
	result_amount = 2

/datum/chemical_reaction/iced_beer
	result = "iced_beer"
	required_reagents = list("beer" = 10, "frostoil" = 1)
	result_amount = 10

/datum/chemical_reaction/iced_beer2
	result = "iced_beer"
	required_reagents = list("beer" = 5, "ice" = 1)
	result_amount = 6

/datum/chemical_reaction/grog
	result = "grog"
	required_reagents = list("rum" = 1, "water" = 1)
	result_amount = 2

/datum/chemical_reaction/soy_latte
	result = "soy_latte"
	required_reagents = list("coffee" = 1, "soymilk" = 1)
	result_amount = 2

/datum/chemical_reaction/cafe_latte
	result = "cafe_latte"
	required_reagents = list("coffee" = 1, "milk" = 1)
	result_amount = 2

/datum/chemical_reaction/acidspit
	result = "acidspit"
	required_reagents = list("sacid" = 1, "wine" = 5)
	result_amount = 6

/datum/chemical_reaction/amasec
	result = "amasec"
	required_reagents = list("iron" = 1, "wine" = 5, "vodka" = 5)
	result_amount = 10

/datum/chemical_reaction/changelingsting
	result = "changelingsting"
	required_reagents = list("screwdrivercocktail" = 1, "limejuice" = 1, "lemonjuice" = 1)
	result_amount = 3

/datum/chemical_reaction/aloe
	result = "aloe"
	required_reagents = list("cream" = 1, "whiskey" = 1, "watermelonjuice" = 1)
	result_amount = 3

/datum/chemical_reaction/andalusia
	result = "andalusia"
	required_reagents = list("rum" = 1, "whiskey" = 1, "lemonjuice" = 1)
	result_amount = 3

/datum/chemical_reaction/neurotoxin
	result = "neurotoxin"
	required_reagents = list("gargleblaster" = 1, "stoxin" = 1)
	result_amount = 2

/datum/chemical_reaction/snowwhite
	result = "snowwhite"
	required_reagents = list("beer" = 1, "lemon_lime" = 1)
	result_amount = 2

/datum/chemical_reaction/irishcarbomb
	result = "irishcarbomb"
	required_reagents = list("ale" = 1, "irishcream" = 1)
	result_amount = 2

/datum/chemical_reaction/syndicatebomb
	result = "syndicatebomb"
	required_reagents = list("beer" = 1, "whiskeycola" = 1)
	result_amount = 2

/datum/chemical_reaction/erikasurprise
	result = "erikasurprise"
	required_reagents = list("ale" = 2, "limejuice" = 1, "whiskey" = 1, "banana" = 1, "ice" = 1)
	result_amount = 6

/datum/chemical_reaction/devilskiss
	result = "devilskiss"
	required_reagents = list("blood" = 1, "kahlua" = 1, "rum" = 1)
	result_amount = 3

/datum/chemical_reaction/hippiesdelight
	result = "hippiesdelight"
	required_reagents = list("psilocybin" = 1, "gargleblasterlite" = 1)
	result_amount = 2

/datum/chemical_reaction/bananahonk
	result = "bananahonk"
	required_reagents = list("banana" = 1, "cream" = 1, "sugar" = 1)
	result_amount = 3

/datum/chemical_reaction/silencer
	result = "silencer"
	required_reagents = list("nothing" = 1, "cream" = 1, "sugar" = 1)
	result_amount = 3

/datum/chemical_reaction/driestmartini
	result = "driestmartini"
	required_reagents = list("nothing" = 1, "gin" = 1)
	result_amount = 2

/datum/chemical_reaction/lemonade
	result = "lemonade"
	required_reagents = list("lemonjuice" = 1, "sugar" = 1, "water" = 1)
	result_amount = 3

/datum/chemical_reaction/kiraspecial
	result = "kiraspecial"
	required_reagents = list("orangejuice" = 1, "limejuice" = 1, "sodawater" = 1)
	result_amount = 3

/datum/chemical_reaction/brownstar
	result = "brownstar"
	required_reagents = list("orangejuice" = 2, "cola" = 1)
	result_amount = 3

/datum/chemical_reaction/milkshake
	result = "milkshake"
	required_reagents = list("cream" = 1, "ice" = 2, "milk" = 2)
	result_amount = 5

/datum/chemical_reaction/rewriter
	result = "rewriter"
	required_reagents = list("spacemountainwind" = 1, "coffee" = 1)
	result_amount = 2

/datum/chemical_reaction/suidream
	result = "suidream"
	required_reagents = list("space_up" = 1, "bluecuracao" = 1, "melonliquor" = 1)
	result_amount = 3

/datum/chemical_reaction/luminol
	result = "luminol"
	required_reagents = list("hydrazine" = 2, "carbon" = 2, "ammonia" = 2)
	result_amount = 6

/datum/chemical_reaction/mbr
	result = "machine binding ritual"
	required_reagents = list("coffee" = 1, "carbon" = 1, "sugar" = 1, "ethanol" = 1)
	result_amount = 4
	maximum_temperature = 343
	minimum_temperature = 323

/datum/chemical_reaction/machine_spirit
	result = "machine spirit"
	required_reagents = list("machine binding ritual" = 1, "tramadol" = 1, "blattedin" = 1)
	result_amount = 3
	maximum_temperature = 318
	minimum_temperature = 308

/datum/chemical_reaction/party_drops
	result = "party drops"
	required_reagents = list("grape drops" = 1, "machine spirit" = 1, "ultrasurgeon" = 1)
	result_amount = 3

/datum/chemical_reaction/cherry_drops
	result = "cherry drops"
	required_reagents = list("iron" = 1, "nicotine" = 1, "vodka" = 1)
	result_amount = 3
	maximum_temperature = 333
	minimum_temperature = 303

/datum/chemical_reaction/grape_drops
	result = "grape drops"
	required_reagents = list("nanites" = 1, "cherry drops" = 1, "ethanol" = 1)
	result_amount = 3
	maximum_temperature = 343
	minimum_temperature = 338

/datum/chemical_reaction/pro_surgeon
	result = "prosurgeon"
	required_reagents = list("nicotine" = 1, "sugar" = 2, "tungsten" = 2)
	result_amount = 4

/datum/chemical_reaction/ultra_surgeon
	result = "ultrasurgeon"
	required_reagents = list("prosurgeon" = 3, "noexcutite" = 1)
	result_amount = 4
	maximum_temperature = 263
	minimum_temperature = 243

/datum/chemical_reaction/noexcutite
	result = "noexcutite"
	required_reagents = list("tramadol" = 1, "anti_toxin" = 1)
	maximum_temperature = 150
	minimum_temperature = 120
	result_amount = 2

/datum/chemical_reaction/violence
	result = "violence"
	required_reagents = list("acetone" = 1, "ammonia" = 1, "vodka" = 1)
	result_amount = 6
	maximum_temperature = 423
	minimum_temperature = 393

/datum/chemical_reaction/violence_ultra
	result = "violence ultra"
	required_reagents = list("violence" = 1, "gewaltine" = 1, "tramadol" = 1)
	result_amount = 3
	maximum_temperature = 258
	minimum_temperature = 243

/datum/chemical_reaction/bouncer
	result = "bouncer"
	required_reagents = list("inaprovaline" = 1, "vodka" = 1, "tramadol" = 1)
	result_amount = 3
	maximum_temperature = 333
	minimum_temperature = 303

/datum/chemical_reaction/boxer
	result = "boxer"
	required_reagents = list("bouncer" = 1, "starkellin" = 1, "toxin" = 1)
	result_amount = 3
	maximum_temperature = 328
	minimum_temperature = 323

/datum/chemical_reaction/steady
	result = "steady"
	required_reagents = list("nicotine" = 1, "copper" = 1, "tramadol" = 1)
	result_amount = 4
	maximum_temperature = 338
	minimum_temperature = 323

/datum/chemical_reaction/turbo
	result = "turbo"
	required_reagents = list("steady" = 1, "kelotane" = 1, "pararein" = 1)
	result_amount = 3
	maximum_temperature = 293
	minimum_temperature = 288

/datum/chemical_reaction/menace
	result = "menace"
	required_reagents = list("turbo" = 1, "boxer" = 1, "violence ultra" = 1)
	result_amount = 3
	maximum_temperature = 363
	minimum_temperature = 358

/datum/chemical_reaction/sanguinum
	result = "sanguinum"
	required_reagents = list("bicaridine" = 1, "spaceacillin" = 1, "mercury" = 1)
	result_amount = 3

/datum/chemical_reaction/kyphotorin
	result = "kyphotorin"
	required_reagents = list("peridaxon" = 1, "mutagen" = 1, "clonexadone" = 1)
	result_amount = 3

/datum/chemical_reaction/vomitol
	result = "vomitol"
	required_reagents = list("carbon" = 1, "hclacid" = 1, "acetone" = 1)
	result_amount = 3
	maximum_temperature = 683.14 //So it doesn't form back into vomitol, decompose, and form back again when over decomposition point
	minimum_temperature = 0

/datum/chemical_reaction/arectine
	result = "arectine"
	required_reagents = list("ethanol" = 1, "anti_toxin" = 1, "fuel" = 1)
	result_amount = 3

/datum/chemical_reaction/quickclot
	result = "quickclot"
	required_reagents = list("kelotane" = 1, "clonexadone" = 1)
	result_amount = 2
	catalysts = list("plasma" = 1)

/datum/chemical_reaction/ossisine
	result = "ossisine"
	required_reagents = list("stoxin" = 1, "clonexadone" = 1, "bicaridine" = 1)
	result_amount = 3

/datum/chemical_reaction/instant_ice
	result = "instant_ice"
	required_reagents = list("hydrazine" = 1, "acetone" = 1, "sodiumchloride" = 1)
	result_amount = 3

/datum/chemical_reaction/instant_ice_with_water
	result = "water"
	supports_decomposition_by_electrolysis = FALSE
	required_reagents = list("instant_ice" = 3, "water" = 3)
	result_amount = 4


/datum/chemical_reaction/instant_ice_with_water/on_reaction(datum/reagents/holder, var/created_volume)
	..()
	holder.chem_temp = max(223, holder.chem_temp - abs(holder.chem_temp - 223) * created_volume/holder.total_volume) // if someone actually wants to do some physics here they are welcome
	return 0

/datum/chemical_reaction/detox
	result = "detox"
	required_reagents = list("serotrotium" = 1, "inaprovaline" = 3)
	result_amount = 4
	maximum_temperature = INFINITY
	minimum_temperature = 363

/datum/chemical_reaction/polystem
	result = "polystem"
	required_reagents = list("pacid" = 1, "iron" = 1, "potassium" = 3)
	result_amount = 5
	maximum_temperature = 168
	minimum_temperature = 124

/datum/chemical_reaction/purger
	result = "purger"
	required_reagents = list("mindbreaker" = 1, "anti_toxin" = 3)
	result_amount = 4
	maximum_temperature = INFINITY
	minimum_temperature = 363

/datum/chemical_reaction/addictol
	result = "addictol"
	required_reagents = list("mercury" = 2, "purger" = 2, "impedrezene" = 2)
	result_amount = 3

/datum/chemical_reaction/aminazine
	result = "aminazine"
	required_reagents = list("purger" = 1, "alkysine" = 1)
	result_amount = 2

/datum/chemical_reaction/haloperidol
	result = "haloperidol"
	required_reagents = list("anti_toxin" = 2, "leporazine" = 1)
	result_amount = 3
	maximum_temperature = 340
	minimum_temperature = 290

/datum/chemical_reaction/ethanol
	result = "ethanol"
	required_reagents = list("water" = 3, "sugar" = 1)
	result_amount = 4
	catalysts = list("enzyme" = 5)
	maximum_temperature = INFINITY
	minimum_temperature = 363

/datum/chemical_reaction/adrenaline
	result = "adrenaline"
	required_reagents = list("blood" = 3, "dexalin" = 1)
	result_amount = 4
	maximum_temperature = INFINITY
	minimum_temperature = 373

/datum/chemical_reaction/carbon
	result = "carbon"
	required_reagents = list("woodpulp" = 3)
	result_amount = 2
	maximum_temperature = INFINITY
	minimum_temperature = 373

/datum/chemical_reaction/cyanide
	result = "cyanide"
	required_reagents = list("toxin" = 5, "mindbreaker" = 3, "fuhrerole" = 2)
	result_amount = 2
	maximum_temperature = 33
	minimum_temperature = 10

/datum/chemical_reaction/serotrotium
	result = "serotrotium"
	required_reagents = list("blood" = 5, "psilocybin" = 1)
	catalysts = list("nutriment" = 5)
	result_amount = 4
	maximum_temperature = 273
	minimum_temperature = 203

/datum/chemical_reaction/oil
	result = "oil"
	required_reagents = list("fuel" = 1, "carbon" = 1, "ethanol" = 1)
	result_amount = 3
	maximum_temperature = INFINITY
	minimum_temperature = 480

/datum/chemical_reaction/plasticide
	result = "plasticide"
	required_reagents = list("oil" = 1, "ethanol" = 1, "silicon" = 1)
	result_amount = 3
	maximum_temperature = 270
	minimum_temperature = 0

/datum/chemical_reaction/glue
	result = "glue"
	required_reagents = list("plasticide" = 1, "ethanol" = 1, "carbon" = 1)
	result_amount = 3
	maximum_temperature = INFINITY
	minimum_temperature = 363

/datum/chemical_reaction/eznutrient
	result = "eznutrient"
	required_reagents = list("ammonia" = 1, "carbon" = 3)
	result_amount = 4

/datum/chemical_reaction/left4zed
	result = "left4zed"
	required_reagents = list("nutriment" = 1, "radium" = 3)
	result_amount = 4

/datum/chemical_reaction/robustharvest
	result = "robustharvest"
	required_reagents = list("eznutrient" = 1, "sugar" = 3, "carbon" = 3)
	result_amount = 7

/datum/chemical_reaction/arad
	result = "arad nanites"
	required_reagents = list("nanites" = 1, "arithrazine" = 1)
	result_amount = 1

/datum/chemical_reaction/implant_medics
	result = "implant nanites"
	required_reagents = list("nanites" = 1, "aluminum" = 1)
	result_amount = 1

/datum/chemical_reaction/nantidotes
	result = "nantidotes"
	required_reagents = list("nanites" = 1, "haloperidol" = 1)
	result_amount = 1

/datum/chemical_reaction/nanosymbiotes
	result = "nanosymbiotes"
	required_reagents = list("nanites" = 1, "peridaxon" = 1)
	result_amount = 1

/datum/chemical_reaction/oxyrush
	result = "oxyrush"
	required_reagents = list("nanites" = 1, "dexalin" = 1)
	result_amount = 1

/datum/chemical_reaction/trauma_control_system
	result = "trauma_control_system"
	required_reagents = list("nanites" = 1, "bicaridine" = 1)
	result_amount = 1

/datum/chemical_reaction/nanopurgers
	result = "nanopurgers"
	required_reagents = list("nanites" = 1, "vomitol" = 1)
	result_amount = 1

/datum/chemical_reaction/cbu
	result = "cbu"
	required_reagents = list("uncap nanites" = 1, "party drops" = 1)
	result_amount = 1

/datum/chemical_reaction/cbc
	result = "cbc"
	required_reagents = list("uncap nanites" = 1, "menace" = 1)
	result_amount = 1

/datum/chemical_reaction/nanohands
	result = "nanohands"
	required_reagents = list("uncap nanites" = 1, "sterilizine" = 1)
	result_amount = 1

/datum/chemical_reaction/nanovoice
	result = "nanovoice"
	required_reagents = list("uncap nanites" = 1, "synaptizine" = 1)
	result_amount = 1

/datum/chemical_reaction/rejuvenating_agent
	result = "rejuvenating_agent"
	required_reagents = list("cleaner" = 2, "pacid" = 1, "sulfur" = 1)
	result_amount = 2

/datum/chemical_reaction/roachbeer
	result = "roachbeer"
	required_reagents = list("water" = 2, "diplopterum" = 1, "fuel" = 1, "beer" = 1)
	result_amount = 1

/datum/chemical_reaction/kaiserbeer
	result = "kaiserbeer"
	required_reagents = list("fuhrerole" = 1, "kaiseraurum" = 1, "roachbeer" = 2)
	result_amount = 2

/* Other */

/datum/chemical_reaction/protein_shake
	result = "protein_shake"
	required_reagents = list("milk" = 1, "protein" = 1)
	result_amount = 2

/datum/chemical_reaction/suppressital
	result = "suppressital"
	required_reagents = list("blood" = 1, "citalopram" = 1)
	result_amount = 2
	maximum_temperature = 12.7
	minimum_temperature = 7.7

/* FBP "medicine" */

/datum/chemical_reaction/fbp_repair
	result = "fbp_repair"
	required_reagents = list("nanites" = 1, "silicon" = 1)
	result_amount = 2

/* Uncomment when CE_MECH_REPLENISH has a use
/datum/chemical_reaction/fbp_replenish
	result = "fbp_replenish"
	required_reagents = list("nanites" = 1, "oil" = 1)
	result_amount = 2
*/
