
//Chemical Reactions - Initialises all /datum/chemical_reaction into a list
// It is filtered into69ultiple lists within a list.
// For example:
// chemical_reaction_list69"plasma"69 is a list of all reactions relating to plasma
//69ote that entries in the list are69OT duplicated. So if a reaction pertains to
//69ore than one chemical it will still only appear in only one of the sublists.
/proc/initialize_chemical_reactions()
	var/paths = typesof(/datum/chemical_reaction) - /datum/chemical_reaction
	GLOB.chemical_reactions_list = list()

	for(var/path in paths)
		var/datum/chemical_reaction/D =69ew path()
		for(var/id in D.re69uired_reagents)
			if(!is_reagent_with_id_exist(id))
				error("recipe 69D.type69 created incorectly,\69re69uired_reagents\69 reagent with id \"69id69\" does69ot exist.")
		for(var/id in D.catalysts)
			if(!is_reagent_with_id_exist(id))
				error("recipe 69D.type69 created incorectly,\69catalysts\69 reagent with id 69id69 does69ot exist.")
		for(var/id in D.inhibitors)
			if(!is_reagent_with_id_exist(id))
				error("recipe 69D.type69 created incorectly,\69inhibitors\69 reagent with id 69id69 does69ot exist.")
		for(var/id in D.byproducts)
			if(!is_reagent_with_id_exist(id))
				error("recipe 69D.type69 created incorectly,\69byproducts\69 reagent with id 69id69 does69ot exist.")
		if(D.re69uired_reagents && D.re69uired_reagents.len)
			if(D.result)
				if(!GLOB.chemical_reactions_list_by_result69D.result69)
					GLOB.chemical_reactions_list_by_result69D.result69 = list()
				GLOB.chemical_reactions_list_by_result69D.result69 += D
			var/reagent_id = D.re69uired_reagents69169
			if(!GLOB.chemical_reactions_list69reagent_id69)
				GLOB.chemical_reactions_list69reagent_id69 = list()
			GLOB.chemical_reactions_list69reagent_id69 += D

//helper that ensures the reaction rate holds after iterating
//Ex. REACTION_RATE(0.3)69eans that 30% of the reagents will react each chemistry tick (~2 seconds by default).
#define REACTION_RATE(rate) (1 - (1-rate)**(1/PROCESS_REACTION_ITER))

//helper to define reaction rate in terms of half-life
//Ex.
//HALF_LIFE(0) -> Reaction completes immediately (default chems)
//HALF_LIFE(1) -> Half of the reagents react immediately, the rest over the following ticks.
//HALF_LIFE(2) -> Half of the reagents are consumed after 2 chemistry ticks.
//HALF_LIFE(3) -> Half of the reagents are consumed after 3 chemistry ticks.
#define HALF_LIFE(ticks) (ticks? 1 - (0.5)**(1/(ticks*PROCESS_REACTION_ITER)) : 1)

/datum/chemical_reaction
	var/result =69ull
	var/list/re69uired_reagents = list()
	var/list/catalysts = list()
	var/list/inhibitors = list()
	var/result_amount = 0
	var/list/byproducts= list()

	//how far the reaction proceeds each time it is processed. Used with either REACTION_RATE or HALF_LIFE69acros.
	var/reaction_rate = HALF_LIFE(0)

	//if less than 1, the reaction will be inhibited if the ratio of products/reagents is too high.
	//0.5 = 50% yield -> reaction will only proceed halfway until products are removed.
	var/yield = 1

	// Reaction thermal re69uirements
	var/maximum_temperature = INFINITY
	var/minimum_temperature = 0
	var/thermal_product // Heat generated by the reaction

	var/rotation_re69uired = FALSE

	// if true then chemical can be decomposed to initial reagents
	var/supports_decomposition_by_electrolysis = TRUE

	//If limits on reaction rate would leave less than this amount of any reagent (adjusted by the reaction ratios),
	//the reaction goes to completion. This is to prevent reactions from going on forever with tiny reagent amounts.
	var/min_reaction = 2

	var/mix_message = "The solution begins to bubble."
	var/reaction_sound = 'sound/effects/bubbles.ogg'

	var/list/re69uire_containers = list() // This reaction will only occure in these containers(Or their subtypes).
	var/list/blacklist_containers = list() // This reaction will69ot occure in these containers(Or their subtypes).

	var/log_is_important = 0 // If this reaction should be considered important for logging. Important recipes69essage admins when69ixed,69on-important ones just log to file.

/datum/chemical_reaction/proc/can_happen(datum/reagents/holder)
	//check that all the re69uired reagents are present
	if(!holder.has_all_reagents(re69uired_reagents))
		return FALSE

	//check that all the re69uired catalysts are present in the re69uired amount
	if(!holder.has_all_reagents(catalysts))
		return FALSE

	//check that69one of the inhibitors are present in the re69uired amount
	if(holder.has_any_reagent(inhibitors))
		return FALSE

	if(re69uire_containers.len && !is_type_in_list(holder.my_atom, re69uire_containers))
		return FALSE

	if(blacklist_containers.len && is_type_in_list(holder.my_atom, blacklist_containers))
		return FALSE

	var/temperature = holder.chem_temp
	if(temperature <69inimum_temperature || temperature >69aximum_temperature)
		return FALSE

	if(rotation_re69uired && !holder.rotating)
		return FALSE

	return TRUE

/datum/chemical_reaction/proc/calc_reaction_progress(var/datum/reagents/holder,69ar/reaction_limit)
	var/progress = reaction_limit * reaction_rate //simple exponential progression

	//calculate yield
	if(1-yield > 0.001) //if yield ratio is big enough just assume it goes to completion
		/*
			Determine the69ax amount of product by applying the yield condition:
			(max_product/result_amount) / reaction_limit == yield/(1-yield)

			We69ake use of the fact that:
			reaction_limit = (holder.get_reagent_amount(reactant) / re69uired_reagents69reactant69) of the limiting reagent.
		*/
		var/yield_ratio = yield/(1-yield)
		var/max_product = yield_ratio * reaction_limit * result_amount //rearrange to obtain69ax_product
		var/yield_limit =69ax(0,69ax_product - holder.get_reagent_amount(result))/result_amount

		progress =69in(progress, yield_limit) //apply yield limit

	//apply69in reaction progress - wasn't sure if this should go before or after applying yield
	//I guess people can just have their69iniscule reactions go to completion regardless of yield.
	for(var/reactant in re69uired_reagents)
		var/remainder = holder.get_reagent_amount(reactant) - progress*re69uired_reagents69reactant69
		if(remainder <=69in_reaction*re69uired_reagents69reactant69)
			progress = reaction_limit
			break

	return progress

// This proc returns a list of all reagents it wants to use; if the holder has several reactions that use the same reagent, it will split the reagent evenly between them
/datum/chemical_reaction/proc/get_used_reagents()
	. = list()
	for(var/reagent in re69uired_reagents)
		. += reagent

/datum/chemical_reaction/proc/process(datum/reagents/holder)
	//determine how far the reaction can proceed
	var/list/reaction_limits = list()
	for(var/reactant in re69uired_reagents)
		reaction_limits += holder.get_reagent_amount(reactant) / re69uired_reagents69reactant69

	//determine how far the reaction proceeds
	var/reaction_limit =69in(reaction_limits)
	var/progress_limit = calc_reaction_progress(holder, reaction_limit)

	var/reaction_progress =69in(reaction_limit, progress_limit) //no69atter what, the reaction progress cannot exceed the stoichiometric limit.

	//need to obtain the69ew reagent's data before anything is altered
	var/data = send_data(holder, reaction_progress)

	//remove the reactants
	for(var/reactant in re69uired_reagents)
		var/amt_used = re69uired_reagents69reactant69 * reaction_progress
		holder.remove_reagent(reactant, amt_used, safety = 1)

	//add the product
	var/amt_produced = result_amount * reaction_progress
	if(result)
		holder.add_reagent(result, amt_produced, data, safety = 1)

	on_reaction(holder, amt_produced)

	return reaction_progress

//called when a reaction processes
/datum/chemical_reaction/proc/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	if(thermal_product)
		holder.chem_temp += thermal_product
	var/datum/reagents/to_splash =69ew()
	to_splash.maximum_volume = INFINITY
	//well i'll69ever test this cause there is69o recipes with byproducts, so if YOU, yes you, the one who decided to add some, its up to you to fix this
	if(byproducts.len)
		for(var/i = 1 to created_volume/result_amount) // this to evenly fill holder
			for(var/id in byproducts)
				if(holder.get_free_space() > byproducts69id69)
					holder.add_reagent(id, byproducts69id69, safety = 1)
				else
					to_splash.add_reagent(id, byproducts69id69, safety = 1)
	if(to_splash.total_volume)
		to_splash.handle_reactions()
		to_splash.splash(get_turf(holder.my_atom), to_splash.total_volume, 1, FALSE, to_splash.total_volume, to_splash.total_volume)
		69del(to_splash)


//called after processing reactions, if they occurred
/datum/chemical_reaction/proc/post_reaction(var/datum/reagents/holder)
	var/atom/container = holder.my_atom
	if(mix_message && container && !ismob(container))
		var/turf/T = get_turf(container)
		var/list/seen =69iewers(4, T)
		for(var/mob/M in seen)
			M.show_message(SPAN_NOTICE("\icon69container69 69mix_message69"), 1)
		playsound(T, reaction_sound, 80, 1)

//obtains any special data that will be provided to the reaction products
//this is called just before reactants are removed.
/datum/chemical_reaction/proc/send_data(var/datum/reagents/holder,69ar/reaction_limit)
	return69ull

// UI data used by chemical catalog
/datum/chemical_reaction/ui_data()
	var/list/dat = list()
	if(re69uired_reagents)
		dat69"reagents"69 = list()
		for(var/id in re69uired_reagents)
			dat69"reagents"69 += list(list("type" = get_reagent_type_by_id(id), "reagent" = get_reagent_name_by_id(id), "parts" = "69re69uired_reagents69id6969 part\s"))
	if(catalysts)
		dat69"catalyst"69 = list()
		for(var/id in catalysts)
			dat69"catalyst"69 += list(list("type" = get_reagent_type_by_id(id), "reagent" = get_reagent_name_by_id(id), "units" = catalysts69id69))

	dat69"minimum_temperature"69 =69inimum_temperature
	if(maximum_temperature != INFINITY)
		dat69"maximum_temperature"69 =69aximum_temperature

	dat69"result_amount"69 = "69result_amount69 part\s"
	return dat
/* Common reactions */

/datum/chemical_reaction/inaprovaline
	result = "inaprovaline"
	re69uired_reagents = list("acetone" = 1, "carbon" = 1, "sugar" = 1)
	result_amount = 3

/datum/chemical_reaction/dylovene
	result = "anti_toxin"
	re69uired_reagents = list("silicon" = 1, "potassium" = 1, "ammonia" = 1)
	result_amount = 3

/datum/chemical_reaction/tramadol
	result = "tramadol"
	re69uired_reagents = list("paracetamol" = 1, "sugar" = 1, "water" = 1)
	result_amount = 3

/datum/chemical_reaction/paracetamol
	result = "paracetamol"
	re69uired_reagents = list("inaprovaline" = 1, "ethanol" = 1, "acetone" = 1)
	result_amount = 3

/datum/chemical_reaction/oxycodone
	result = "oxycodone"
	re69uired_reagents = list("ethanol" = 1, "tramadol" = 1)
	catalysts = list("plasma" = 5)
	result_amount = 1

/datum/chemical_reaction/toxin
	result = "toxin"
	re69uired_reagents = list("ammonia" = 1, "mercury" = 1, "ethanol" = 1)
	catalysts = list("plasma" = 5)
	result_amount = 3

/datum/chemical_reaction/sterilizine
	result = "sterilizine"
	re69uired_reagents = list("ethanol" = 1, "anti_toxin" = 1, "hclacid" = 1)
	result_amount = 3

/datum/chemical_reaction/silicate
	result = "silicate"
	re69uired_reagents = list("aluminum" = 1, "silicon" = 1, "acetone" = 1)
	result_amount = 3

/datum/chemical_reaction/mutagen
	result = "mutagen"
	re69uired_reagents = list("radium" = 1, "phosphorus" = 1, "hclacid" = 1)
	result_amount = 3

/datum/chemical_reaction/thermite
	result = "thermite"
	re69uired_reagents = list("aluminum" = 1, "iron" = 1, "acetone" = 1)
	result_amount = 3

/datum/chemical_reaction/space_drugs
	result = "space_drugs"
	re69uired_reagents = list("mercury" = 1, "sugar" = 1, "lithium" = 1)
	result_amount = 3

/datum/chemical_reaction/nicotine
    result = "nicotine"
    re69uired_reagents = list("toxin" = 1, "carbon" = 1, "capsaicin" = 1, "mercury" = 1)
    result_amount = 8

/datum/chemical_reaction/lube
	result = "lube"
	re69uired_reagents = list("water" = 1, "silicon" = 1, "acetone" = 1)
	result_amount = 4

/datum/chemical_reaction/pacid
	result = "pacid"
	re69uired_reagents = list("sacid" = 1, "hclacid" = 1, "potassium" = 1)
	result_amount = 3

/datum/chemical_reaction/synaptizine
	result = "synaptizine"
	re69uired_reagents = list("sugar" = 1, "lithium" = 1, "water" = 1)
	result_amount = 3

/datum/chemical_reaction/hyronalin
	result = "hyronalin"
	re69uired_reagents = list("radium" = 1, "anti_toxin" = 1)
	result_amount = 2

/datum/chemical_reaction/arithrazine
	result = "arithrazine"
	re69uired_reagents = list("hyronalin" = 1, "hydrazine" = 1)
	result_amount = 2

/datum/chemical_reaction/impedrezene
	result = "impedrezene"
	re69uired_reagents = list("mercury" = 1, "acetone" = 1, "sugar" = 1)
	result_amount = 2

/datum/chemical_reaction/kelotane
	result = "kelotane"
	re69uired_reagents = list("silicon" = 1, "carbon" = 1)
	result_amount = 2
	log_is_important = 1

/datum/chemical_reaction/peridaxon
	result = "peridaxon"
	re69uired_reagents = list("bicaridine" = 2, "clonexadone" = 2)
	catalysts = list("plasma" = 5)
	result_amount = 2

/datum/chemical_reaction/virus_food
	result = "virusfood"
	re69uired_reagents = list("water" = 1, "milk" = 1)
	result_amount = 5

/datum/chemical_reaction/leporazine
	result = "leporazine"
	re69uired_reagents = list("silicon" = 1, "copper" = 1)
	catalysts = list("plasma" = 5)
	result_amount = 2

/datum/chemical_reaction/cryptobiolin
	result = "cryptobiolin"
	re69uired_reagents = list("potassium" = 1, "acetone" = 1, "sugar" = 1)
	result_amount = 3

/datum/chemical_reaction/tricordrazine
	result = "tricordrazine"
	re69uired_reagents = list("inaprovaline" = 1, "anti_toxin" = 1)
	result_amount = 2

/datum/chemical_reaction/alkysine
	result = "alkysine"
	re69uired_reagents = list("hclacid" = 1, "ammonia" = 1, "anti_toxin" = 1)
	result_amount = 2

/datum/chemical_reaction/dexalin
	result = "dexalin"
	re69uired_reagents = list("acetone" = 2, "plasma" = 0.1)
	catalysts = list("plasma" = 1)
	inhibitors = list("water" = 1) //69esses with cryox
	result_amount = 1

/datum/chemical_reaction/dermaline
	result = "dermaline"
	re69uired_reagents = list("acetone" = 1, "phosphorus" = 1, "kelotane" = 1)
	result_amount = 3

/datum/chemical_reaction/dexalinp
	result = "dexalinp"
	re69uired_reagents = list("dexalin" = 1, "carbon" = 1, "iron" = 1)
	result_amount = 3

/datum/chemical_reaction/bicaridine
	result = "bicaridine"
	re69uired_reagents = list("inaprovaline" = 2, "blattedin" = 1)
	inhibitors = list("sugar" = 1) //69esses up with inaprovaline
	result_amount = 3
/datum/chemical_reaction/meralyne
	result = "meralyne"
	re69uired_reagents = list("hyperzine" = 1, "blattedin" = 2, "tramadol" = 1)
	result_amount = 2

/datum/chemical_reaction/hyperzine
	result = "hyperzine"
	re69uired_reagents = list("sugar" = 1, "blattedin" = 1, "sulfur" = 1)
	result_amount = 3

/datum/chemical_reaction/ryetalyn
	result = "ryetalyn"
	re69uired_reagents = list("arithrazine" = 1, "carbon" = 1)
	result_amount = 2
/datum/chemical_reaction/negative_ling
	result = "negativeling"
	re69uired_reagents = list("ryetalyn" = 1, "carbon" = 1)
	result_amount = 1
	maximum_temperature = INFINITY
	minimum_temperature = 400

/datum/chemical_reaction/positive_ling
	result = "positiveling"
	re69uired_reagents = list("negativeling" = 1, "blood" = 1)
	result_amount = 1
	maximum_temperature = INFINITY
	minimum_temperature = 700

/datum/chemical_reaction/positive_ling/can_happen(datum/reagents/holder)
	if(..())
		var/list/blood_data = holder.get_data("blood")
		if(blood_data69"carrion"69)
			return TRUE

	return FALSE

/datum/chemical_reaction/cryoxadone
	result = "cryoxadone"
	re69uired_reagents = list("dexalin" = 1, "water" = 1, "acetone" = 1)
	result_amount = 3

/datum/chemical_reaction/clonexadone
	result = "clonexadone"
	re69uired_reagents = list("cryoxadone" = 1, "sodium" = 1, "plasma" = 0.1)
	catalysts = list("plasma" = 5)
	result_amount = 2

/datum/chemical_reaction/spaceacillin
	result = "spaceacillin"
	re69uired_reagents = list("cryptobiolin" = 1, "inaprovaline" = 1)
	result_amount = 2

/datum/chemical_reaction/spaceacillin_mold
	result = "spaceacillin"
	re69uired_reagents = list("mold" = 1, "sugar" = 1, "acetone" = 1)
	result_amount = 6

/datum/chemical_reaction/imidazoline
	result = "imidazoline"
	re69uired_reagents = list("carbon" = 1, "hydrazine" = 1, "anti_toxin" = 1)
	result_amount = 2

/datum/chemical_reaction/ethylredoxrazine
	result = "ethylredoxrazine"
	re69uired_reagents = list("acetone" = 1, "anti_toxin" = 1, "carbon" = 1)
	result_amount = 3

/datum/chemical_reaction/soporific
	result = "stoxin"
	re69uired_reagents = list("chloralhydrate" = 1, "sugar" = 4)
	inhibitors = list("phosphorus") //69esses with the smoke
	result_amount = 5

/datum/chemical_reaction/chloralhydrate
	result = "chloralhydrate"
	re69uired_reagents = list("ethanol" = 1, "hclacid" = 3, "water" = 1)
	result_amount = 1

/datum/chemical_reaction/potassium_chloride
	result = "potassium_chloride"
	re69uired_reagents = list("sodiumchloride" = 1, "potassium" = 1)
	result_amount = 2

/datum/chemical_reaction/potassium_chlorophoride
	result = "potassium_chlorophoride"
	re69uired_reagents = list("potassium_chloride" = 1, "plasma" = 1, "chloralhydrate" = 1)
	result_amount = 4

/datum/chemical_reaction/zombiepowder
	result = "zombiepowder"
	re69uired_reagents = list("carpotoxin" = 5, "stoxin" = 5, "copper" = 5)
	result_amount = 2

/datum/chemical_reaction/mindbreaker
	result = "mindbreaker"
	re69uired_reagents = list("silicon" = 1, "hydrazine" = 1, "anti_toxin" = 1)
	result_amount = 3

/datum/chemical_reaction/mindwipe
	result = "mindwipe"
	re69uired_reagents = list("mindbreaker" = 1, "anti_toxin" = 1, "ethanol" = 1)
	catalysts = list("whiskey" = 5)
	result_amount = 1

/datum/chemical_reaction/lipozine
	result = "lipozine"
	re69uired_reagents = list("sodiumchloride" = 1, "ethanol" = 1, "radium" = 1)
	result_amount = 3

/datum/chemical_reaction/surfactant
	result = "surfactant"
	re69uired_reagents = list("hydrazine" = 2, "carbon" = 2, "sacid" = 1)
	result_amount = 5

/datum/chemical_reaction/diethylamine
	result = "diethylamine"
	re69uired_reagents = list ("ammonia" = 1, "ethanol" = 1)
	result_amount = 2

/datum/chemical_reaction/space_cleaner
	result = "cleaner"
	re69uired_reagents = list("ammonia" = 1, "water" = 1)
	result_amount = 2

/datum/chemical_reaction/plantbgone
	result = "plantbgone"
	re69uired_reagents = list("toxin" = 1, "water" = 4)
	result_amount = 5

/datum/chemical_reaction/foaming_agent
	result = "foaming_agent"
	re69uired_reagents = list("lithium" = 1, "hydrazine" = 1)
	result_amount = 1

/datum/chemical_reaction/glycerol
	result = "glycerol"
	re69uired_reagents = list("cornoil" = 3, "sacid" = 1)
	result_amount = 1

/datum/chemical_reaction/sodiumchloride
	result = "sodiumchloride"
	re69uired_reagents = list("sodium" = 1, "hclacid" = 1)
	result_amount = 2

/datum/chemical_reaction/condensedcapsaicin
	result = "condensedcapsaicin"
	re69uired_reagents = list("capsaicin" = 3)
	result_amount = 1
	maximum_temperature = INFINITY
	minimum_temperature = 373

/datum/chemical_reaction/coolant
	result = "coolant"
	re69uired_reagents = list("tungsten" = 1, "acetone" = 1, "water" = 1)
	result_amount = 3
	log_is_important = 1

/datum/chemical_reaction/rezadone
	result = "rezadone"
	re69uired_reagents = list("carpotoxin" = 1, "cryptobiolin" = 1, "copper" = 1)
	result_amount = 3

/datum/chemical_reaction/lexorin
	result = "lexorin"
	re69uired_reagents = list("plasma" = 1, "hydrazine" = 1, "ammonia" = 1)
	result_amount = 3

/datum/chemical_reaction/methylphenidate
	result = "methylphenidate"
	re69uired_reagents = list("mindbreaker" = 1, "hydrazine" = 1)
	result_amount = 3

/datum/chemical_reaction/citalopram
	result = "citalopram"
	re69uired_reagents = list("mindbreaker" = 1, "carbon" = 1)
	result_amount = 3


/datum/chemical_reaction/paroxetine
	result = "paroxetine"
	re69uired_reagents = list("mindbreaker" = 1, "acetone" = 1, "inaprovaline" = 1)
	result_amount = 3

/* Centrifuge */

/datum/chemical_reaction/curing
	result = "antibodies"
	re69uired_reagents = list("blood" = 1)
	result_amount = 1
	reaction_rate = REACTION_RATE(0.3)
	rotation_re69uired = TRUE
	supports_decomposition_by_electrolysis = FALSE
	mix_message =69ull

/datum/chemical_reaction/curing/send_data(datum/reagents/T)
	return list("antibodies" = T.get_data("blood")69"antibodies"69)

/* Solidification */

/datum/chemical_reaction/plasmasolidification
	result =69ull
	re69uired_reagents = list("iron" = 5, "frostoil" = 5, "plasma" = 20)
	result_amount = 1

/datum/chemical_reaction/plasmasolidification/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	new /obj/item/stack/material/plasma(get_turf(holder.my_atom), created_volume)
	return

/datum/chemical_reaction/goldsolidification
	result =69ull
	re69uired_reagents = list("iron" = 5, "frostoil" = 5, "gold" = 20)
	result_amount = 1

/datum/chemical_reaction/goldsolidification/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	new /obj/item/stack/material/gold(get_turf(holder.my_atom), created_volume)
	return

/datum/chemical_reaction/uraniumsolidification
	result =69ull
	re69uired_reagents = list("iron" = 5, "frostoil" = 5, "uranium" = 20)
	result_amount = 1

/datum/chemical_reaction/uraniumsolidification/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	new /obj/item/stack/material/uranium(get_turf(holder.my_atom), created_volume)
	return

/datum/chemical_reaction/silversolidification
	result =69ull
	re69uired_reagents = list("iron" = 5, "frostoil" = 5, "silver" = 20)
	result_amount = 1

/datum/chemical_reaction/silversolidification/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	new /obj/item/stack/material/silver(get_turf(holder.my_atom), created_volume)
	return

/datum/chemical_reaction/platinumsolidification
	result =69ull
	re69uired_reagents = list("iron" = 5, "frostoil" = 5, "platinum" = 20)
	result_amount = 1

/datum/chemical_reaction/platinumsolidification/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	new /obj/item/stack/material/platinum(get_turf(holder.my_atom), created_volume)
	return

/datum/chemical_reaction/plastication
	result =69ull
	re69uired_reagents = list("pacid" = 1, "plasticide" = 2)
	result_amount = 1

/datum/chemical_reaction/plastication/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	new /obj/item/stack/material/plastic(get_turf(holder.my_atom), created_volume)
	return

/* Grenade reactions */

/datum/chemical_reaction/explosion_potassium
	result =69ull
	re69uired_reagents = list("water" = 1, "potassium" = 1)
	result_amount = 2
	mix_message =69ull

/datum/chemical_reaction/explosion_potassium/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/datum/effect/effect/system/reagents_explosion/e =69ew()
	e.set_up(round (created_volume/45, 1), holder.my_atom, 0, 0) // 600/45 = 13.3 , 13/3 = 4-3 light-range , slightly weaker than a cracker.
	if(isliving(holder.my_atom))
		e.amount *= 0.5
		var/mob/living/L = holder.my_atom
		if(L.stat != DEAD)
			if(e.amount >= 6)
				L.gib()
			e.amount *= 1.5
	e.start()
	holder.clear_reagents()
	return

/datum/chemical_reaction/flash_powder
	result =69ull
	re69uired_reagents = list("aluminum" = 1, "potassium" = 1, "sulfur" = 1 )
	result_amount =69ull

/datum/chemical_reaction/flash_powder/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)
	var/datum/effect/effect/system/spark_spread/s =69ew /datum/effect/effect/system/spark_spread
	s.set_up(2, 1, location)
	s.start()
	for(var/mob/living/carbon/M in69iewers(world.view, location))
		switch(get_dist(M, location))
			if(0 to 3)
				if(hasvar(M, "glasses"))
					if(istype(M:glasses, /obj/item/clothing/glasses/sunglasses))
						continue

				if (M.HUDtech.Find("flash"))
					flick("e_flash",69.HUDtech69"flash"69)
				M.Weaken(15)

			if(4 to 5)
				if(hasvar(M, "glasses"))
					if(istype(M:glasses, /obj/item/clothing/glasses/sunglasses))
						continue

				if (M.HUDtech.Find("flash"))
					flick("e_flash",69.HUDtech69"flash"69)
				M.Stun(5)

/datum/chemical_reaction/emp_pulse
	result =69ull
	re69uired_reagents = list(MATERIAL_URANIUM = 1, "iron" = 1) // Yes, laugh, it's the best recipe I could think of that69akes a little bit of sense
	result_amount = 2

/datum/chemical_reaction/emp_pulse/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)
	// 100 created69olume = 4 heavy range & 7 light range. A few tiles smaller than contractor EMP grandes.
	// 200 created69olume = 8 heavy range & 14 light range. 4 tiles larger than contractor EMP grenades.
	empulse(location, round(created_volume / 24), round(created_volume / 14), 1)
	holder.clear_reagents()
	return

/datum/chemical_reaction/nitroglycerin
	result = "nitroglycerin"
	re69uired_reagents = list("glycerol" = 1, "pacid" = 1, "sacid" = 1)
	result_amount = 2
	log_is_important = 1

/datum/chemical_reaction/nitroglycerin/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/datum/effect/effect/system/reagents_explosion/e =69ew()
	e.set_up(round (created_volume/2, 1), holder.my_atom, 0, 0)
	if(isliving(holder.my_atom))
		e.amount *= 0.5
		var/mob/living/L = holder.my_atom
		if(L.stat!=DEAD)
			e.amount *= 0.5
	e.start()

	holder.clear_reagents()
	return

/datum/chemical_reaction/napalm
	result =69ull
	re69uired_reagents = list("aluminum" = 1, "plasma" = 1, "sacid" = 1 )
	result_amount = 1

/datum/chemical_reaction/napalm/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/turf/location = get_turf(holder.my_atom.loc)
	for(var/turf/simulated/floor/target_tile in range(0,location))
		target_tile.assume_gas("plasma", created_volume, 400+T0C)
		spawn (0) target_tile.hotspot_expose(700, 400)
	holder.del_reagent("napalm")
	return

/datum/chemical_reaction/chemsmoke
	result =69ull
	re69uired_reagents = list("potassium" = 1, "sugar" = 1, "phosphorus" = 1)
	result_amount = 0.4

/datum/chemical_reaction/chemsmoke/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)
	var/datum/effect/effect/system/smoke_spread/chem/S =69ew /datum/effect/effect/system/smoke_spread/chem
	S.attach(location)
	S.set_up(holder, created_volume, 0, location)
	playsound(location, 'sound/effects/smoke.ogg', 50, 1, -3)
	spawn(0)
		S.start()
	holder.clear_reagents()
	return

/datum/chemical_reaction/foam
	result =69ull
	re69uired_reagents = list("surfactant" = 1, "water" = 1)
	result_amount = 2
	mix_message = "The solution69iolently bubbles!"

/datum/chemical_reaction/foam/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)

	for(var/mob/M in69iewers(5, location))
		to_chat(M, SPAN_WARNING("The solution spews out foam!"))

	var/datum/effect/effect/system/foam_spread/s =69ew()
	s.set_up(created_volume, location, holder, 0)
	s.start()
	holder.clear_reagents()
	return

/datum/chemical_reaction/metalfoam
	result =69ull
	re69uired_reagents = list("aluminum" = 3, "foaming_agent" = 1, "pacid" = 1)
	result_amount = 5

/datum/chemical_reaction/metalfoam/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)

	for(var/mob/M in69iewers(5, location))
		to_chat(M, SPAN_WARNING("The solution spews out a69etalic foam!"))

	var/datum/effect/effect/system/foam_spread/s =69ew()
	s.set_up(created_volume, location, holder, 1)
	s.start()
	return

/datum/chemical_reaction/ironfoam
	result =69ull
	re69uired_reagents = list("iron" = 3, "foaming_agent" = 1, "pacid" = 1)
	result_amount = 5

/datum/chemical_reaction/ironfoam/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)

	for(var/mob/M in69iewers(5, location))
		to_chat(M, SPAN_WARNING("The solution spews out a69etalic foam!"))

	var/datum/effect/effect/system/foam_spread/s =69ew()
	s.set_up(created_volume, location, holder, 2)
	s.start()
	return

/* Paint */

/datum/chemical_reaction/red_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_red" = 1)
	result_amount = 5

/datum/chemical_reaction/red_paint/send_data()
	return "#FE191A"

/datum/chemical_reaction/orange_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_orange" = 1)
	result_amount = 5

/datum/chemical_reaction/orange_paint/send_data()
	return "#FFBE4F"

/datum/chemical_reaction/yellow_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_yellow" = 1)
	result_amount = 5

/datum/chemical_reaction/yellow_paint/send_data()
	return "#FDFE7D"

/datum/chemical_reaction/green_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_green" = 1)
	result_amount = 5

/datum/chemical_reaction/green_paint/send_data()
	return "#18A31A"

/datum/chemical_reaction/blue_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_blue" = 1)
	result_amount = 5

/datum/chemical_reaction/blue_paint/send_data()
	return "#247CFF"

/datum/chemical_reaction/purple_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_purple" = 1)
	result_amount = 5

/datum/chemical_reaction/purple_paint/send_data()
	return "#CC0099"

/datum/chemical_reaction/grey_paint //mime
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_grey" = 1)
	result_amount = 5

/datum/chemical_reaction/grey_paint/send_data()
	return "#808080"

/datum/chemical_reaction/brown_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "crayon_dust_brown" = 1)
	result_amount = 5

/datum/chemical_reaction/brown_paint/send_data()
	return "#846F35"

/datum/chemical_reaction/blood_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "blood" = 2)
	result_amount = 5

/datum/chemical_reaction/blood_paint/send_data(var/datum/reagents/T)
	var/t = T.get_data("blood")
	if(t && t69"blood_colour"69)
		return t69"blood_colour"69
	return "#FE191A" // Probably red

/datum/chemical_reaction/milk_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "milk" = 5)
	result_amount = 5

/datum/chemical_reaction/milk_paint/send_data()
	return "#F0F8FF"

/datum/chemical_reaction/orange_juice_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "orangejuice" = 5)
	result_amount = 5

/datum/chemical_reaction/orange_juice_paint/send_data()
	return "#E78108"

/datum/chemical_reaction/tomato_juice_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "tomatojuice" = 5)
	result_amount = 5

/datum/chemical_reaction/tomato_juice_paint/send_data()
	return "#731008"

/datum/chemical_reaction/lime_juice_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "limejuice" = 5)
	result_amount = 5

/datum/chemical_reaction/lime_juice_paint/send_data()
	return "#365E30"

/datum/chemical_reaction/carrot_juice_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "carrotjuice" = 5)
	result_amount = 5

/datum/chemical_reaction/carrot_juice_paint/send_data()
	return "#973800"

/datum/chemical_reaction/berry_juice_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "berryjuice" = 5)
	result_amount = 5

/datum/chemical_reaction/berry_juice_paint/send_data()
	return "#990066"

/datum/chemical_reaction/grape_juice_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "grapejuice" = 5)
	result_amount = 5

/datum/chemical_reaction/grape_juice_paint/send_data()
	return "#863333"

/datum/chemical_reaction/poisonberry_juice_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "poisonberryjuice" = 5)
	result_amount = 5

/datum/chemical_reaction/poisonberry_juice_paint/send_data()
	return "#863353"

/datum/chemical_reaction/watermelon_juice_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "watermelonjuice" = 5)
	result_amount = 5

/datum/chemical_reaction/watermelon_juice_paint/send_data()
	return "#B83333"

/datum/chemical_reaction/lemon_juice_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "lemonjuice" = 5)
	result_amount = 5

/datum/chemical_reaction/lemon_juice_paint/send_data()
	return "#AFAF00"

/datum/chemical_reaction/banana_juice_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "banana" = 5)
	result_amount = 5

/datum/chemical_reaction/banana_juice_paint/send_data()
	return "#C3AF00"

/datum/chemical_reaction/potato_juice_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "potato" = 5)
	result_amount = 5

/datum/chemical_reaction/potato_juice_paint/send_data()
	return "#302000"

/datum/chemical_reaction/carbon_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "carbon" = 1)
	result_amount = 5

/datum/chemical_reaction/carbon_paint/send_data()
	return "#333333"

/datum/chemical_reaction/aluminum_paint
	result = "paint"
	re69uired_reagents = list("plasticide" = 1, "water" = 3, "aluminum" = 1)
	result_amount = 5

/datum/chemical_reaction/aluminum_paint/send_data()
	return "#F0F8FF"

/* Slime cores */

/datum/chemical_reaction/slime
	var/re69uired =69ull

/datum/chemical_reaction/slime/ui_data()
	var/list/dat = ..()
	dat69"re69uired_object"69 = re69uired
	return dat

/datum/chemical_reaction/slime/can_happen(var/datum/reagents/holder)
	if(holder.my_atom && istype(holder.my_atom, re69uired))
		var/obj/item/slime_extract/T = holder.my_atom
		if(T.Uses > 0)
			return ..()
	return 0

/datum/chemical_reaction/slime/on_reaction(var/datum/reagents/holder)
	var/obj/item/slime_extract/T = holder.my_atom
	T.Uses--
	if(T.Uses <= 0)
		T.visible_message("\icon69T69<span class='notice'>\The 69T69's power is consumed in the reaction.</span>")
		T.name = "used slime extract"
		T.desc = "This extract has been used up."

//Grey
/datum/chemical_reaction/slime/spawn
	result =69ull
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/grey

/datum/chemical_reaction/slime/spawn/on_reaction(var/datum/reagents/holder)
	holder.my_atom.visible_message(SPAN_WARNING("Infused with plasma, the core begins to 69uiver and grow, and soon a69ew baby slime emerges from it!"))
	var/mob/living/carbon/slime/S =69ew /mob/living/carbon/slime
	S.loc = get_turf(holder.my_atom)
	..()

/datum/chemical_reaction/slime/monkey
	result =69ull
	re69uired_reagents = list("blood" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/grey

/datum/chemical_reaction/slime/monkey/on_reaction(var/datum/reagents/holder)
	for(var/i = 1, i <= 3, i++)
		var /obj/item/reagent_containers/food/snacks/monkeycube/M =69ew /obj/item/reagent_containers/food/snacks/monkeycube
		M.loc = get_turf(holder.my_atom)
	..()

//Green
/datum/chemical_reaction/slime/mutate
	result = "mutationtoxin"
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/green

//Metal
/datum/chemical_reaction/slime/metal
	result =69ull
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/metal

/datum/chemical_reaction/slime/metal/on_reaction(var/datum/reagents/holder)
	var/obj/item/stack/material/steel/M =69ew /obj/item/stack/material/steel
	M.amount = 15
	M.loc = get_turf(holder.my_atom)
	var/obj/item/stack/material/plasteel/P =69ew /obj/item/stack/material/plasteel
	P.amount = 5
	P.loc = get_turf(holder.my_atom)
	..()

//Gold - removed
/datum/chemical_reaction/slime/crit
	result =69ull
	re69uired_reagents = list("blood" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/gold
	mix_message = "The slime extract begins to69ibrate69iolently!"

/datum/chemical_reaction/slime/crit/on_reaction(var/datum/reagents/holder)
	for(var/i = 1 to 2)
		var/roachcube = pick(subtypesof(/obj/item/reagent_containers/food/snacks/roachcube))
		new roachcube(get_turf(holder.my_atom))
	..()

//Silver
/datum/chemical_reaction/slime/bork
	result =69ull
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/silver

/datum/chemical_reaction/slime/bork/on_reaction(var/datum/reagents/holder)
	var/list/borks = typesof(/obj/item/reagent_containers/food/snacks) - /obj/item/reagent_containers/food/snacks
	playsound(get_turf(holder.my_atom), 'sound/effects/phasein.ogg', 100, 1)
	for(var/mob/living/carbon/human/M in69iewers(get_turf(holder.my_atom),69ull))
		if(M.eyecheck() < FLASH_PROTECTION_MODERATE)
			if (M.HUDtech.Find("flash"))
				flick("e_flash",69.HUDtech69"flash"69)

	for(var/i = 1, i <= 4 + rand(1,2), i++)
		var/chosen = pick(borks)
		var/obj/B =69ew chosen
		if(B)
			B.loc = get_turf(holder.my_atom)
			if(prob(50))
				for(var/j = 1, j <= rand(1, 3), j++)
					step(B, pick(NORTH, SOUTH, EAST, WEST))
	..()

//Blue
/datum/chemical_reaction/slime/frost
	result = "frostoil"
	re69uired_reagents = list("plasma" = 1)
	result_amount = 10
	re69uired = /obj/item/slime_extract/blue

//Dark Blue
/datum/chemical_reaction/slime/freeze
	result =69ull
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/darkblue
	mix_message = "The slime extract begins to69ibrate69iolently!"

/datum/chemical_reaction/slime/freeze/on_reaction(var/datum/reagents/holder)
	..()
	sleep(50)
	playsound(get_turf(holder.my_atom), 'sound/effects/phasein.ogg', 100, 1)
	for(var/mob/living/M in range (get_turf(holder.my_atom), 7))
		M.bodytemperature -= 140
		to_chat(M, SPAN_WARNING("You feel a chill!"))

//Orange
/datum/chemical_reaction/slime/casp
	result = "capsaicin"
	re69uired_reagents = list("blood" = 1)
	result_amount = 10
	re69uired = /obj/item/slime_extract/orange

/datum/chemical_reaction/slime/fire
	result =69ull
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/orange
	mix_message = "The slime extract begins to69ibrate69iolently!"

/datum/chemical_reaction/slime/fire/on_reaction(var/datum/reagents/holder)
	..()
	sleep(50)
	var/turf/location = get_turf(holder.my_atom.loc)
	for(var/turf/simulated/floor/target_tile in range(0, location))
		target_tile.assume_gas("plasma", 25, 1400)
		spawn (0)
			target_tile.hotspot_expose(700, 400)

//Yellow
/datum/chemical_reaction/slime/overload
	result =69ull
	re69uired_reagents = list("blood" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/yellow

/datum/chemical_reaction/slime/overload/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	..()
	empulse(get_turf(holder.my_atom), 3, 7)

/datum/chemical_reaction/slime/cell
	result =69ull
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/yellow

/datum/chemical_reaction/slime/cell/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/obj/item/cell/large/slime/P =69ew /obj/item/cell/large/slime
	P.loc = get_turf(holder.my_atom)

/datum/chemical_reaction/slime/glow
	result =69ull
	re69uired_reagents = list("water" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/yellow
	mix_message = "The contents of the slime core harden and begin to emit a warm, bright light."

/datum/chemical_reaction/slime/glow/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	..()
	var/obj/item/device/slimelight/F =69ew /obj/item/device/slimelight
	F.loc = get_turf(holder.my_atom)

//Purple
/datum/chemical_reaction/slime/psteroid
	result =69ull
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/purple

/datum/chemical_reaction/slime/psteroid/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	..()
	var/obj/item/slimesteroid/P =69ew /obj/item/slimesteroid
	P.loc = get_turf(holder.my_atom)

/datum/chemical_reaction/slime/jam
	result = "slimejelly"
	re69uired_reagents = list("sugar" = 1)
	result_amount = 10
	re69uired = /obj/item/slime_extract/purple

//Dark Purple
/datum/chemical_reaction/slime/plasma
	result =69ull
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/darkpurple

/datum/chemical_reaction/slime/plasma/on_reaction(var/datum/reagents/holder)
	..()
	var/obj/item/stack/material/plasma/P =69ew /obj/item/stack/material/plasma
	P.amount = 10
	P.loc = get_turf(holder.my_atom)

//Red
/datum/chemical_reaction/slime/glycerol
	result = "glycerol"
	re69uired_reagents = list("plasma" = 1)
	result_amount = 8
	re69uired = /obj/item/slime_extract/red

/datum/chemical_reaction/slime/bloodlust
	result =69ull
	re69uired_reagents = list("blood" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/red

/datum/chemical_reaction/slime/bloodlust/on_reaction(var/datum/reagents/holder)
	..()
	for(var/mob/living/carbon/slime/slime in69iewers(get_turf(holder.my_atom),69ull))
		slime.rabid = 1
		slime.visible_message(SPAN_WARNING("The 69slime69 is driven into a frenzy!"))

//Pink
/datum/chemical_reaction/slime/ppotion
	result =69ull
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/pink

/datum/chemical_reaction/slime/ppotion/on_reaction(var/datum/reagents/holder)
	..()
	var/obj/item/slimepotion/P =69ew /obj/item/slimepotion
	P.loc = get_turf(holder.my_atom)

//Black
/datum/chemical_reaction/slime/mutate2
	result = "amutationtoxin"
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/black

//Oil
/datum/chemical_reaction/slime/explosion
	result =69ull
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/oil
	mix_message = "The slime extract begins to69ibrate69iolently!"

/datum/chemical_reaction/slime/explosion/on_reaction(var/datum/reagents/holder)
	..()
	sleep(50)
	explosion(get_turf(holder.my_atom), 1, 3, 6)

//Light Pink
/datum/chemical_reaction/slime/potion2
	result =69ull
	result_amount = 1
	re69uired = /obj/item/slime_extract/lightpink
	re69uired_reagents = list("plasma" = 1)

/datum/chemical_reaction/slime/potion2/on_reaction(var/datum/reagents/holder)
	..()
	var/obj/item/slimepotion2/P =69ew /obj/item/slimepotion2
	P.loc = get_turf(holder.my_atom)

//Adamantine
/datum/chemical_reaction/slime/golem
	result =69ull
	re69uired_reagents = list("plasma" = 1)
	result_amount = 1
	re69uired = /obj/item/slime_extract/adamantine

/datum/chemical_reaction/slime/golem/on_reaction(var/datum/reagents/holder)
	..()
	var/obj/effect/golemrune/Z =69ew /obj/effect/golemrune
	Z.loc = get_turf(holder.my_atom)
	Z.announce_to_ghosts()

/* Food */

/datum/chemical_reaction/tofu
	result =69ull
	re69uired_reagents = list("soymilk" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 1
	blacklist_containers = list(/mob)

/datum/chemical_reaction/tofu/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/tofu(location)

/datum/chemical_reaction/chocolate_bar
	result =69ull
	re69uired_reagents = list("soymilk" = 2, "coco" = 2, "sugar" = 2)
	result_amount = 1
	blacklist_containers = list(/mob)

/datum/chemical_reaction/chocolate_bar/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/chocolatebar(location)

/datum/chemical_reaction/chocolate_bar2
	result =69ull
	re69uired_reagents = list("milk" = 2, "coco" = 2, "sugar" = 2)
	result_amount = 1
	blacklist_containers = list(/mob)

/datum/chemical_reaction/chocolate_bar2/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/chocolatebar(location)

/datum/chemical_reaction/hot_coco
	result = "hot_coco"
	re69uired_reagents = list("water" = 5, "coco" = 1)
	result_amount = 5

/datum/chemical_reaction/soysauce
	result = "soysauce"
	re69uired_reagents = list("soymilk" = 4, "sacid" = 1)
	result_amount = 5

/datum/chemical_reaction/ketchup
	result = "ketchup"
	re69uired_reagents = list("tomatojuice" = 2, "water" = 1, "sugar" = 1)
	result_amount = 4

/datum/chemical_reaction/cheesewheel
	result =69ull
	re69uired_reagents = list("milk" = 40)
	catalysts = list("enzyme" = 5)
	result_amount = 1
	blacklist_containers = list(/mob)

/datum/chemical_reaction/cheesewheel/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/sliceable/cheesewheel(location)

/datum/chemical_reaction/meatball
	result =69ull
	re69uired_reagents = list("protein" = 3, "flour" = 5)
	result_amount = 3
	blacklist_containers = list(/mob)

/datum/chemical_reaction/meatball/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/meatball(location)

/datum/chemical_reaction/dough
	result =69ull
	re69uired_reagents = list("egg" = 3, "flour" = 10)
	result_amount = 1
	blacklist_containers = list(/mob)

/datum/chemical_reaction/dough/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/dough(location)

/datum/chemical_reaction/syntiflesh
	result =69ull
	re69uired_reagents = list("blood" = 5, "clonexadone" = 1)
	result_amount = 1
	blacklist_containers = list(/mob)

/datum/chemical_reaction/syntiflesh/on_reaction(var/datum/reagents/holder,69ar/created_volume)
	var/location = get_turf(holder.my_atom)
	for(var/i = 1, i <= created_volume, i++)
		new /obj/item/reagent_containers/food/snacks/meat/syntiflesh(location)

/datum/chemical_reaction/hot_ramen
	result = "hot_ramen"
	re69uired_reagents = list("water" = 1, "dry_ramen" = 3)
	result_amount = 3

/datum/chemical_reaction/hell_ramen
	result = "hell_ramen"
	re69uired_reagents = list("capsaicin" = 1, "hot_ramen" = 6)
	result_amount = 6

/* Alcohol */

/datum/chemical_reaction/goldschlager
	result = "goldschlager"
	re69uired_reagents = list("vodka" = 10,69ATERIAL_GOLD = 1)
	result_amount = 10

/datum/chemical_reaction/patron
	result = "patron"
	re69uired_reagents = list("te69uilla" = 10,69ATERIAL_SILVER = 1)
	result_amount = 10

/datum/chemical_reaction/bilk
	result = "bilk"
	re69uired_reagents = list("milk" = 1, "beer" = 1)
	result_amount = 2

/datum/chemical_reaction/icetea
	result = "icetea"
	re69uired_reagents = list("ice" = 1, "tea" = 2)
	result_amount = 3

/datum/chemical_reaction/icegreentea
	result = "icegreentea"
	re69uired_reagents = list("ice" = 1, "greentea" = 2)
	result_amount = 3

/datum/chemical_reaction/icecoffee
	result = "icecoffee"
	re69uired_reagents = list("ice" = 1, "coffee" = 2)
	result_amount = 3

/datum/chemical_reaction/nuka_cola
	result = "nuka_cola"
	re69uired_reagents = list(MATERIAL_URANIUM = 1, "cola" = 5)
	result_amount = 5

/datum/chemical_reaction/moonshine
	result = "moonshine"
	re69uired_reagents = list("nutriment" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/grenadine
	result = "grenadine"
	re69uired_reagents = list("berryjuice" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/wine
	result = "wine"
	re69uired_reagents = list("grapejuice" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/pwine
	result = "pwine"
	re69uired_reagents = list("poisonberryjuice" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/melonli69uor
	result = "melonli69uor"
	re69uired_reagents = list("watermelonjuice" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/bluecuracao
	result = "bluecuracao"
	re69uired_reagents = list("orangejuice" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/spacebeer
	result = "beer"
	re69uired_reagents = list("cornoil" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/vodka
	result = "vodka"
	re69uired_reagents = list("potato" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/sake
	result = "sake"
	re69uired_reagents = list("rice" = 10)
	catalysts = list("enzyme" = 5)
	result_amount = 10

/datum/chemical_reaction/kahlua
	result = "kahlua"
	re69uired_reagents = list("coffee" = 5, "sugar" = 5)
	catalysts = list("enzyme" = 5)
	result_amount = 5

/datum/chemical_reaction/gin_tonic
	result = "gintonic"
	re69uired_reagents = list("gin" = 2, "tonic" = 1)
	result_amount = 3

/datum/chemical_reaction/cuba_libre
	result = "cubalibre"
	re69uired_reagents = list("rum" = 2, "cola" = 1)
	result_amount = 3

/datum/chemical_reaction/martini
	result = "martini"
	re69uired_reagents = list("gin" = 2, "vermouth" = 1)
	result_amount = 3

/datum/chemical_reaction/vodkamartini
	result = "vodkamartini"
	re69uired_reagents = list("vodka" = 2, "vermouth" = 1)
	result_amount = 3

/datum/chemical_reaction/white_russian
	result = "whiterussian"
	re69uired_reagents = list("blackrussian" = 2, "cream" = 1)
	result_amount = 3

/datum/chemical_reaction/whiskey_cola
	result = "whiskeycola"
	re69uired_reagents = list("whiskey" = 2, "cola" = 1)
	result_amount = 3

/datum/chemical_reaction/screwdriver
	result = "screwdrivercocktail"
	re69uired_reagents = list("vodka" = 2, "orangejuice" = 1)
	result_amount = 3

/datum/chemical_reaction/bloody_mary
	result = "bloodymary"
	re69uired_reagents = list("vodka" = 2, "tomatojuice" = 3, "limejuice" = 1)
	result_amount = 6

/datum/chemical_reaction/gargle_blaster
	result = "gargleblaster"
	re69uired_reagents = list("vodka" = 2, "gin" = 1, "whiskey" = 1, "cognac" = 1, "limejuice" = 1)
	result_amount = 6

/datum/chemical_reaction/brave_bull
	result = "bravebull"
	re69uired_reagents = list("te69uilla" = 2, "kahlua" = 1)
	result_amount = 3

/datum/chemical_reaction/te69uilla_sunrise
	result = "te69uillasunrise"
	re69uired_reagents = list("te69uilla" = 2, "orangejuice" = 1)
	result_amount = 3

/datum/chemical_reaction/plasma_special
	result = "plasmaspecial"
	re69uired_reagents = list("rum" = 2, "vermouth" = 2, "plasma" = 2)
	result_amount = 6

/datum/chemical_reaction/beepsky_smash
	result = "beepskysmash"
	re69uired_reagents = list("limejuice" = 1, "whiskey" = 1, "iron" = 1)
	result_amount = 2

/datum/chemical_reaction/doctor_delight
	result = "doctorsdelight"
	re69uired_reagents = list("limejuice" = 1, "tomatojuice" = 1, "orangejuice" = 1, "cream" = 2, "tricordrazine" = 1)
	result_amount = 6

/datum/chemical_reaction/irish_cream
	result = "irishcream"
	re69uired_reagents = list("whiskey" = 2, "cream" = 1)
	result_amount = 3

/datum/chemical_reaction/manly_dorf
	result = "manlydorf"
	re69uired_reagents = list ("beer" = 1, "ale" = 2)
	result_amount = 3

/datum/chemical_reaction/hooch
	result = "hooch"
	re69uired_reagents = list ("sugar" = 1, "ethanol" = 2, "fuel" = 1)
	result_amount = 3

/datum/chemical_reaction/irish_coffee
	result = "irishcoffee"
	re69uired_reagents = list("irishcream" = 1, "coffee" = 1)
	result_amount = 2

/datum/chemical_reaction/b52
	result = "b52"
	re69uired_reagents = list("irishcream" = 1, "kahlua" = 1, "cognac" = 1)
	result_amount = 3

/datum/chemical_reaction/atomicbomb
	result = "atomicbomb"
	re69uired_reagents = list("b52" = 10,69ATERIAL_URANIUM = 1)
	result_amount = 10

/datum/chemical_reaction/margarita
	result = "margarita"
	re69uired_reagents = list("te69uilla" = 2, "limejuice" = 1)
	result_amount = 3

/datum/chemical_reaction/longislandicedtea
	result = "longislandicedtea"
	re69uired_reagents = list("vodka" = 1, "gin" = 1, "te69uilla" = 1, "cubalibre" = 3)
	result_amount = 6

/datum/chemical_reaction/icedtea
	result = "longislandicedtea"
	re69uired_reagents = list("vodka" = 1, "gin" = 1, "te69uilla" = 1, "cubalibre" = 3)
	result_amount = 6

/datum/chemical_reaction/threemileisland
	result = "threemileisland"
	re69uired_reagents = list("longislandicedtea" = 10,69ATERIAL_URANIUM = 1)
	result_amount = 10

/datum/chemical_reaction/whiskeysoda
	result = "whiskeysoda"
	re69uired_reagents = list("whiskey" = 2, "sodawater" = 1)
	result_amount = 3

/datum/chemical_reaction/black_russian
	result = "blackrussian"
	re69uired_reagents = list("vodka" = 2, "kahlua" = 1)
	result_amount = 3

/datum/chemical_reaction/manhattan
	result = "manhattan"
	re69uired_reagents = list("whiskey" = 2, "vermouth" = 1)
	result_amount = 3

/datum/chemical_reaction/manhattan_proj
	result = "manhattan_proj"
	re69uired_reagents = list("manhattan" = 10,69ATERIAL_URANIUM = 1)
	result_amount = 10

/datum/chemical_reaction/vodka_tonic
	result = "vodkatonic"
	re69uired_reagents = list("vodka" = 2, "tonic" = 1)
	result_amount = 3

/datum/chemical_reaction/gin_fizz
	result = "ginfizz"
	re69uired_reagents = list("gin" = 1, "sodawater" = 1, "limejuice" = 1)
	result_amount = 3

/datum/chemical_reaction/bahama_mama
	result = "bahama_mama"
	re69uired_reagents = list("rum" = 2, "orangejuice" = 2, "limejuice" = 1, "ice" = 1)
	result_amount = 6

/datum/chemical_reaction/singulo
	result = "singulo"
	re69uired_reagents = list("vodka" = 5, "radium" = 1, "wine" = 5)
	result_amount = 10

/datum/chemical_reaction/alliescocktail
	result = "alliescocktail"
	re69uired_reagents = list("martini" = 1, "vodka" = 1)
	result_amount = 2

/datum/chemical_reaction/demonsblood
	result = "demonsblood"
	re69uired_reagents = list("rum" = 3, "spacemountainwind" = 1, "blood" = 1, "dr_gibb" = 1)
	result_amount = 6

/datum/chemical_reaction/booger
	result = "booger"
	re69uired_reagents = list("cream" = 2, "banana" = 1, "rum" = 1, "watermelonjuice" = 1)
	result_amount = 5

/datum/chemical_reaction/antifreeze
	result = "antifreeze"
	re69uired_reagents = list("vodka" = 1, "cream" = 1, "ice" = 1)
	result_amount = 3

/datum/chemical_reaction/barefoot
	result = "barefoot"
	re69uired_reagents = list("berryjuice" = 1, "cream" = 1, "vermouth" = 1)
	result_amount = 3

/datum/chemical_reaction/grapesoda
	result = "grapesoda"
	re69uired_reagents = list("grapejuice" = 2, "cola" = 1)
	result_amount = 3

/datum/chemical_reaction/sbiten
	result = "sbiten"
	re69uired_reagents = list("vodka" = 10, "capsaicin" = 1)
	result_amount = 10

/datum/chemical_reaction/red_mead
	result = "red_mead"
	re69uired_reagents = list("blood" = 1, "mead" = 1)
	result_amount = 2

/datum/chemical_reaction/mead
	result = "mead"
	re69uired_reagents = list("honey" = 1, "water" = 1)
	catalysts = list("enzyme" = 5)
	result_amount = 2

/datum/chemical_reaction/iced_beer
	result = "iced_beer"
	re69uired_reagents = list("beer" = 10, "frostoil" = 1)
	result_amount = 10

/datum/chemical_reaction/iced_beer2
	result = "iced_beer"
	re69uired_reagents = list("beer" = 5, "ice" = 1)
	result_amount = 6

/datum/chemical_reaction/grog
	result = "grog"
	re69uired_reagents = list("rum" = 1, "water" = 1)
	result_amount = 2

/datum/chemical_reaction/soy_latte
	result = "soy_latte"
	re69uired_reagents = list("coffee" = 1, "soymilk" = 1)
	result_amount = 2

/datum/chemical_reaction/cafe_latte
	result = "cafe_latte"
	re69uired_reagents = list("coffee" = 1, "milk" = 1)
	result_amount = 2

/datum/chemical_reaction/acidspit
	result = "acidspit"
	re69uired_reagents = list("sacid" = 1, "wine" = 5)
	result_amount = 6

/datum/chemical_reaction/amasec
	result = "amasec"
	re69uired_reagents = list("iron" = 1, "wine" = 5, "vodka" = 5)
	result_amount = 10

/datum/chemical_reaction/changelingsting
	result = "changelingsting"
	re69uired_reagents = list("screwdrivercocktail" = 1, "limejuice" = 1, "lemonjuice" = 1)
	result_amount = 3

/datum/chemical_reaction/aloe
	result = "aloe"
	re69uired_reagents = list("cream" = 1, "whiskey" = 1, "watermelonjuice" = 1)
	result_amount = 3

/datum/chemical_reaction/andalusia
	result = "andalusia"
	re69uired_reagents = list("rum" = 1, "whiskey" = 1, "lemonjuice" = 1)
	result_amount = 3

/datum/chemical_reaction/neurotoxin
	result = "neurotoxin"
	re69uired_reagents = list("gargleblaster" = 1, "stoxin" = 1)
	result_amount = 2

/datum/chemical_reaction/snowwhite
	result = "snowwhite"
	re69uired_reagents = list("beer" = 1, "lemon_lime" = 1)
	result_amount = 2

/datum/chemical_reaction/irishcarbomb
	result = "irishcarbomb"
	re69uired_reagents = list("ale" = 1, "irishcream" = 1)
	result_amount = 2

/datum/chemical_reaction/syndicatebomb
	result = "syndicatebomb"
	re69uired_reagents = list("beer" = 1, "whiskeycola" = 1)
	result_amount = 2

/datum/chemical_reaction/erikasurprise
	result = "erikasurprise"
	re69uired_reagents = list("ale" = 2, "limejuice" = 1, "whiskey" = 1, "banana" = 1, "ice" = 1)
	result_amount = 6

/datum/chemical_reaction/devilskiss
	result = "devilskiss"
	re69uired_reagents = list("blood" = 1, "kahlua" = 1, "rum" = 1)
	result_amount = 3

/datum/chemical_reaction/hippiesdelight
	result = "hippiesdelight"
	re69uired_reagents = list("psilocybin" = 1, "gargleblaster" = 1)
	result_amount = 2

/datum/chemical_reaction/bananahonk
	result = "bananahonk"
	re69uired_reagents = list("banana" = 1, "cream" = 1, "sugar" = 1)
	result_amount = 3

/datum/chemical_reaction/silencer
	result = "silencer"
	re69uired_reagents = list("nothing" = 1, "cream" = 1, "sugar" = 1)
	result_amount = 3

/datum/chemical_reaction/driestmartini
	result = "driestmartini"
	re69uired_reagents = list("nothing" = 1, "gin" = 1)
	result_amount = 2

/datum/chemical_reaction/lemonade
	result = "lemonade"
	re69uired_reagents = list("lemonjuice" = 1, "sugar" = 1, "water" = 1)
	result_amount = 3

/datum/chemical_reaction/kiraspecial
	result = "kiraspecial"
	re69uired_reagents = list("orangejuice" = 1, "limejuice" = 1, "sodawater" = 1)
	result_amount = 3

/datum/chemical_reaction/brownstar
	result = "brownstar"
	re69uired_reagents = list("orangejuice" = 2, "cola" = 1)
	result_amount = 3

/datum/chemical_reaction/milkshake
	result = "milkshake"
	re69uired_reagents = list("cream" = 1, "ice" = 2, "milk" = 2)
	result_amount = 5

/datum/chemical_reaction/rewriter
	result = "rewriter"
	re69uired_reagents = list("spacemountainwind" = 1, "coffee" = 1)
	result_amount = 2

/datum/chemical_reaction/suidream
	result = "suidream"
	re69uired_reagents = list("space_up" = 1, "bluecuracao" = 1, "melonli69uor" = 1)
	result_amount = 3

/datum/chemical_reaction/luminol
	result = "luminol"
	re69uired_reagents = list("hydrazine" = 2, "carbon" = 2, "ammonia" = 2)
	result_amount = 6

/datum/chemical_reaction/mbr
	result = "machine binding ritual"
	re69uired_reagents = list("coffee" = 1, "carbon" = 1, "sugar" = 1, "ethanol" = 1)
	result_amount = 4
	maximum_temperature = 343
	minimum_temperature = 323

/datum/chemical_reaction/machine_spirit
	result = "machine spirit"
	re69uired_reagents = list("machine binding ritual" = 1, "tramadol" = 1, "blattedin" = 1)
	result_amount = 3
	maximum_temperature = 318
	minimum_temperature = 308

/datum/chemical_reaction/party_drops
	result = "party drops"
	re69uired_reagents = list("grape drops" = 1, "machine spirit" = 1, "ultrasurgeon" = 1)
	result_amount = 3

/datum/chemical_reaction/cherry_drops
	result = "cherry drops"
	re69uired_reagents = list("iron" = 1, "nicotine" = 1, "vodka" = 1)
	result_amount = 3
	maximum_temperature = 333
	minimum_temperature = 303

/datum/chemical_reaction/grape_drops
	result = "grape drops"
	re69uired_reagents = list("nanites" = 1, "cherry drops" = 1, "ethanol" = 1)
	result_amount = 3
	maximum_temperature = 343
	minimum_temperature = 338

/datum/chemical_reaction/pro_surgeon
	result = "prosurgeon"
	re69uired_reagents = list("nicotine" = 1, "sugar" = 2, "tungsten" = 2)
	result_amount = 4

/datum/chemical_reaction/ultra_surgeon
	result = "ultrasurgeon"
	re69uired_reagents = list("prosurgeon" = 3, "noexcutite" = 1)
	result_amount = 4
	maximum_temperature = 263
	minimum_temperature = 243

/datum/chemical_reaction/noexcutite
	result = "noexcutite"
	re69uired_reagents = list("tramadol" = 1, "anti_toxin" = 1)
	maximum_temperature = 150
	minimum_temperature = 120
	result_amount = 2

/datum/chemical_reaction/violence
	result = "violence"
	re69uired_reagents = list("acetone" = 1, "ammonia" = 1, "vodka" = 1)
	result_amount = 6
	maximum_temperature = 423
	minimum_temperature = 393

/datum/chemical_reaction/violence_ultra
	result = "violence ultra"
	re69uired_reagents = list("violence" = 1, "gewaltine" = 1, "tramadol" = 1)
	result_amount = 3
	maximum_temperature = 258
	minimum_temperature = 243

/datum/chemical_reaction/bouncer
	result = "bouncer"
	re69uired_reagents = list("inaprovaline" = 1, "vodka" = 1, "tramadol" = 1)
	result_amount = 3
	maximum_temperature = 333
	minimum_temperature = 303

/datum/chemical_reaction/boxer
	result = "boxer"
	re69uired_reagents = list("bouncer" = 1, "starkellin" = 1, "toxin" = 1)
	result_amount = 3
	maximum_temperature = 328
	minimum_temperature = 323

/datum/chemical_reaction/steady
	result = "steady"
	re69uired_reagents = list("nicotine" = 1, "copper" = 1, "tramadol" = 1)
	result_amount = 4
	maximum_temperature = 338
	minimum_temperature = 323

/datum/chemical_reaction/turbo
	result = "turbo"
	re69uired_reagents = list("steady" = 1, "kelotane" = 1, "pararein" = 1)
	result_amount = 3
	maximum_temperature = 293
	minimum_temperature = 288

/datum/chemical_reaction/menace
	result = "menace"
	re69uired_reagents = list("turbo" = 1, "boxer" = 1, "violence ultra" = 1)
	result_amount = 3
	maximum_temperature = 363
	minimum_temperature = 358

/datum/chemical_reaction/sanguinum
	result = "sanguinum"
	re69uired_reagents = list("bicaridine" = 1, "spaceacillin" = 1, "mercury" = 1)
	result_amount = 3

/datum/chemical_reaction/kyphotorin
	result = "kyphotorin"
	re69uired_reagents = list("peridaxon" = 1, "mutagen" = 1, "clonexadone" = 1)
	result_amount = 3

/datum/chemical_reaction/vomitol
	result = "vomitol"
	re69uired_reagents = list("carbon" = 1, "hclacid" = 1, "acetone" = 1)
	result_amount = 3
	maximum_temperature = 683.14 //So it doesn't form back into69omitol, decompose, and form back again when over decomposition point
	minimum_temperature = 0

/datum/chemical_reaction/arectine
	result = "arectine"
	re69uired_reagents = list("ethanol" = 1, "anti_toxin" = 1, "fuel" = 1)
	result_amount = 3

/datum/chemical_reaction/69uickclot
	result = "69uickclot"
	re69uired_reagents = list("kelotane" = 1, "clonexadone" = 1)
	result_amount = 2
	catalysts = list("plasma" = 1)

/datum/chemical_reaction/ossisine
	result = "ossisine"
	re69uired_reagents = list("stoxin" = 1, "clonexadone" = 1, "bicaridine" = 1)
	result_amount = 3

/datum/chemical_reaction/instant_ice
	result = "instant_ice"
	re69uired_reagents = list("hydrazine" = 1, "acetone" = 1, "sodiumchloride" = 1)
	result_amount = 3

/datum/chemical_reaction/instant_ice_with_water
	result = "water"
	supports_decomposition_by_electrolysis = FALSE
	re69uired_reagents = list("instant_ice" = 3, "water" = 3)
	result_amount = 4


/datum/chemical_reaction/instant_ice_with_water/on_reaction(datum/reagents/holder,69ar/created_volume)
	..()
	holder.chem_temp =69ax(223, holder.chem_temp - abs(holder.chem_temp - 223) * created_volume/holder.total_volume) // if someone actually wants to do some physics here they are welcome
	return 0

/datum/chemical_reaction/detox
	result = "detox"
	re69uired_reagents = list("serotrotium" = 1, "inaprovaline" = 3)
	result_amount = 4
	maximum_temperature = INFINITY
	minimum_temperature = 363

/datum/chemical_reaction/polystem
	result = "polystem"
	re69uired_reagents = list("pacid" = 1, "iron" = 1, "potassium" = 3)
	result_amount = 5
	maximum_temperature = 168
	minimum_temperature = 124

/datum/chemical_reaction/purger
	result = "purger"
	re69uired_reagents = list("mindbreaker" = 1, "anti_toxin" = 3)
	result_amount = 4
	maximum_temperature = INFINITY
	minimum_temperature = 363

/datum/chemical_reaction/addictol
	result = "addictol"
	re69uired_reagents = list("mercury" = 2, "purger" = 2, "impedrezene" = 2)
	result_amount = 3

/datum/chemical_reaction/aminazine
	result = "aminazine"
	re69uired_reagents = list("purger" = 1, "alkysine" = 1)
	result_amount = 2

/datum/chemical_reaction/haloperidol
	result = "haloperidol"
	re69uired_reagents = list("anti_toxin" = 2, "leporazine" = 1)
	result_amount = 3
	maximum_temperature = 340
	minimum_temperature = 290

/datum/chemical_reaction/ethanol
	result = "ethanol"
	re69uired_reagents = list("water" = 3, "sugar" = 1)
	result_amount = 4
	catalysts = list("enzyme" = 5)
	maximum_temperature = INFINITY
	minimum_temperature = 363

/datum/chemical_reaction/adrenaline
	result = "adrenaline"
	re69uired_reagents = list("blood" = 3, "dexalin" = 1)
	result_amount = 4
	maximum_temperature = INFINITY
	minimum_temperature = 373

/datum/chemical_reaction/carbon
	result = "carbon"
	re69uired_reagents = list("woodpulp" = 3)
	result_amount = 2
	maximum_temperature = INFINITY
	minimum_temperature = 373

/datum/chemical_reaction/cyanide
	result = "cyanide"
	re69uired_reagents = list("toxin" = 5, "mindbreaker" = 3, "fuhrerole" = 2)
	result_amount = 2
	maximum_temperature = 33
	minimum_temperature = 10

/datum/chemical_reaction/serotrotium
	result = "serotrotium"
	re69uired_reagents = list("blood" = 5, "psilocybin" = 1)
	catalysts = list("nutriment" = 5)
	result_amount = 4
	maximum_temperature = 273
	minimum_temperature = 203

/datum/chemical_reaction/oil
	result = "oil"
	re69uired_reagents = list("fuel" = 1, "carbon" = 1, "ethanol" = 1)
	result_amount = 3
	maximum_temperature = INFINITY
	minimum_temperature = 480

/datum/chemical_reaction/plasticide
	result = "plasticide"
	re69uired_reagents = list("oil" = 1, "ethanol" = 1, "silicon" = 1)
	result_amount = 3
	maximum_temperature = 270
	minimum_temperature = 0

/datum/chemical_reaction/glue
	result = "glue"
	re69uired_reagents = list("plasticide" = 1, "ethanol" = 1, "carbon" = 1)
	result_amount = 3
	maximum_temperature = INFINITY
	minimum_temperature = 363

/datum/chemical_reaction/eznutrient
	result = "eznutrient"
	re69uired_reagents = list("ammonia" = 1, "carbon" = 3)
	result_amount = 4

/datum/chemical_reaction/left4zed
	result = "left4zed"
	re69uired_reagents = list("nutriment" = 1, "radium" = 3)
	result_amount = 4

/datum/chemical_reaction/robustharvest
	result = "robustharvest"
	re69uired_reagents = list("eznutrient" = 1, "sugar" = 3, "carbon" = 3)
	result_amount = 7

/datum/chemical_reaction/arad
	result = "arad69anites"
	re69uired_reagents = list("nanites" = 1, "arithrazine" = 1)
	result_amount = 1

/datum/chemical_reaction/implant_medics
	result = "implant69anites"
	re69uired_reagents = list("nanites" = 1, "aluminum" = 1)
	result_amount = 1

/datum/chemical_reaction/nantidotes
	result = "nantidotes"
	re69uired_reagents = list("nanites" = 1, "haloperidol" = 1)
	result_amount = 1

/datum/chemical_reaction/nanosymbiotes
	result = "nanosymbiotes"
	re69uired_reagents = list("nanites" = 1, "peridaxon" = 1)
	result_amount = 1

/datum/chemical_reaction/oxyrush
	result = "oxyrush"
	re69uired_reagents = list("nanites" = 1, "dexalin" = 1)
	result_amount = 1

/datum/chemical_reaction/trauma_control_system
	result = "trauma_control_system"
	re69uired_reagents = list("nanites" = 1, "bicaridine" = 1)
	result_amount = 1

/datum/chemical_reaction/nanopurgers
	result = "nanopurgers"
	re69uired_reagents = list("nanites" = 1, "vomitol" = 1)
	result_amount = 1

/datum/chemical_reaction/cbu
	result = "cbu"
	re69uired_reagents = list("uncap69anites" = 1, "party drops" = 1)
	result_amount = 1

/datum/chemical_reaction/cbc
	result = "cbc"
	re69uired_reagents = list("uncap69anites" = 1, "menace" = 1)
	result_amount = 1

/datum/chemical_reaction/nanohands
	result = "nanohands"
	re69uired_reagents = list("uncap69anites" = 1, "sterilizine" = 1)
	result_amount = 1

/datum/chemical_reaction/nanovoice
	result = "nanovoice"
	re69uired_reagents = list("uncap69anites" = 1, "synaptizine" = 1)
	result_amount = 1

/datum/chemical_reaction/rejuvenating_agent
	result = "rejuvenating_agent"
	re69uired_reagents = list("cleaner" = 2, "pacid" = 1, "sulfur" = 1)
	result_amount = 2

/datum/chemical_reaction/roachbeer
	result = "roachbeer"
	re69uired_reagents = list("water" = 2, "diplopterum" = 1, "fuel" = 1, "beer" = 1)
	result_amount = 1

/datum/chemical_reaction/kaiserbeer
	result = "kaiserbeer"
	re69uired_reagents = list("fuhrerole" = 1, "kaiseraurum" = 1, "roachbeer" = 2)
	result_amount = 2
