#define SURGERY_FAILURE -1

#define AUTODOC_DAMAGE          1
#define AUTODOC_EMBED_OBJECT	1 << 1
#define AUTODOC_FRACTURE 		1 << 2
#define AUTODOC_IB				1 << 3
#define AUTODOC_OPEN_WOUNDS		1 << 4

#define AUTODOC_BLOOD			1 << 5
#define AUTODOC_TOXIN			1 << 6
#define AUTODOC_DIALYSIS		1 << 7
#define AUTODOC_DIALYSIS_AMOUNT 5

#define AUTODOC_SCAN_COST           200
#define AUTODOC_DAMAGE_COST         800
#define AUTODOC_EMBED_OBJECT_COST	1000
#define AUTODOC_FRACTURE_COST       1200
#define AUTODOC_IB_COST				1200
#define AUTODOC_OPEN_WOUNDS_COST    600
#define AUTODOC_BLOOD_COST          800
#define AUTODOC_TOXIN_COST			600
#define AUTODOC_DIALYSIS_COST		1000