#define SURGERY_FAILURE -1

#define AUTODOC_DAMAGE	1
#define AUTODOC_INNER_DAMAGE	1 << 1
#define AUTODOC_EMBED_OBJECT	1 << 2
#define AUTODOC_FRACTURE 		1 << 3
#define AUTODOC_IB				1 << 4
#define AUTODOC_OPEN_WOUNDS		1 << 5

#define AUTODOC_TOXIN			1 << 8
#define AUTODOC_DIALYSIS		1 << 9
#define AUTODOC_DIALYSIS_AMOUNT 5