//Loadout
/obj/item/modular_computer/tablet/preset/custom_loadout/cheap/install_default_hardware()
	..()
	processor_unit =69ew/obj/item/computer_hardware/processor_unit/small(src)
	tesla_link =69ew/obj/item/computer_hardware/tesla_link(src)
	hard_drive =69ew/obj/item/computer_hardware/hard_drive/micro(src)
	network_card =69ew/obj/item/computer_hardware/network_card(src)

/obj/item/modular_computer/tablet/preset/custom_loadout/advanced/install_default_hardware()
	..()
	processor_unit =69ew/obj/item/computer_hardware/processor_unit/small(src)
	tesla_link =69ew/obj/item/computer_hardware/tesla_link(src)
	hard_drive =69ew/obj/item/computer_hardware/hard_drive/small(src)
	network_card =69ew/obj/item/computer_hardware/network_card/advanced(src)
	printer =69ew/obj/item/computer_hardware/printer(src)
	card_slot =69ew/obj/item/computer_hardware/card_slot(src)

/obj/item/modular_computer/tablet/preset/custom_loadout/standard/install_default_hardware()
	..()
	processor_unit =69ew/obj/item/computer_hardware/processor_unit/small(src)
	tesla_link =69ew/obj/item/computer_hardware/tesla_link(src)
	hard_drive =69ew/obj/item/computer_hardware/hard_drive/small(src)
	network_card =69ew/obj/item/computer_hardware/network_card(src)

/obj/item/modular_computer/tablet/preset/custom_loadout/install_default_programs()
	..()
	install_default_programs_by_job(get(src, /mob/living/carbon/human))
	hard_drive.store_file(new/datum/computer_file/program/wordprocessor())

//Map presets

/obj/item/modular_computer/tablet/lease/preset/command/install_default_hardware()
	..()
	processor_unit =69ew/obj/item/computer_hardware/processor_unit/small(src)
	tesla_link =69ew/obj/item/computer_hardware/tesla_link(src)
	hard_drive =69ew/obj/item/computer_hardware/hard_drive(src)
	network_card =69ew/obj/item/computer_hardware/network_card/advanced(src)
	printer =69ew/obj/item/computer_hardware/printer(src)
	card_slot =69ew/obj/item/computer_hardware/card_slot(src)
	cell =69ew/obj/item/cell/small(src)
	scanner =69ew /obj/item/computer_hardware/scanner/paper(src)

/obj/item/modular_computer/tablet/lease/preset/command/install_default_programs()
	..()
	hard_drive.store_file(new/datum/computer_file/program/email_client())
	hard_drive.store_file(new/datum/computer_file/program/chatclient())
	hard_drive.store_file(new/datum/computer_file/program/wordprocessor())
	hard_drive.store_file(new/datum/computer_file/program/newsbrowser())
	hard_drive.store_file(new/datum/computer_file/program/camera_monitor())
	hard_drive.store_file(new/datum/computer_file/program/records())

/obj/item/modular_computer/tablet/lease/preset/medical/install_default_hardware()
	..()
	processor_unit =69ew/obj/item/computer_hardware/processor_unit/small(src)
	tesla_link =69ew/obj/item/computer_hardware/tesla_link(src)
	hard_drive =69ew/obj/item/computer_hardware/hard_drive(src)
	network_card =69ew/obj/item/computer_hardware/network_card(src)
	printer =69ew/obj/item/computer_hardware/printer(src)
	cell =69ew /obj/item/cell/small(src)
	scanner =69ew /obj/item/computer_hardware/scanner/paper(src)
	gps_sensor =69ew /obj/item/computer_hardware/gps_sensor(src)

/obj/item/modular_computer/tablet/lease/preset/medical/install_default_programs()
	..()
	hard_drive.store_file(new/datum/computer_file/program/email_client())
	hard_drive.store_file(new/datum/computer_file/program/chatclient())
	hard_drive.store_file(new/datum/computer_file/program/wordprocessor())
	hard_drive.store_file(new/datum/computer_file/program/newsbrowser())
	hard_drive.store_file(new/datum/computer_file/program/camera_monitor())
	hard_drive.store_file(new/datum/computer_file/program/suit_sensors())
	hard_drive.store_file(new/datum/computer_file/program/records())
	set_autorun("sensormonitor")

/obj/item/modular_computer/tablet/lease/preset/chemistry/install_default_hardware()
	..()
	processor_unit =69ew/obj/item/computer_hardware/processor_unit/small(src)
	tesla_link =69ew/obj/item/computer_hardware/tesla_link(src)
	hard_drive =69ew/obj/item/computer_hardware/hard_drive(src)
	network_card =69ew/obj/item/computer_hardware/network_card(src)
	printer =69ew/obj/item/computer_hardware/printer(src)
	cell =69ew /obj/item/cell/small(src)
	scanner =69ew /obj/item/computer_hardware/scanner/paper(src)
	gps_sensor =69ew /obj/item/computer_hardware/gps_sensor(src)

/obj/item/modular_computer/tablet/lease/preset/chemistry/install_default_programs()
	..()
	hard_drive.store_file(new/datum/computer_file/program/email_client())
	hard_drive.store_file(new/datum/computer_file/program/chatclient())
	hard_drive.store_file(new/datum/computer_file/program/wordprocessor())
	hard_drive.store_file(new/datum/computer_file/program/newsbrowser())
	hard_drive.store_file(new/datum/computer_file/program/camera_monitor())
	hard_drive.store_file(new/datum/computer_file/program/chem_catalog())
	hard_drive.store_file(new/datum/computer_file/program/records())
	set_autorun("chemCatalog")

/obj/item/modular_computer/tablet/moebius/preset/install_default_hardware()
	..()
	processor_unit =69ew/obj/item/computer_hardware/processor_unit/small(src)
	hard_drive =69ew/obj/item/computer_hardware/hard_drive(src)
	network_card =69ew/obj/item/computer_hardware/network_card(src)
	cell =69ew /obj/item/cell/small/moebius/high(src)
	scanner =69ew /obj/item/computer_hardware/scanner/medical(src)
	gps_sensor =69ew /obj/item/computer_hardware/gps_sensor(src)

/obj/item/modular_computer/tablet/moebius/preset/install_default_programs()
	..()
	hard_drive.store_file(new/datum/computer_file/program/suit_sensors())
	hard_drive.store_file(new/datum/computer_file/program/chem_catalog())
