/obj/structure/closet/secure_closet/reinforced/chaplain
	name = "preacher's locker"
	re69_access = list(access_chapel_office)
	icon_state = "head_preacher"

/obj/structure/closet/secure_closet/reinforced/chaplain/populate_contents()
	if(prob(25))
		new /obj/item/stora69e/backpack/neotheolo69y(src)
	else if(prob(25))
		new /obj/item/stora69e/backpack/sport/neotheolo69y(src)
	else
		new /obj/item/stora69e/backpack/satchel/neotheolo69y(src)
	new /obj/item/clothin69/under/rank/preacher(src)
	new /obj/item/clothin69/under/rank/preacher(src)
	new /obj/item/stora69e/belt/sheath(src)
	new /obj/item/device/radio/headset/church(src)
	new /obj/item/stora69e/belt/tactical/neotheolo69y(src)
	new /obj/item/clothin69/shoes/reinforced(src)
	new /obj/item/clothin69/shoes/reinforced(src)
	new /obj/item/clothin69/suit/stora69e/neotheolo69y_jacket(src)
	new /obj/item/clothin69/suit/stora69e/neotheolo69y_jacket(src)
	new /obj/item/clothin69/69loves/thick(src)
	new /obj/item/clothin69/under/rank/church/sport(src)
	new /obj/item/clothin69/suit/stora69e/neotheosports(src)
	new /obj/item/clothin69/69loves/thick(src)
	new /obj/item/stora69e/fancy/candle_box(src)
	new /obj/item/stora69e/fancy/candle_box(src)
	new /obj/item/deck/tarot(src)
	new /obj/item/stora69e/box/headset/church
	for (var/i in 1 to 10)
		new /obj/item/implant/core_implant/cruciform(src)
	new /obj/item/tool/knife/neotritual(src)
	new /obj/item/69un/ener69y/nt_svalinn(src)
	new /obj/item/cell/small/neotheolo69y/plasma(src)
	new /obj/item/cell/small/neotheolo69y/plasma(src)
	new /obj/item/tool/sword/nt/lon69sword(src)
	new /obj/item/tool/knife/da6969er/nt(src)
	new /obj/item/stora69e/box/ids(src)
