#define CYBERAVATAR_INITIALIZATION(typeOfAtom, DefaultColor) ##typeOfAtom/CyberAvatar = DefaultColor


//CYBERAVATAR_INITIALIZATION(/obj/item, CYBERSPACE_SHADOW_COLOR)
CYBERAVATAR_INITIALIZATION(/obj/machinery, CYBERSPACE_MAIN_COLOR)
CYBERAVATAR_INITIALIZATION(/obj/item/modular_computer, CYBERSPACE_MAIN_COLOR)
CYBERAVATAR_INITIALIZATION(/mob/living/carbon/superior_animal/roach/bluespace, CYBERSPACE_BLUESPACE)
CYBERAVATAR_INITIALIZATION(/mob/living/carbon/superior_animal/roach/nanite, CYBERSPACE_MAIN_COLOR)
CYBERAVATAR_INITIALIZATION(/obj/structure/cyberplant, CYBERSPACE_MAIN_COLOR)
