/obj/machinery/vending/serbomat
	name = "From Serbia with love"
	desc = "How did this end up here?"
	icon_state = "serbomat"
	product_ads = "For Tsar and Country.;Have you fulfilled your nutrition quota today?;Very nice!;We are simple people, for this is all we eat.;If there is a person, there is a problem. If there is no person, then there is no problem.;Our ERPs are definitely free of food additives and totally not laced to the brim with harmful chems. Try it out!."
	products = list(
					/obj/item/reagent_containers/food/drinks/bottle/vodka = 60, // ghetto antihacking, have fun
					/obj/item/storage/deferred/crate/uniform_green = 4,
					/obj/item/storage/deferred/crate/uniform_brown = 4,
					/obj/item/storage/deferred/crate/uniform_black = 4,
					/obj/item/storage/deferred/crate/uniform_flak  = 2,
					/obj/item/storage/deferred/crate/uniform_light = 2,
					/obj/item/gun/projectile/kovacs = 2,
					/obj/item/ammo_magazine/srifle = 6,
					/obj/item/gun/projectile/boltgun/serbian = 10,
					/obj/item/ammo_magazine/ammobox/lrifle_small = 30,
					/obj/item/storage/ration_pack = 10,
					/obj/item/clothing/mask/balaclava = 50
					)
	prices = list(
					/obj/item/reagent_containers/food/drinks/bottle/vodka = 50,
          			/obj/item/storage/deferred/crate/uniform_green = 2000,
          			/obj/item/storage/deferred/crate/uniform_brown = 2000,
					/obj/item/storage/deferred/crate/uniform_black = 2000,
					/obj/item/storage/deferred/crate/uniform_flak  = 2200,
					/obj/item/storage/deferred/crate/uniform_light = 1800,
					/obj/item/gun/projectile/kovacs = 3000,
					/obj/item/ammo_magazine/ammobox/lrifle_small = 400,
					/obj/item/ammo_magazine/srifle = 300,
					/obj/item/gun/projectile/boltgun/serbian = 1000,
					/obj/item/storage/ration_pack = 800,
					/obj/item/clothing/mask/balaclava = 100
					)
	idle_power_usage = 211
	vendor_department = DEPARTMENT_OFFSHIP

/obj/machinery/vending/billomat
	name = "Bill Trustworthy's Discount Guns and Enterprising Detritus"
	desc = "Some relic of an arms dealer's business, its owner most likely long dead."
	product_slogans = "Discount guns for discount prices!;Also see our used ship line!;From the home of Challenge Pissing!"
	product_ads = "Brought to you by the man behind Bill Trustworthy's Used Ships!;Don't wait! Don't delay! Don't fuck with us!;Lifetime warranty! (it won't last that long.);Coolness sold seperately.;Also see Rent-A-Nuke!"
	icon_state = "trashvend"
	products = list(
					/obj/item/ammo_magazine/lrifle = 12,
					/obj/item/ammo_magazine/hpistol = 12,
					/obj/item/ammo_magazine/srifle = 12,
					/obj/item/ammo_magazine/smg = 12,
					/obj/item/part/armor = 30,
					/obj/item/part/gun = 30,
					/obj/item/gun/projectile/automatic/ak47/fs = 4,
					/obj/item/gun/energy/retro = 4,
					/obj/item/gun/projectile/shotgun/doublebarrel = 4,
					/obj/item/gun/projectile/mk58  = 2,
					/obj/item/gun/projectile/mk58/wood = 2,
					/obj/item/gun/projectile/colt = 4,
					/obj/item/gun/projectile/revolver/deckard = 2,
					/obj/item/gun/projectile/automatic/z8 = 4,
					/obj/item/gun/projectile/automatic/molly = 4,
					/obj/item/gun/projectile/shotgun/pump/gladstone = 4,
					/obj/item/gun/projectile/shotgun/pump/regulator = 4,
					/obj/item/storage/deferred/crate/clown_crime = 2,
					/obj/item/storage/deferred/crate/clown_crime/wolf = 2,
					/obj/item/storage/deferred/crate/clown_crime/hoxton = 2,
					/obj/item/storage/deferred/crate/clown_crime/chains = 2
					)
	contraband = list(
					/obj/item/gun/projectile/mandella = 4,
					/obj/item/ammo_magazine/cspistol = 12,
					/obj/item/computer_hardware/hard_drive/portable/design/guns/scaramanga = 1)
	prices = list(
					/obj/item/ammo_magazine/lrifle = 400,
					/obj/item/ammo_magazine/hpistol = 300,
					/obj/item/ammo_magazine/cspistol = 400,
					/obj/item/ammo_magazine/srifle = 300,
					/obj/item/ammo_magazine/smg = 400,
					/obj/item/part/armor = 700,
					/obj/item/part/gun = 700,
					/obj/item/gun/projectile/automatic/ak47/fs = 3200,
					/obj/item/gun/energy/retro = 1200,
					/obj/item/gun/projectile/shotgun/doublebarrel = 1400,
					/obj/item/gun/projectile/mk58  = 900,
					/obj/item/gun/projectile/mk58/wood = 900,
					/obj/item/gun/projectile/colt = 1200,
					/obj/item/gun/projectile/mandella = 1800,
					/obj/item/gun/projectile/revolver/deckard = 3600,
					/obj/item/gun/projectile/automatic/z8 = 3500,
					/obj/item/gun/projectile/automatic/molly = 1700,
					/obj/item/gun/projectile/shotgun/pump/gladstone = 2200,
					/obj/item/gun/projectile/shotgun/pump/regulator = 2400,
					/obj/item/storage/deferred/crate/clown_crime = 1800,
					/obj/item/storage/deferred/crate/clown_crime/wolf = 1800,
					/obj/item/storage/deferred/crate/clown_crime/hoxton = 1800,
					/obj/item/storage/deferred/crate/clown_crime/chains = 1800,
					/obj/item/computer_hardware/hard_drive/portable/design/guns/scaramanga = 7000
					)
	idle_power_usage = 211
	vendor_department = DEPARTMENT_OFFSHIP
